In [1]:
import pandas as pd

PATH = "csse_covid_19_data/csse_covid_19_daily_reports/"

doc = pd.read_csv(f"{PATH}04-01-2020.csv", encoding = "utf-8-sig")

In [2]:
doc

,FIPS,Admin2,Province_State,Country_Region,Last_Update,Lat,Long_,Confirmed,Deaths,Recovered,Active,Combined_Key
0,45001.0,Abbeville,South Carolina,US,2020-04-01 21:58:49,34.223334,-82.461707,4,0,0,4,"Abbeville, South Carolina, US"
1,22001.0,Acadia,Louisiana,US,2020-04-01 21:58:49,30.295065,-92.414197,47,1,0,46,"Acadia, Louisiana, US"
2,51001.0,Accomack,Virginia,US,2020-04-01 21:58:49,37.767072,-75.632346,7,0,0,7,"Accomack, Virginia, US"
3,16001.0,Ada,Idaho,US,2020-04-01 21:58:49,43.452658,-116.241552,195,3,0,192,"Ada, Idaho, US"
4,19001.0,Adair,Iowa,US,2020-04-01 21:58:49,41.330756,-94.471059,1,0,0,1,"Adair, Iowa, US"
...,...,...,...,...,...,...,...,...,...,...,...,...
2517,82604.0,NaN,Wales,United Kingdom,2020-04-01 21:58:49,52.130700,-3.783700,0,198,0,0,"Wales, United Kingdom"
2518,NaN,NaN,NaN,Nauru,2020-04-01 21:58:49,-0.522800,166.931500,0,0,0,0,Nauru
2519,NaN,NaN,Niue,New Zealand,2020-04-01 21:58:49,-19.054400,-169.867200,0,0,0,0,"Niue, New Zealand"
2520,NaN,NaN,NaN,Tuvalu,2020-04-01 21:58:49,-7.109500,177.649300,0,0,0,0,Tuvalu
2521,NaN,NaN,Pitcairn Islands,United Kingdom,2020-04-01 21:58:49,-24.376800,-128.324200,0,0,0,0,"Pitcairn Islands, United Kingdom"

In [3]:
# 왜 국가에서부터 데이터를 보려고 하는가?
# 국가별 코로나 발병 추이

countries = doc["Country_Region"]
countries.head()

0    US
1    US
2    US
3    US
4    US
Name: Country_Region, dtype: object

In [4]:
print(countries.size, countries.count())

2522 2522

In [5]:
print(countries.unique(), len(countries.unique()))
# 전체 행 갯수 = 2522개, 실제 집계된 국가 수 190개

['US' 'Canada' 'United Kingdom' 'China' 'Netherlands' 'Australia'
 'Denmark' 'France' 'Afghanistan' 'Albania' 'Algeria' 'Andorra' 'Angola'
 'Antigua and Barbuda' 'Argentina' 'Armenia' 'Austria' 'Azerbaijan'
 'Bahamas' 'Bahrain' 'Bangladesh' 'Barbados' 'Belarus' 'Belgium' 'Belize'
 'Benin' 'Bhutan' 'Bolivia' 'Bosnia and Herzegovina' 'Botswana' 'Brazil'
 'Brunei' 'Bulgaria' 'Burkina Faso' 'Burma' 'Burundi' 'Cabo Verde'
 'Cambodia' 'Cameroon' 'Central African Republic' 'Chad' 'Chile'
 'Colombia' 'Congo (Brazzaville)' 'Congo (Kinshasa)' 'Costa Rica'
 "Cote d'Ivoire" 'Croatia' 'Cuba' 'Cyprus' 'Czechia' 'Diamond Princess'
 'Djibouti' 'Dominica' 'Dominican Republic' 'Ecuador' 'Egypt'
 'El Salvador' 'Equatorial Guinea' 'Eritrea' 'Estonia' 'Eswatini'
 'Ethiopia' 'Fiji' 'Finland' 'Gabon' 'Gambia' 'Georgia' 'Germany' 'Ghana'
 'Greece' 'Grenada' 'Guatemala' 'Guinea' 'Guinea-Bissau' 'Guyana' 'Haiti'
 'Holy See' 'Honduras' 'Hungary' 'Iceland' 'India' 'Indonesia' 'Iran'
 'Iraq' 'Ireland' 'Israel' 'Italy' 'Jamaica' 'Japan' 'Jordan' 'Kazakhstan'
 'Kenya' 'Korea, South' 'Kosovo' 'Kuwait' 'Kyrgyzstan' 'Laos' 'Latvia'
 'Lebanon' 'Liberia' 'Libya' 'Liechtenstein' 'Lithuania' 'Luxembourg'
 'MS Zaandam' 'Madagascar' 'Maldives' 'Mali' 'Malta' 'Mauritania'
 'Mauritius' 'Mexico' 'Moldova' 'Monaco' 'Mongolia' 'Montenegro' 'Morocco'
 'Mozambique' 'Namibia' 'Nepal' 'New Zealand' 'Nicaragua' 'Niger'
 'Nigeria' 'North Macedonia' 'Norway' 'Oman' 'Pakistan' 'Panama'
 'Papua New Guinea' 'Paraguay' 'Peru' 'Philippines' 'Poland' 'Portugal'
 'Qatar' 'Romania' 'Russia' 'Rwanda' 'Saint Kitts and Nevis' 'Saint Lucia'
 'Saint Vincent and the Grenadines' 'Samoa' 'San Marino' 'Saudi Arabia'
 'Senegal' 'Serbia' 'Seychelles' 'Sierra Leone' 'Singapore' 'Slovakia'
 'Slovenia' 'Somalia' 'South Africa' 'Spain' 'Sri Lanka' 'Sudan'
 'Suriname' 'Sweden' 'Switzerland' 'Syria' 'Taiwan*' 'Tanzania' 'Thailand'
 'Timor-Leste' 'Togo' 'Trinidad and Tobago' 'Tunisia' 'Turkey' 'Uganda'
 'Ukraine' 'United Arab Emirates' 'Uruguay' 'Uzbekistan' 'Venezuela'
 'Vietnam' 'West Bank and Gaza' 'Zambia' 'Zimbabwe' 'Kiribati' 'Palau'
 'Summer Olympics 2020' 'Malaysia' 'Tonga' 'Winter Olympics 2022'
 'Antarctica' 'Korea, North' 'Nauru' 'Tuvalu'] 190

In [6]:
countries.value_counts()

Country_Region
US                2228
China               34
United Kingdom      18
Malaysia            17
Canada              16
                  ...
Ghana                1
Greece               1
Grenada              1
Guatemala            1
Tuvalu               1
Name: count, Length: 190, dtype: int64

In [ ]:
# 해당 데이터는 미국이 주도함, 미국이 거의 90%에 해당하는 데이터 지분율을 갖고 있다
# 국가별 발병=> 국가의 정체는 확인함
# 국가 + 발병과 관련된 관련 컬럼 정리 => 확진, 사망, 회복

In [7]:
covid_stat = doc[["Confirmed", "Deaths", "Recovered"]]
covid_stat.head()

   Confirmed  Deaths  Recovered
0          4       0          0
1         47       1          0
2          7       0          0
3        195       3          0
4          1       0          0

In [8]:
# 미국 국가에 한해서 데이터 추출!!
import pandas as pd

PATH = "csse_covid_19_data/csse_covid_19_daily_reports/"

doc = pd.read_csv(f"{PATH}04-01-2020.csv", encoding = "utf-8-sig")

In [9]:
doc_us = doc[doc["Country_Region"] == "US"]
doc_us

,FIPS,Admin2,Province_State,Country_Region,Last_Update,Lat,Long_,Confirmed,Deaths,Recovered,Active,Combined_Key
0,45001.0,Abbeville,South Carolina,US,2020-04-01 21:58:49,34.223334,-82.461707,4,0,0,4,"Abbeville, South Carolina, US"
1,22001.0,Acadia,Louisiana,US,2020-04-01 21:58:49,30.295065,-92.414197,47,1,0,46,"Acadia, Louisiana, US"
2,51001.0,Accomack,Virginia,US,2020-04-01 21:58:49,37.767072,-75.632346,7,0,0,7,"Accomack, Virginia, US"
3,16001.0,Ada,Idaho,US,2020-04-01 21:58:49,43.452658,-116.241552,195,3,0,192,"Ada, Idaho, US"
4,19001.0,Adair,Iowa,US,2020-04-01 21:58:49,41.330756,-94.471059,1,0,0,1,"Adair, Iowa, US"
...,...,...,...,...,...,...,...,...,...,...,...,...
2246,66000.0,NaN,Guam,US,2020-04-01 21:58:49,13.444300,144.793700,77,3,0,74,"Guam, US"
2273,NaN,NaN,Northern Mariana Islands,US,2020-04-01 21:58:49,15.097900,145.673900,2,0,0,2,",Northern Mariana Islands,US"
2280,NaN,NaN,Puerto Rico,US,2020-04-01 21:58:49,18.220800,-66.590100,286,11,0,275,"Puerto Rico, US"
2285,NaN,NaN,Recovered,US,2020-04-01 21:58:49,0.000000,0.000000,0,0,8474,0,"Recovered, US"
2303,NaN,NaN,Virgin Islands,US,2020-04-01 21:58:49,18.335800,-64.896300,30,0,0,30,",Virgin Islands,US"

In [29]:
# 1) 필요로하는 컬럼만 찾아오는 방법
# 2) 특정 국가만 조회하는 방법
# 3) 결측이 발생했을 때 대처하는 방법

In [10]:
doc = pd.read_csv(f"{PATH}01-22-2020.csv", encoding = "utf-8-sig")

In [11]:
doc.isnull().sum()

Province/State    12
Country/Region     0
Last Update        0
Confirmed         10
Deaths            37
Recovered         37
dtype: int64

In [ ]:
# 결측치를 제거 = 삭제 (* 전체 데이터 가운데, 결측치가 차지하는 비율이 극소수일 경우)
# 결측치 내부 값을 0 혹은 빈문자 처리 (* 향후 연산 등의 에러 발생률 감소, 평균값 구했을 때 오류)
# 결측치 내부 값을 전체 데이터의 평균 혹은 중앙값 대체 (* 결측의 비율이 작지 않은 상태에서 향후 평균 등 연산처리 시, 왜곡된 데이터를 발생하진 않음)

In [12]:
doc = doc.dropna() # not available
doc.head()

,Province/State,Country/Region,Last Update,Confirmed,Deaths,Recovered
13,Hubei,Mainland China,1/22/2020 17:00,444.0,17.0,28.0
41,Cook Islands,New Zealand,1/22/2020 17:00,0.0,0.0,0.0
43,Johor,Malaysia,1/22/2020 17:00,0.0,0.0,0.0
44,Kedah,Malaysia,1/22/2020 17:00,0.0,0.0,0.0
45,Kelantan,Malaysia,1/22/2020 17:00,0.0,0.0,0.0

In [13]:
doc.isnull().sum()

Province/State    0
Country/Region    0
Last Update       0
Confirmed         0
Deaths            0
Recovered         0
dtype: int64

In [ ]:
# 결측치의 데이터라고 해서 다같은 비중을 차지하는 결측치는 아님
# A컬럼에서의 결측과 B컬럼에서의 결측의 가치와 비중은 다를 수 있음

In [14]:
doc = pd.read_csv(f"{PATH}01-22-2020.csv", encoding = "utf-8-sig")

In [15]:
doc.head()

,Province/State,Country/Region,Last Update,Confirmed,Deaths,Recovered
0,Anhui,Mainland China,1/22/2020 17:00,1.0,NaN,NaN
1,Beijing,Mainland China,1/22/2020 17:00,14.0,NaN,NaN
2,Chongqing,Mainland China,1/22/2020 17:00,6.0,NaN,NaN
3,Fujian,Mainland China,1/22/2020 17:00,1.0,NaN,NaN
4,Gansu,Mainland China,1/22/2020 17:00,NaN,NaN,NaN

In [16]:
doc.isnull().sum()

Province/State    12
Country/Region     0
Last Update        0
Confirmed         10
Deaths            37
Recovered         37
dtype: int64

In [17]:
doc = doc.dropna(subset = ["Confirmed"])
doc.head()

,Province/State,Country/Region,Last Update,Confirmed,Deaths,Recovered
0,Anhui,Mainland China,1/22/2020 17:00,1.0,NaN,NaN
1,Beijing,Mainland China,1/22/2020 17:00,14.0,NaN,NaN
2,Chongqing,Mainland China,1/22/2020 17:00,6.0,NaN,NaN
3,Fujian,Mainland China,1/22/2020 17:00,1.0,NaN,NaN
5,Guangdong,Mainland China,1/22/2020 17:00,26.0,NaN,NaN

In [18]:
doc.isnull().sum()

Province/State    12
Country/Region     0
Last Update        0
Confirmed          0
Deaths            27
Recovered         27
dtype: int64

In [26]:
doc = pd.read_csv(f"{PATH}01-22-2020.csv", encoding = "utf-8-sig")

In [27]:
doc.fillna(0)

,Province/State,Country/Region,Last Update,Confirmed,Deaths,Recovered
0,Anhui,Mainland China,1/22/2020 17:00,1.0,0.0,0.0
1,Beijing,Mainland China,1/22/2020 17:00,14.0,0.0,0.0
2,Chongqing,Mainland China,1/22/2020 17:00,6.0,0.0,0.0
3,Fujian,Mainland China,1/22/2020 17:00,1.0,0.0,0.0
4,Gansu,Mainland China,1/22/2020 17:00,0.0,0.0,0.0
...,...,...,...,...,...,...
71,Unknown,United Kingdom,1/22/2020 17:00,0.0,0.0,0.0
72,0,Nauru,1/22/2020 17:00,0.0,0.0,0.0
73,Niue,New Zealand,1/22/2020 17:00,0.0,0.0,0.0
74,0,Tuvalu,1/22/2020 17:00,0.0,0.0,0.0
75,Pitcairn Islands,United Kingdom,1/22/2020 17:00,0.0,0.0,0.0

In [25]:
doc.isnull().sum()

Province/State    12
Country/Region     0
Last Update        0
Confirmed         10
Deaths             0
Recovered          0
dtype: int64

In [28]:
doc.shape

(76, 6)

In [29]:
doc.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 76 entries, 0 to 75
Data columns (total 6 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Province/State  64 non-null     object
 1   Country/Region  76 non-null     object
 2   Last Update     76 non-null     object
 3   Confirmed       66 non-null     float64
 4   Deaths          39 non-null     float64
 5   Recovered       39 non-null     float64
dtypes: float64(3), object(3)
memory usage: 3.7+ KB

In [30]:
doc.describe()

        Confirmed     Deaths  Recovered
count   66.000000  39.000000  39.000000
mean     8.439394   0.435897   0.769231
std     54.585185   2.722179   4.486597
min      0.000000   0.000000   0.000000
25%      0.000000   0.000000   0.000000
50%      0.000000   0.000000   0.000000
75%      1.750000   0.000000   0.000000
max    444.000000  17.000000  28.000000

In [31]:
doc = pd.read_csv(f"{PATH}01-22-2020.csv", encoding = "utf-8-sig")

In [32]:
doc.isnull().sum()

Province/State    12
Country/Region     0
Last Update        0
Confirmed         10
Deaths            37
Recovered         37
dtype: int64

In [33]:
nan_data = {"Deaths" : 0 , "Recovered" : 0}
doc = doc.fillna(nan_data)
doc.isnull().sum()

Province/State    12
Country/Region     0
Last Update        0
Confirmed         10
Deaths             0
Recovered          0
dtype: int64