In [1]:
import pandas as pd

PATH = "csse_covid_19_data/csse_covid_19_daily_reports/"

doc = pd.read_csv(f"{PATH}04-01-2020.csv", encoding = "utf-8-sig")

In [2]:
doc

,FIPS,Admin2,Province_State,Country_Region,Last_Update,Lat,Long_,Confirmed,Deaths,Recovered,Active,Combined_Key
0,45001.0,Abbeville,South Carolina,US,2020-04-01 21:58:49,34.223334,-82.461707,4,0,0,4,"Abbeville, South Carolina, US"
1,22001.0,Acadia,Louisiana,US,2020-04-01 21:58:49,30.295065,-92.414197,47,1,0,46,"Acadia, Louisiana, US"
2,51001.0,Accomack,Virginia,US,2020-04-01 21:58:49,37.767072,-75.632346,7,0,0,7,"Accomack, Virginia, US"
3,16001.0,Ada,Idaho,US,2020-04-01 21:58:49,43.452658,-116.241552,195,3,0,192,"Ada, Idaho, US"
4,19001.0,Adair,Iowa,US,2020-04-01 21:58:49,41.330756,-94.471059,1,0,0,1,"Adair, Iowa, US"
...,...,...,...,...,...,...,...,...,...,...,...,...
2517,82604.0,NaN,Wales,United Kingdom,2020-04-01 21:58:49,52.130700,-3.783700,0,198,0,0,"Wales, United Kingdom"
2518,NaN,NaN,NaN,Nauru,2020-04-01 21:58:49,-0.522800,166.931500,0,0,0,0,Nauru
2519,NaN,NaN,Niue,New Zealand,2020-04-01 21:58:49,-19.054400,-169.867200,0,0,0,0,"Niue, New Zealand"
2520,NaN,NaN,NaN,Tuvalu,2020-04-01 21:58:49,-7.109500,177.649300,0,0,0,0,Tuvalu
2521,NaN,NaN,Pitcairn Islands,United Kingdom,2020-04-01 21:58:49,-24.376800,-128.324200,0,0,0,0,"Pitcairn Islands, United Kingdom"

In [3]:
doc = pd.read_csv(f"{PATH}03-01-2020.csv", encoding = "utf-8-sig")
doc.head()

,Province/State,Country/Region,Last Update,Confirmed,Deaths,Recovered,Latitude,Longitude
0,Hubei,Mainland China,2020-03-01T10:13:19,66907,2761,31536,30.9756,112.2707
1,NaN,South Korea,2020-03-01T23:43:03,3736,17,30,36.0000,128.0000
2,NaN,Italy,2020-03-01T23:23:02,1694,34,83,43.0000,12.0000
3,Guangdong,Mainland China,2020-03-01T14:13:18,1349,7,1016,23.3417,113.4244
4,Henan,Mainland China,2020-03-01T14:13:18,1272,22,1198,33.8820,113.6140

In [4]:
doc = pd.read_csv(f"{PATH}01-22-2020.csv", encoding = "utf-8-sig")
doc.head()

,Province/State,Country/Region,Last Update,Confirmed,Deaths,Recovered
0,Anhui,Mainland China,1/22/2020 17:00,1.0,NaN,NaN
1,Beijing,Mainland China,1/22/2020 17:00,14.0,NaN,NaN
2,Chongqing,Mainland China,1/22/2020 17:00,6.0,NaN,NaN
3,Fujian,Mainland China,1/22/2020 17:00,1.0,NaN,NaN
4,Gansu,Mainland China,1/22/2020 17:00,NaN,NaN,NaN

In [5]:
doc = pd.read_csv(f"{PATH}01-22-2020.csv", encoding = "utf-8-sig")

try : 
    doc = doc[["Province_State","Country_Region","Confirmed"]]
except : 
    doc = doc[["Province/State","Country/Region","Confirmed"]]
    doc.columns = ["Province_State","Country_Region","Confirmed"]

doc.head()

  Province_State  Country_Region  Confirmed
0          Anhui  Mainland China        1.0
1        Beijing  Mainland China       14.0
2      Chongqing  Mainland China        6.0
3         Fujian  Mainland China        1.0
4          Gansu  Mainland China        NaN

In [15]:
doc = pd.read_csv(f"{PATH}01-22-2020.csv", encoding = "utf-8-sig")

try : 
    doc = doc[["Province_State","Country_Region","Confirmed"]]
except : 
    doc = doc[["Province/State","Country/Region","Confirmed"]]
    doc.columns = ["Province_State","Country_Region","Confirmed"]

    
doc = doc.dropna(subset = ["Confirmed"])
doc = doc.astype({"Confirmed" : "int64"})

doc.head()

  Province_State  Country_Region  Confirmed
0          Anhui  Mainland China          1
1        Beijing  Mainland China         14
2      Chongqing  Mainland China          6
3         Fujian  Mainland China          1
5      Guangdong  Mainland China         26

In [7]:
doc.info()

<class 'pandas.core.frame.DataFrame'>
Index: 66 entries, 0 to 75
Data columns (total 3 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Province_State  54 non-null     object
 1   Country_Region  66 non-null     object
 2   Confirmed       66 non-null     int64
dtypes: int64(1), object(2)
memory usage: 2.1+ KB

In [8]:
country_info = pd.read_csv("./csse_covid_19_data/UID_ISO_FIPS_LookUp_Table.csv")

country_info.head()

,UID,iso2,iso3,code3,FIPS,Admin2,Province_State,Country_Region,Lat,Long_,Combined_Key,Population
0,4,AF,AFG,4.0,NaN,NaN,NaN,Afghanistan,33.93911,67.709953,Afghanistan,38928341.0
1,8,AL,ALB,8.0,NaN,NaN,NaN,Albania,41.15330,20.168300,Albania,2877800.0
2,10,AQ,ATA,10.0,NaN,NaN,NaN,Antarctica,-71.94990,23.347000,Antarctica,NaN
3,12,DZ,DZA,12.0,NaN,NaN,NaN,Algeria,28.03390,1.659600,Algeria,43851043.0
4,20,AD,AND,20.0,NaN,NaN,NaN,Andorra,42.50630,1.521800,Andorra,77265.0

In [9]:
doc = pd.read_csv(f"{PATH}04-01-2020.csv", encoding = "utf-8-sig")

In [10]:
import pandas as pd

test_df = pd.merge(doc, country_info, on = "Country_Region", how = "left")

In [11]:
test_df

,FIPS_x,Admin2_x,Province_State_x,Country_Region,Last_Update,Lat_x,Long__x,Confirmed,Deaths,Recovered,...,iso2,iso3,code3,FIPS_y,Admin2_y,Province_State_y,Lat_y,Long__y,Combined_Key_y,Population
0,45001.0,Abbeville,South Carolina,US,2020-04-01 21:58:49,34.223334,-82.461707,4,0,0,...,US,USA,840.0,NaN,NaN,NaN,40.000000,-100.000000,US,329466283.0
1,45001.0,Abbeville,South Carolina,US,2020-04-01 21:58:49,34.223334,-82.461707,4,0,0,...,AS,ASM,16.0,60.0,NaN,American Samoa,-14.271000,-170.132000,"American Samoa, US",55641.0
2,45001.0,Abbeville,South Carolina,US,2020-04-01 21:58:49,34.223334,-82.461707,4,0,0,...,GU,GUM,316.0,66.0,NaN,Guam,13.444300,144.793700,"Guam, US",164229.0
3,45001.0,Abbeville,South Carolina,US,2020-04-01 21:58:49,34.223334,-82.461707,4,0,0,...,MP,MNP,580.0,69.0,NaN,Northern Mariana Islands,15.097900,145.673900,"Northern Mariana Islands, US",55144.0
4,45001.0,Abbeville,South Carolina,US,2020-04-01 21:58:49,34.223334,-82.461707,4,0,0,...,VI,VIR,850.0,78.0,NaN,Virgin Islands,18.335800,-64.896300,"Virgin Islands, US",107268.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7591770,NaN,NaN,Pitcairn Islands,United Kingdom,2020-04-01 21:58:49,-24.376800,-128.324200,0,0,0,...,MS,MSR,500.0,NaN,NaN,Montserrat,16.742498,-62.187366,"Montserrat, United Kingdom",4999.0
7591771,NaN,NaN,Pitcairn Islands,United Kingdom,2020-04-01 21:58:49,-24.376800,-128.324200,0,0,0,...,TC,TCA,796.0,NaN,NaN,Turks and Caicos Islands,21.694000,-71.797900,"Turks and Caicos Islands, United Kingdom",38718.0
7591772,NaN,NaN,Pitcairn Islands,United Kingdom,2020-04-01 21:58:49,-24.376800,-128.324200,0,0,0,...,PN,PCN,612.0,NaN,NaN,Pitcairn Islands,-24.376800,-128.324200,"Pitcairn Islands, United Kingdom",67.0
7591773,NaN,NaN,Pitcairn Islands,United Kingdom,2020-04-01 21:58:49,-24.376800,-128.324200,0,0,0,...,AI,AIA,660.0,NaN,NaN,Anguilla,18.220600,-63.068600,"Anguilla, United Kingdom",15002.0
7591774,NaN,NaN,Pitcairn Islands,United Kingdom,2020-04-01 21:58:49,-24.376800,-128.324200,0,0,0,...,SH,SHN,654.0,NaN,NaN,"Saint Helena, Ascension and Tristan da Cunha",-7.946700,-14.355900,"Saint Helena, Ascension and Tristan da Cunha, ...",5661.0

In [13]:
test_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7591775 entries, 0 to 7591774
Data columns (total 23 columns):
 #   Column            Dtype
---  ------            -----
 0   FIPS_x            float64
 1   Admin2_x          object
 2   Province_State_x  object
 3   Country_Region    object
 4   Last_Update       object
 5   Lat_x             float64
 6   Long__x           float64
 7   Confirmed         int64
 8   Deaths            int64
 9   Recovered         int64
 10  Active            int64
 11  Combined_Key_x    object
 12  UID               int64
 13  iso2              object
 14  iso3              object
 15  code3             float64
 16  FIPS_y            float64
 17  Admin2_y          object
 18  Province_State_y  object
 19  Lat_y             float64
 20  Long__y           float64
 21  Combined_Key_y    object
 22  Population        float64
dtypes: float64(8), int64(5), object(10)
memory usage: 1.3+ GB

In [14]:
test_df.isnull().sum()

FIPS_x              197269
Admin2_x             27049
Province_State_x       804
Country_Region           0
Last_Update              0
Lat_x                 3488
Long__x               3488
Confirmed                0
Deaths                   0
Recovered                0
Active                   0
Combined_Key_x           0
UID                      0
iso2                     5
iso3                     4
code3                    4
FIPS_y               52223
Admin2_y            143571
Province_State_y      2522
Lat_y               265276
Long__y             265276
Combined_Key_y           0
Population          265279
dtype: int64

In [16]:
doc = pd.read_csv(f"{PATH}01-22-2020.csv", encoding = "utf-8-sig")

try : 
    doc = doc[["Province_State","Country_Region","Confirmed"]]
except : 
    doc = doc[["Province/State","Country/Region","Confirmed"]]
    doc.columns = ["Province_State","Country_Region","Confirmed"]

    
doc = doc.dropna(subset = ["Confirmed"])
doc = doc.astype({"Confirmed" : "int64"})

doc.head()

  Province_State  Country_Region  Confirmed
0          Anhui  Mainland China          1
1        Beijing  Mainland China         14
2      Chongqing  Mainland China          6
3         Fujian  Mainland China          1
5      Guangdong  Mainland China         26

In [18]:
test_df = pd.merge(doc, country_info, on = "Country_Region", how = "left")

In [19]:
test_df.head()

,Province_State_x,Country_Region,Confirmed,UID,iso2,iso3,code3,FIPS,Admin2,Province_State_y,Lat,Long_,Combined_Key,Population
0,Anhui,Mainland China,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Beijing,Mainland China,14,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Chongqing,Mainland China,6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Fujian,Mainland China,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Guangdong,Mainland China,26,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [20]:
test_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3993 entries, 0 to 3992
Data columns (total 14 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Province_State_x  3932 non-null   object
 1   Country_Region    3993 non-null   object
 2   Confirmed         3993 non-null   int64
 3   UID               3967 non-null   float64
 4   iso2              3965 non-null   object
 5   iso3              3965 non-null   object
 6   code3             3965 non-null   float64
 7   FIPS              3384 non-null   float64
 8   Admin2            3343 non-null   object
 9   Province_State_y  3927 non-null   object
 10  Lat               3820 non-null   float64
 11  Long_             3820 non-null   float64
 12  Combined_Key      3967 non-null   object
 13  Population        3817 non-null   float64
dtypes: float64(6), int64(1), object(7)
memory usage: 436.9+ KB

In [22]:
test_df[test_df["iso2"].isnull()]

,Province_State_x,Country_Region,Confirmed,UID,iso2,iso3,code3,FIPS,Admin2,Province_State_y,Lat,Long_,Combined_Key,Population
0,Anhui,Mainland China,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Beijing,Mainland China,14,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Chongqing,Mainland China,6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Fujian,Mainland China,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Guangdong,Mainland China,26,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,Guangxi,Mainland China,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,Guizhou,Mainland China,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,Hainan,Mainland China,4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,Hebei,Mainland China,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,Henan,Mainland China,5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,Hubei,Mainland China,444,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,Hunan,Mainland China,4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12,Jiangsu,Mainland China,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13,Jiangxi,Mainland China,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14,Liaoning,Mainland China,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15,Macau,Macau,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16,Ningxia,Mainland China,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17,Shandong,Mainland China,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
18,Shanghai,Mainland China,9,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19,Shanxi,Mainland China,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20,Sichuan,Mainland China,5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
21,Taiwan,Taiwan,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
22,Tianjin,Mainland China,4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3429,Yunnan,Mainland China,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3430,Zhejiang,Mainland China,10,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3482,NaN,South Korea,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3488,NaN,Summer Olympics 2020,0,2020.0,NaN,NaN,NaN,NaN,NaN,NaN,35.6491,139.7737,Summer Olympics 2020,NaN
3796,NaN,Winter Olympics 2022,0,2022.0,NaN,NaN,NaN,NaN,NaN,NaN,39.9042,116.4074,Winter Olympics 2022,NaN

In [24]:
nan_rows = test_df[test_df["iso2"].isnull()]
nan_rows

,Province_State_x,Country_Region,Confirmed,UID,iso2,iso3,code3,FIPS,Admin2,Province_State_y,Lat,Long_,Combined_Key,Population
0,Anhui,Mainland China,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Beijing,Mainland China,14,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Chongqing,Mainland China,6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Fujian,Mainland China,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Guangdong,Mainland China,26,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,Guangxi,Mainland China,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,Guizhou,Mainland China,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,Hainan,Mainland China,4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,Hebei,Mainland China,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,Henan,Mainland China,5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,Hubei,Mainland China,444,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,Hunan,Mainland China,4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12,Jiangsu,Mainland China,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13,Jiangxi,Mainland China,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14,Liaoning,Mainland China,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15,Macau,Macau,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16,Ningxia,Mainland China,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17,Shandong,Mainland China,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
18,Shanghai,Mainland China,9,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19,Shanxi,Mainland China,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20,Sichuan,Mainland China,5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
21,Taiwan,Taiwan,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
22,Tianjin,Mainland China,4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3429,Yunnan,Mainland China,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3430,Zhejiang,Mainland China,10,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3482,NaN,South Korea,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3488,NaN,Summer Olympics 2020,0,2020.0,NaN,NaN,NaN,NaN,NaN,NaN,35.6491,139.7737,Summer Olympics 2020,NaN
3796,NaN,Winter Olympics 2022,0,2022.0,NaN,NaN,NaN,NaN,NaN,NaN,39.9042,116.4074,Winter Olympics 2022,NaN

In [25]:
import json

with open("./csse_covid_19_data/country_convert.json", "r", encoding = "utf-8-sig") as json_file :
    json_data = json.load(json_file)

In [26]:
print(json_data)

{'Mainland China': 'China', 'Macau': 'China', 'South Korea': 'Korea, South', 'Aruba': 'Netherlands', ' Azerbaijan': 'Azerbaijan', 'Bahamas, The': 'Bahamas', 'Cape Verde': 'Cabo Verde', 'Cayman Islands': 'United Kingdom', 'Channel Islands': 'United Kingdom', 'Curacao': 'Netherlands', 'Czech Republic': 'Czechia', 'East Timor': 'Timor-Leste', 'Faroe Islands': 'Denmark', 'French Guiana': 'France', 'Gambia, The': 'Gambia', 'Gibraltar': 'United Kingdom', 'Greenland': 'Denmark', 'Guadeloupe': 'France', 'Guam': 'US', 'Guernsey': 'US', 'Hong Kong': 'China', 'Hong Kong SAR': 'China', 'Iran (Islamic Republic of)': 'Iran', 'Ivory Coast': "Cote d'Ivoire", 'Jersey': 'US', 'Macao SAR': 'China', 'Martinique': 'France', 'Mayotte': 'France', 'North Ireland': 'United Kingdom', 'Palestine': 'West Bank and Gaza', 'Puerto Rico': 'US', 'Republic of Ireland': 'Ireland', 'Republic of Korea': 'Korea, South', 'Republic of Moldova': 'Moldova', 'Republic of the Congo': 'Congo (Brazzaville)', 'Reunion': 'France', 'Russian Federation': 'Russia', 'Saint Barthelemy': 'France', 'Saint Martin': 'France', 'St. Martin': 'US', 'Taipei and environs': 'Taiwan', 'The Bahamas': 'Bahamas', 'The Gambia': 'Gambia', 'UK': 'United Kingdom', 'Vatican City': 'Holy See', 'Viet Nam': 'Vietnam', 'occupied Palestinian territory': 'West Bank and Gaza', 'Taiwan*': 'Taiwan', 'Malawi': 'France', 'South Sudan': 'Sudan', 'Western Sahara': 'Morocco', 'Namibia': 'Namibia'}

In [27]:
print(json_data.keys())

dict_keys(['Mainland China', 'Macau', 'South Korea', 'Aruba', ' Azerbaijan', 'Bahamas, The', 'Cape Verde', 'Cayman Islands', 'Channel Islands', 'Curacao', 'Czech Republic', 'East Timor', 'Faroe Islands', 'French Guiana', 'Gambia, The', 'Gibraltar', 'Greenland', 'Guadeloupe', 'Guam', 'Guernsey', 'Hong Kong', 'Hong Kong SAR', 'Iran (Islamic Republic of)', 'Ivory Coast', 'Jersey', 'Macao SAR', 'Martinique', 'Mayotte', 'North Ireland', 'Palestine', 'Puerto Rico', 'Republic of Ireland', 'Republic of Korea', 'Republic of Moldova', 'Republic of the Congo', 'Reunion', 'Russian Federation', 'Saint Barthelemy', 'Saint Martin', 'St. Martin', 'Taipei and environs', 'The Bahamas', 'The Gambia', 'UK', 'Vatican City', 'Viet Nam', 'occupied Palestinian territory', 'Taiwan*', 'Malawi', 'South Sudan', 'Western Sahara', 'Namibia'])

In [28]:
# apply() : 특정 컬럼 내 각 행을 순회하면서 어떤 결과값을 적용하고자 할 때 사용!

df = pd.DataFrame({
    "영어" : [60, 70],
    "수학" : [100, 50]
}, index = ["Dave", "David"])

df

       영어   수학
Dave   60  100
David  70   50

In [31]:
def func(df_data) :
    print(type(df_data))
    print(df_data.index)
    print(df_data.values)
    return df_data

In [32]:
df_func = df.apply(func, axis = 0)

<class 'pandas.core.series.Series'>
Index(['Dave', 'David'], dtype='object')
[60 70]
<class 'pandas.core.series.Series'>
Index(['Dave', 'David'], dtype='object')
[100  50]

In [33]:
df_func = df.apply(func, axis = 1)

<class 'pandas.core.series.Series'>
Index(['영어', '수학'], dtype='object')
[ 60 100]
<class 'pandas.core.series.Series'>
Index(['영어', '수학'], dtype='object')
[70 50]

In [34]:
def func(row) :
    if row["Country_Region"] in json_data :
        row["Country_Region"] = json_data[row["Country_Region"]]
    return row

In [36]:
doc = doc.apply(func, axis = 1)
doc.head()

  Province_State Country_Region  Confirmed
0          Anhui          China          1
1        Beijing          China         14
2      Chongqing          China          6
3         Fujian          China          1
5      Guangdong          China         26

In [37]:
data = "01-22-2020.csv"
date_column = data.split(".")[0]
date_column # 1/22/2020  이 형식으로 바꾸고 싶음

'01-22-2020'

In [39]:
data = "01-22-2020.csv"
date_column = data.split(".")[0].lstrip("0").replace("-", "/")
date_column

'1/22/2020'

In [42]:
doc.columns = ['Province_State', 'Country_Region', date_column]
doc.columns

Index(['Province_State', 'Country_Region', '1/22/2020'], dtype='object')

In [43]:
doc

      Province_State  Country_Region  1/22/2020
0              Anhui           China          1
1            Beijing           China         14
2          Chongqing           China          6
3             Fujian           China          1
5          Guangdong           China         26
..               ...             ...        ...
71           Unknown  United Kingdom          0
72               NaN           Nauru          0
73              Niue     New Zealand          0
74               NaN          Tuvalu          0
75  Pitcairn Islands  United Kingdom          0

[66 rows x 3 columns]

In [ ]:
# 1) 원하는 컬럼만 추출 : 해당 원하는 컬럼명이 시기에 따라서 달랐기 때문에, try/except  + if 구문을 활용했다.
# 2) 각 국가마다 확진자 수를 통합 + 각 국가별 공식 명칭에 따라 국기를 찾아올 수 있기 때문에 이름을 통일해야 했다.=> apply() 메서드 활용
# 3) 날짜별 확진자 컬럼 이름을 변경해야 했기 때문에, split을 통해 불필요한 문자열을 편집했다.
# 4) 중복 데이터 병합 : groupby

In [44]:
df = pd.DataFrame({
    "성별" : ["남", "남", "남"],
    "이름" : ["David", "Dave", "Dave"],
    "수학" : [100, 50, 50],
    "국어" : [80, 70, 50]
})

df

  성별     이름   수학  국어
0  남  David  100  80
1  남   Dave   50  70
2  남   Dave   50  50

In [45]:
df.groupby("이름").sum()

       성별   수학   국어
이름
Dave   남남  100  120
David   남  100   80

In [46]:
selected_columns = ["이름", "수학", "국어"]
df = df[selected_columns]

df.groupby("이름").sum() # groupby 기준값은 인덱스로 빠진다.

        수학   국어
이름
Dave   100  120
David  100   80

In [49]:
import pandas as pd
import json

PATH = "csse_covid_19_data/csse_covid_19_daily_reports/"

with open("./csse_covid_19_data/country_convert.json", "r", encoding = "utf-8-sig") as json_file :
    json_data = json.load(json_file)

def country_name_convert(row) :
    if row["Country_Region"] in json_data :
        row["Country_Region"] = json_data[row["Country_Region"]]
    return row["Country_Region"]

def create_dateframe(filename) :
    doc = pd.read_csv(f"{PATH}{filename}", encoding = "utf-8-sig")

    try : 
        doc = doc[["Country_Region","Confirmed"]]
    except : 
        doc = doc[["Country/Region","Confirmed"]]
        doc.columns = ["Country_Region","Confirmed"]

    
    doc = doc.dropna(subset = ["Confirmed"])
    doc["Country_Region"] = doc.apply(country_name_convert, axis = 1)
    doc = doc.astype({"Confirmed" : "int64"})
    doc = doc.groupby("Country_Region").sum()

    date_column = filename.split(".")[0].lstrip("0").replace("-", "/")
    doc.columns = [date_column]

    return doc

In [50]:
doc1 = create_dateframe("01-22-2020.csv")
doc2 = create_dateframe("04-01-2020.csv")

In [51]:
doc1.head()

                1/22/2020
Country_Region
Antarctica              0
China                 548
Japan                   2
Kiribati                0
Korea, North            0

In [52]:
doc2.head()

                4/01/2020
Country_Region
Afghanistan           192
Albania               259
Algeria               847
Andorra               390
Angola                  8

In [53]:
doc1.info()

<class 'pandas.core.frame.DataFrame'>
Index: 19 entries, Antarctica to Winter Olympics 2022
Data columns (total 1 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   1/22/2020  19 non-null     int64
dtypes: int64(1)
memory usage: 304.0+ bytes

In [54]:
doc2.info()

<class 'pandas.core.frame.DataFrame'>
Index: 190 entries, Afghanistan to Zimbabwe
Data columns (total 1 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   4/01/2020  190 non-null    int64
dtypes: int64(1)
memory usage: 3.0+ KB

In [57]:
import pandas as pd

doc = pd.merge(doc1, doc2, how = "outer", left_index = True, right_index = True)
doc.head()

                1/22/2020  4/01/2020
Country_Region
Afghanistan           NaN        192
Albania               NaN        259
Algeria               NaN        847
Andorra               NaN        390
Angola                NaN          8

In [58]:
doc = doc.fillna(0)
doc

                      1/22/2020  4/01/2020
Country_Region
Afghanistan                 0.0        192
Albania                     0.0        259
Algeria                     0.0        847
Andorra                     0.0        390
Angola                      0.0          8
...                         ...        ...
Vietnam                     0.0        218
West Bank and Gaza          0.0        134
Winter Olympics 2022        0.0          0
Zambia                      0.0         36
Zimbabwe                    0.0          8

[190 rows x 2 columns]

In [59]:
# 다양한 프로그래밍 언어 : 로컬 시스템 관련한 속성 및 메서드를 사용 -> OS

import os

PATH = "csse_covid_19_data/csse_covid_19_daily_reports/"
file_list = os.listdir(PATH)

file_list

['.gitignore',
 '01-01-2021.csv',
 '01-01-2022.csv',
 '01-01-2023.csv',
 '01-02-2021.csv',
 '01-02-2022.csv',
 '01-02-2023.csv',
 '01-03-2021.csv',
 '01-03-2022.csv',
 '01-03-2023.csv',
 '01-04-2021.csv',
 '01-04-2022.csv',
 '01-04-2023.csv',
 '01-05-2021.csv',
 '01-05-2022.csv',
 '01-05-2023.csv',
 '01-06-2021.csv',
 '01-06-2022.csv',
 '01-06-2023.csv',
 '01-07-2021.csv',
 '01-07-2022.csv',
 '01-07-2023.csv',
 '01-08-2021.csv',
 '01-08-2022.csv',
 '01-08-2023.csv',
 '01-09-2021.csv',
 '01-09-2022.csv',
 '01-09-2023.csv',
 '01-10-2021.csv',
 '01-10-2022.csv',
 '01-10-2023.csv',
 '01-11-2021.csv',
 '01-11-2022.csv',
 '01-11-2023.csv',
 '01-12-2021.csv',
 '01-12-2022.csv',
 '01-12-2023.csv',
 '01-13-2021.csv',
 '01-13-2022.csv',
 '01-13-2023.csv',
 '01-14-2021.csv',
 '01-14-2022.csv',
 '01-14-2023.csv',
 '01-15-2021.csv',
 '01-15-2022.csv',
 '01-15-2023.csv',
 '01-16-2021.csv',
 '01-16-2022.csv',
 '01-16-2023.csv',
 '01-17-2021.csv',
 '01-17-2022.csv',
 '01-17-2023.csv',
 '01-18-2021.csv',
 '01-18-2022.csv',
 '01-18-2023.csv',
 '01-19-2021.csv',
 '01-19-2022.csv',
 '01-19-2023.csv',
 '01-20-2021.csv',
 '01-20-2022.csv',
 '01-20-2023.csv',
 '01-21-2021.csv',
 '01-21-2022.csv',
 '01-21-2023.csv',
 '01-22-2020.csv',
 '01-22-2021.csv',
 '01-22-2022.csv',
 '01-22-2023.csv',
 '01-23-2020.csv',
 '01-23-2021.csv',
 '01-23-2022.csv',
 '01-23-2023.csv',
 '01-24-2020.csv',
 '01-24-2021.csv',
 '01-24-2022.csv',
 '01-24-2023.csv',
 '01-25-2020.csv',
 '01-25-2021.csv',
 '01-25-2022.csv',
 '01-25-2023.csv',
 '01-26-2020.csv',
 '01-26-2021.csv',
 '01-26-2022.csv',
 '01-26-2023.csv',
 '01-27-2020.csv',
 '01-27-2021.csv',
 '01-27-2022.csv',
 '01-27-2023.csv',
 '01-28-2020.csv',
 '01-28-2021.csv',
 '01-28-2022.csv',
 '01-28-2023.csv',
 '01-29-2020.csv',
 '01-29-2021.csv',
 '01-29-2022.csv',
 '01-29-2023.csv',
 '01-30-2020.csv',
 '01-30-2021.csv',
 '01-30-2022.csv',
 '01-30-2023.csv',
 '01-31-2020.csv',
 '01-31-2021.csv',
 '01-31-2022.csv',
 '01-31-2023.csv',
 '02-01-2020.csv',
 '02-01-2021.csv',
 '02-01-2022.csv',
 '02-01-2023.csv',
 '02-02-2020.csv',
 '02-02-2021.csv',
 '02-02-2022.csv',
 '02-02-2023.csv',
 '02-03-2020.csv',
 '02-03-2021.csv',
 '02-03-2022.csv',
 '02-03-2023.csv',
 '02-04-2020.csv',
 '02-04-2021.csv',
 '02-04-2022.csv',
 '02-04-2023.csv',
 '02-05-2020.csv',
 '02-05-2021.csv',
 '02-05-2022.csv',
 '02-05-2023.csv',
 '02-06-2020.csv',
 '02-06-2021.csv',
 '02-06-2022.csv',
 '02-06-2023.csv',
 '02-07-2020.csv',
 '02-07-2021.csv',
 '02-07-2022.csv',
 '02-07-2023.csv',
 '02-08-2020.csv',
 '02-08-2021.csv',
 '02-08-2022.csv',
 '02-08-2023.csv',
 '02-09-2020.csv',
 '02-09-2021.csv',
 '02-09-2022.csv',
 '02-09-2023.csv',
 '02-10-2020.csv',
 '02-10-2021.csv',
 '02-10-2022.csv',
 '02-10-2023.csv',
 '02-11-2020.csv',
 '02-11-2021.csv',
 '02-11-2022.csv',
 '02-11-2023.csv',
 '02-12-2020.csv',
 '02-12-2021.csv',
 '02-12-2022.csv',
 '02-12-2023.csv',
 '02-13-2020.csv',
 '02-13-2021.csv',
 '02-13-2022.csv',
 '02-13-2023.csv',
 '02-14-2020.csv',
 '02-14-2021.csv',
 '02-14-2022.csv',
 '02-14-2023.csv',
 '02-15-2020.csv',
 '02-15-2021.csv',
 '02-15-2022.csv',
 '02-15-2023.csv',
 '02-16-2020.csv',
 '02-16-2021.csv',
 '02-16-2022.csv',
 '02-16-2023.csv',
 '02-17-2020.csv',
 '02-17-2021.csv',
 '02-17-2022.csv',
 '02-17-2023.csv',
 '02-18-2020.csv',
 '02-18-2021.csv',
 '02-18-2022.csv',
 '02-18-2023.csv',
 '02-19-2020.csv',
 '02-19-2021.csv',
 '02-19-2022.csv',
 '02-19-2023.csv',
 '02-20-2020.csv',
 '02-20-2021.csv',
 '02-20-2022.csv',
 '02-20-2023.csv',
 '02-21-2020.csv',
 '02-21-2021.csv',
 '02-21-2022.csv',
 '02-21-2023.csv',
 '02-22-2020.csv',
 '02-22-2021.csv',
 '02-22-2022.csv',
 '02-22-2023.csv',
 '02-23-2020.csv',
 '02-23-2021.csv',
 '02-23-2022.csv',
 '02-23-2023.csv',
 '02-24-2020.csv',
 '02-24-2021.csv',
 '02-24-2022.csv',
 '02-24-2023.csv',
 '02-25-2020.csv',
 '02-25-2021.csv',
 '02-25-2022.csv',
 '02-25-2023.csv',
 '02-26-2020.csv',
 '02-26-2021.csv',
 '02-26-2022.csv',
 '02-26-2023.csv',
 '02-27-2020.csv',
 '02-27-2021.csv',
 '02-27-2022.csv',
 '02-27-2023.csv',
 '02-28-2020.csv',
 '02-28-2021.csv',
 '02-28-2022.csv',
 '02-28-2023.csv',
 '02-29-2020.csv',
 '03-01-2020.csv',
 '03-01-2021.csv',
 '03-01-2022.csv',
 '03-01-2023.csv',
 '03-02-2020.csv',
 '03-02-2021.csv',
 '03-02-2022.csv',
 '03-02-2023.csv',
 '03-03-2020.csv',
 '03-03-2021.csv',
 '03-03-2022.csv',
 '03-03-2023.csv',
 '03-04-2020.csv',
 '03-04-2021.csv',
 '03-04-2022.csv',
 '03-04-2023.csv',
 '03-05-2020.csv',
 '03-05-2021.csv',
 '03-05-2022.csv',
 '03-05-2023.csv',
 '03-06-2020.csv',
 '03-06-2021.csv',
 '03-06-2022.csv',
 '03-06-2023.csv',
 '03-07-2020.csv',
 '03-07-2021.csv',
 '03-07-2022.csv',
 '03-07-2023.csv',
 '03-08-2020.csv',
 '03-08-2021.csv',
 '03-08-2022.csv',
 '03-08-2023.csv',
 '03-09-2020.csv',
 '03-09-2021.csv',
 '03-09-2022.csv',
 '03-09-2023.csv',
 '03-10-2020.csv',
 '03-10-2021.csv',
 '03-10-2022.csv',
 '03-11-2020.csv',
 '03-11-2021.csv',
 '03-11-2022.csv',
 '03-12-2020.csv',
 '03-12-2021.csv',
 '03-12-2022.csv',
 '03-13-2020.csv',
 '03-13-2021.csv',
 '03-13-2022.csv',
 '03-14-2020.csv',
 '03-14-2021.csv',
 '03-14-2022.csv',
 '03-15-2020.csv',
 '03-15-2021.csv',
 '03-15-2022.csv',
 '03-16-2020.csv',
 '03-16-2021.csv',
 '03-16-2022.csv',
 '03-17-2020.csv',
 '03-17-2021.csv',
 '03-17-2022.csv',
 '03-18-2020.csv',
 '03-18-2021.csv',
 '03-18-2022.csv',
 '03-19-2020.csv',
 '03-19-2021.csv',
 '03-19-2022.csv',
 '03-20-2020.csv',
 '03-20-2021.csv',
 '03-20-2022.csv',
 '03-21-2020.csv',
 '03-21-2021.csv',
 '03-21-2022.csv',
 '03-22-2020.csv',
 '03-22-2021.csv',
 '03-22-2022.csv',
 '03-23-2020.csv',
 '03-23-2021.csv',
 '03-23-2022.csv',
 '03-24-2020.csv',
 '03-24-2021.csv',
 '03-24-2022.csv',
 '03-25-2020.csv',
 '03-25-2021.csv',
 '03-25-2022.csv',
 '03-26-2020.csv',
 '03-26-2021.csv',
 '03-26-2022.csv',
 '03-27-2020.csv',
 '03-27-2021.csv',
 '03-27-2022.csv',
 '03-28-2020.csv',
 '03-28-2021.csv',
 '03-28-2022.csv',
 '03-29-2020.csv',
 '03-29-2021.csv',
 '03-29-2022.csv',
 '03-30-2020.csv',
 '03-30-2021.csv',
 '03-30-2022.csv',
 '03-31-2020.csv',
 '03-31-2021.csv',
 '03-31-2022.csv',
 '04-01-2020.csv',
 '04-01-2021.csv',
 '04-01-2022.csv',
 '04-02-2020.csv',
 '04-02-2021.csv',
 '04-02-2022.csv',
 '04-03-2020.csv',
 '04-03-2021.csv',
 '04-03-2022.csv',
 '04-04-2020.csv',
 '04-04-2021.csv',
 '04-04-2022.csv',
 '04-05-2020.csv',
 '04-05-2021.csv',
 '04-05-2022.csv',
 '04-06-2020.csv',
 '04-06-2021.csv',
 '04-06-2022.csv',
 '04-07-2020.csv',
 '04-07-2021.csv',
 '04-07-2022.csv',
 '04-08-2020.csv',
 '04-08-2021.csv',
 '04-08-2022.csv',
 '04-09-2020.csv',
 '04-09-2021.csv',
 '04-09-2022.csv',
 '04-10-2020.csv',
 '04-10-2021.csv',
 '04-10-2022.csv',
 '04-11-2020.csv',
 '04-11-2021.csv',
 '04-11-2022.csv',
 '04-12-2020.csv',
 '04-12-2021.csv',
 '04-12-2022.csv',
 '04-13-2020.csv',
 '04-13-2021.csv',
 '04-13-2022.csv',
 '04-14-2020.csv',
 '04-14-2021.csv',
 '04-14-2022.csv',
 '04-15-2020.csv',
 '04-15-2021.csv',
 '04-15-2022.csv',
 '04-16-2020.csv',
 '04-16-2021.csv',
 '04-16-2022.csv',
 '04-17-2020.csv',
 '04-17-2021.csv',
 '04-17-2022.csv',
 '04-18-2020.csv',
 '04-18-2021.csv',
 '04-18-2022.csv',
 '04-19-2020.csv',
 '04-19-2021.csv',
 '04-19-2022.csv',
 '04-20-2020.csv',
 '04-20-2021.csv',
 '04-20-2022.csv',
 '04-21-2020.csv',
 '04-21-2021.csv',
 '04-21-2022.csv',
 '04-22-2020.csv',
 '04-22-2021.csv',
 '04-22-2022.csv',
 '04-23-2020.csv',
 '04-23-2021.csv',
 '04-23-2022.csv',
 '04-24-2020.csv',
 '04-24-2021.csv',
 '04-24-2022.csv',
 '04-25-2020.csv',
 '04-25-2021.csv',
 '04-25-2022.csv',
 '04-26-2020.csv',
 '04-26-2021.csv',
 '04-26-2022.csv',
 '04-27-2020.csv',
 '04-27-2021.csv',
 '04-27-2022.csv',
 '04-28-2020.csv',
 '04-28-2021.csv',
 '04-28-2022.csv',
 '04-29-2020.csv',
 '04-29-2021.csv',
 '04-29-2022.csv',
 '04-30-2020.csv',
 '04-30-2021.csv',
 '04-30-2022.csv',
 '05-01-2020.csv',
 '05-01-2021.csv',
 '05-01-2022.csv',
 '05-02-2020.csv',
 '05-02-2021.csv',
 '05-02-2022.csv',
 '05-03-2020.csv',
 '05-03-2021.csv',
 '05-03-2022.csv',
 '05-04-2020.csv',
 '05-04-2021.csv',
 '05-04-2022.csv',
 '05-05-2020.csv',
 '05-05-2021.csv',
 '05-05-2022.csv',
 '05-06-2020.csv',
 '05-06-2021.csv',
 '05-06-2022.csv',
 '05-07-2020.csv',
 '05-07-2021.csv',
 '05-07-2022.csv',
 '05-08-2020.csv',
 '05-08-2021.csv',
 '05-08-2022.csv',
 '05-09-2020.csv',
 '05-09-2021.csv',
 '05-09-2022.csv',
 '05-10-2020.csv',
 '05-10-2021.csv',
 '05-10-2022.csv',
 '05-11-2020.csv',
 '05-11-2021.csv',
 '05-11-2022.csv',
 '05-12-2020.csv',
 '05-12-2021.csv',
 '05-12-2022.csv',
 '05-13-2020.csv',
 '05-13-2021.csv',
 '05-13-2022.csv',
 '05-14-2020.csv',
 '05-14-2021.csv',
 '05-14-2022.csv',
 '05-15-2020.csv',
 '05-15-2021.csv',
 '05-15-2022.csv',
 '05-16-2020.csv',
 '05-16-2021.csv',
 '05-16-2022.csv',
 '05-17-2020.csv',
 '05-17-2021.csv',
 '05-17-2022.csv',
 '05-18-2020.csv',
 '05-18-2021.csv',
 '05-18-2022.csv',
 '05-19-2020.csv',
 '05-19-2021.csv',
 '05-19-2022.csv',
 '05-20-2020.csv',
 '05-20-2021.csv',
 '05-20-2022.csv',
 '05-21-2020.csv',
 '05-21-2021.csv',
 '05-21-2022.csv',
 '05-22-2020.csv',
 '05-22-2021.csv',
 '05-22-2022.csv',
 '05-23-2020.csv',
 '05-23-2021.csv',
 '05-23-2022.csv',
 '05-24-2020.csv',
 '05-24-2021.csv',
 '05-24-2022.csv',
 '05-25-2020.csv',
 '05-25-2021.csv',
 '05-25-2022.csv',
 '05-26-2020.csv',
 '05-26-2021.csv',
 '05-26-2022.csv',
 '05-27-2020.csv',
 '05-27-2021.csv',
 '05-27-2022.csv',
 '05-28-2020.csv',
 '05-28-2021.csv',
 '05-28-2022.csv',
 '05-29-2020.csv',
 '05-29-2021.csv',
 '05-29-2022.csv',
 '05-30-2020.csv',
 '05-30-2021.csv',
 '05-30-2022.csv',
 '05-31-2020.csv',
 '05-31-2021.csv',
 '05-31-2022.csv',
 '06-01-2020.csv',
 '06-01-2021.csv',
 '06-01-2022.csv',
 '06-02-2020.csv',
 '06-02-2021.csv',
 '06-02-2022.csv',
 '06-03-2020.csv',
 '06-03-2021.csv',
 '06-03-2022.csv',
 '06-04-2020.csv',
 '06-04-2021.csv',
 '06-04-2022.csv',
 '06-05-2020.csv',
 '06-05-2021.csv',
 '06-05-2022.csv',
 '06-06-2020.csv',
 '06-06-2021.csv',
 '06-06-2022.csv',
 '06-07-2020.csv',
 '06-07-2021.csv',
 '06-07-2022.csv',
 '06-08-2020.csv',
 '06-08-2021.csv',
 '06-08-2022.csv',
 '06-09-2020.csv',
 '06-09-2021.csv',
 '06-09-2022.csv',
 '06-10-2020.csv',
 '06-10-2021.csv',
 '06-10-2022.csv',
 '06-11-2020.csv',
 '06-11-2021.csv',
 '06-11-2022.csv',
 '06-12-2020.csv',
 '06-12-2021.csv',
 '06-12-2022.csv',
 '06-13-2020.csv',
 '06-13-2021.csv',
 '06-13-2022.csv',
 '06-14-2020.csv',
 '06-14-2021.csv',
 '06-14-2022.csv',
 '06-15-2020.csv',
 '06-15-2021.csv',
 '06-15-2022.csv',
 '06-16-2020.csv',
 '06-16-2021.csv',
 '06-16-2022.csv',
 '06-17-2020.csv',
 '06-17-2021.csv',
 '06-17-2022.csv',
 '06-18-2020.csv',
 '06-18-2021.csv',
 '06-18-2022.csv',
 '06-19-2020.csv',
 '06-19-2021.csv',
 '06-19-2022.csv',
 '06-20-2020.csv',
 '06-20-2021.csv',
 '06-20-2022.csv',
 '06-21-2020.csv',
 '06-21-2021.csv',
 '06-21-2022.csv',
 '06-22-2020.csv',
 '06-22-2021.csv',
 '06-22-2022.csv',
 '06-23-2020.csv',
 '06-23-2021.csv',
 '06-23-2022.csv',
 '06-24-2020.csv',
 '06-24-2021.csv',
 '06-24-2022.csv',
 '06-25-2020.csv',
 '06-25-2021.csv',
 '06-25-2022.csv',
 '06-26-2020.csv',
 '06-26-2021.csv',
 '06-26-2022.csv',
 '06-27-2020.csv',
 '06-27-2021.csv',
 '06-27-2022.csv',
 '06-28-2020.csv',
 '06-28-2021.csv',
 '06-28-2022.csv',
 '06-29-2020.csv',
 '06-29-2021.csv',
 '06-29-2022.csv',
 '06-30-2020.csv',
 '06-30-2021.csv',
 '06-30-2022.csv',
 '07-01-2020.csv',
 '07-01-2021.csv',
 '07-01-2022.csv',
 '07-02-2020.csv',
 '07-02-2021.csv',
 '07-02-2022.csv',
 '07-03-2020.csv',
 '07-03-2021.csv',
 '07-03-2022.csv',
 '07-04-2020.csv',
 '07-04-2021.csv',
 '07-04-2022.csv',
 '07-05-2020.csv',
 '07-05-2021.csv',
 '07-05-2022.csv',
 '07-06-2020.csv',
 '07-06-2021.csv',
 '07-06-2022.csv',
 '07-07-2020.csv',
 '07-07-2021.csv',
 '07-07-2022.csv',
 '07-08-2020.csv',
 '07-08-2021.csv',
 '07-08-2022.csv',
 '07-09-2020.csv',
 '07-09-2021.csv',
 '07-09-2022.csv',
 '07-10-2020.csv',
 '07-10-2021.csv',
 '07-10-2022.csv',
 '07-11-2020.csv',
 '07-11-2021.csv',
 '07-11-2022.csv',
 '07-12-2020.csv',
 '07-12-2021.csv',
 '07-12-2022.csv',
 '07-13-2020.csv',
 '07-13-2021.csv',
 '07-13-2022.csv',
 '07-14-2020.csv',
 '07-14-2021.csv',
 '07-14-2022.csv',
 '07-15-2020.csv',
 '07-15-2021.csv',
 '07-15-2022.csv',
 '07-16-2020.csv',
 '07-16-2021.csv',
 '07-16-2022.csv',
 '07-17-2020.csv',
 '07-17-2021.csv',
 '07-17-2022.csv',
 '07-18-2020.csv',
 '07-18-2021.csv',
 '07-18-2022.csv',
 '07-19-2020.csv',
 '07-19-2021.csv',
 '07-19-2022.csv',
 '07-20-2020.csv',
 '07-20-2021.csv',
 '07-20-2022.csv',
 '07-21-2020.csv',
 '07-21-2021.csv',
 '07-21-2022.csv',
 '07-22-2020.csv',
 '07-22-2021.csv',
 '07-22-2022.csv',
 '07-23-2020.csv',
 '07-23-2021.csv',
 '07-23-2022.csv',
 '07-24-2020.csv',
 '07-24-2021.csv',
 '07-24-2022.csv',
 '07-25-2020.csv',
 '07-25-2021.csv',
 '07-25-2022.csv',
 '07-26-2020.csv',
 '07-26-2021.csv',
 '07-26-2022.csv',
 '07-27-2020.csv',
 '07-27-2021.csv',
 '07-27-2022.csv',
 '07-28-2020.csv',
 '07-28-2021.csv',
 '07-28-2022.csv',
 '07-29-2020.csv',
 '07-29-2021.csv',
 '07-29-2022.csv',
 '07-30-2020.csv',
 '07-30-2021.csv',
 '07-30-2022.csv',
 '07-31-2020.csv',
 '07-31-2021.csv',
 '07-31-2022.csv',
 '08-01-2020.csv',
 '08-01-2021.csv',
 '08-01-2022.csv',
 '08-02-2020.csv',
 '08-02-2021.csv',
 '08-02-2022.csv',
 '08-03-2020.csv',
 '08-03-2021.csv',
 '08-03-2022.csv',
 '08-04-2020.csv',
 '08-04-2021.csv',
 '08-04-2022.csv',
 '08-05-2020.csv',
 '08-05-2021.csv',
 '08-05-2022.csv',
 '08-06-2020.csv',
 '08-06-2021.csv',
 '08-06-2022.csv',
 '08-07-2020.csv',
 '08-07-2021.csv',
 '08-07-2022.csv',
 '08-08-2020.csv',
 '08-08-2021.csv',
 '08-08-2022.csv',
 '08-09-2020.csv',
 '08-09-2021.csv',
 '08-09-2022.csv',
 '08-10-2020.csv',
 '08-10-2021.csv',
 '08-10-2022.csv',
 '08-11-2020.csv',
 '08-11-2021.csv',
 '08-11-2022.csv',
 '08-12-2020.csv',
 '08-12-2021.csv',
 '08-12-2022.csv',
 '08-13-2020.csv',
 '08-13-2021.csv',
 '08-13-2022.csv',
 '08-14-2020.csv',
 '08-14-2021.csv',
 '08-14-2022.csv',
 '08-15-2020.csv',
 '08-15-2021.csv',
 '08-15-2022.csv',
 '08-16-2020.csv',
 '08-16-2021.csv',
 '08-16-2022.csv',
 '08-17-2020.csv',
 '08-17-2021.csv',
 '08-17-2022.csv',
 '08-18-2020.csv',
 '08-18-2021.csv',
 '08-18-2022.csv',
 '08-19-2020.csv',
 '08-19-2021.csv',
 '08-19-2022.csv',
 '08-20-2020.csv',
 '08-20-2021.csv',
 '08-20-2022.csv',
 '08-21-2020.csv',
 '08-21-2021.csv',
 '08-21-2022.csv',
 '08-22-2020.csv',
 '08-22-2021.csv',
 '08-22-2022.csv',
 '08-23-2020.csv',
 '08-23-2021.csv',
 '08-23-2022.csv',
 '08-24-2020.csv',
 '08-24-2021.csv',
 '08-24-2022.csv',
 '08-25-2020.csv',
 '08-25-2021.csv',
 '08-25-2022.csv',
 '08-26-2020.csv',
 '08-26-2021.csv',
 '08-26-2022.csv',
 '08-27-2020.csv',
 '08-27-2021.csv',
 '08-27-2022.csv',
 '08-28-2020.csv',
 '08-28-2021.csv',
 '08-28-2022.csv',
 '08-29-2020.csv',
 '08-29-2021.csv',
 '08-29-2022.csv',
 '08-30-2020.csv',
 '08-30-2021.csv',
 '08-30-2022.csv',
 '08-31-2020.csv',
 '08-31-2021.csv',
 '08-31-2022.csv',
 '09-01-2020.csv',
 '09-01-2021.csv',
 '09-01-2022.csv',
 '09-02-2020.csv',
 '09-02-2021.csv',
 '09-02-2022.csv',
 '09-03-2020.csv',
 '09-03-2021.csv',
 '09-03-2022.csv',
 '09-04-2020.csv',
 '09-04-2021.csv',
 '09-04-2022.csv',
 '09-05-2020.csv',
 '09-05-2021.csv',
 '09-05-2022.csv',
 '09-06-2020.csv',
 '09-06-2021.csv',
 '09-06-2022.csv',
 '09-07-2020.csv',
 '09-07-2021.csv',
 '09-07-2022.csv',
 '09-08-2020.csv',
 '09-08-2021.csv',
 '09-08-2022.csv',
 '09-09-2020.csv',
 '09-09-2021.csv',
 '09-09-2022.csv',
 '09-10-2020.csv',
 '09-10-2021.csv',
 '09-10-2022.csv',
 '09-11-2020.csv',
 '09-11-2021.csv',
 '09-11-2022.csv',
 '09-12-2020.csv',
 '09-12-2021.csv',
 '09-12-2022.csv',
 '09-13-2020.csv',
 '09-13-2021.csv',
 '09-13-2022.csv',
 '09-14-2020.csv',
 '09-14-2021.csv',
 '09-14-2022.csv',
 '09-15-2020.csv',
 '09-15-2021.csv',
 '09-15-2022.csv',
 '09-16-2020.csv',
 '09-16-2021.csv',
 '09-16-2022.csv',
 '09-17-2020.csv',
 '09-17-2021.csv',
 '09-17-2022.csv',
 '09-18-2020.csv',
 '09-18-2021.csv',
 '09-18-2022.csv',
 '09-19-2020.csv',
 '09-19-2021.csv',
 '09-19-2022.csv',
 '09-20-2020.csv',
 '09-20-2021.csv',
 '09-20-2022.csv',
 '09-21-2020.csv',
 '09-21-2021.csv',
 '09-21-2022.csv',
 '09-22-2020.csv',
 '09-22-2021.csv',
 '09-22-2022.csv',
 '09-23-2020.csv',
 '09-23-2021.csv',
 '09-23-2022.csv',
 '09-24-2020.csv',
 '09-24-2021.csv',
 '09-24-2022.csv',
 '09-25-2020.csv',
 '09-25-2021.csv',
 '09-25-2022.csv',
 '09-26-2020.csv',
 '09-26-2021.csv',
 '09-26-2022.csv',
 '09-27-2020.csv',
 '09-27-2021.csv',
 '09-27-2022.csv',
 '09-28-2020.csv',
 '09-28-2021.csv',
 '09-28-2022.csv',
 '09-29-2020.csv',
 '09-29-2021.csv',
 '09-29-2022.csv',
 '09-30-2020.csv',
 '09-30-2021.csv',
 '09-30-2022.csv',
 '10-01-2020.csv',
 '10-01-2021.csv',
 '10-01-2022.csv',
 '10-02-2020.csv',
 '10-02-2021.csv',
 '10-02-2022.csv',
 '10-03-2020.csv',
 '10-03-2021.csv',
 '10-03-2022.csv',
 '10-04-2020.csv',
 '10-04-2021.csv',
 '10-04-2022.csv',
 '10-05-2020.csv',
 '10-05-2021.csv',
 '10-05-2022.csv',
 '10-06-2020.csv',
 '10-06-2021.csv',
 '10-06-2022.csv',
 '10-07-2020.csv',
 '10-07-2021.csv',
 '10-07-2022.csv',
 '10-08-2020.csv',
 '10-08-2021.csv',
 '10-08-2022.csv',
 '10-09-2020.csv',
 '10-09-2021.csv',
 '10-09-2022.csv',
 '10-10-2020.csv',
 '10-10-2021.csv',
 '10-10-2022.csv',
 '10-11-2020.csv',
 '10-11-2021.csv',
 '10-11-2022.csv',
 '10-12-2020.csv',
 '10-12-2021.csv',
 '10-12-2022.csv',
 '10-13-2020.csv',
 '10-13-2021.csv',
 '10-13-2022.csv',
 '10-14-2020.csv',
 '10-14-2021.csv',
 '10-14-2022.csv',
 '10-15-2020.csv',
 '10-15-2021.csv',
 '10-15-2022.csv',
 '10-16-2020.csv',
 '10-16-2021.csv',
 '10-16-2022.csv',
 '10-17-2020.csv',
 '10-17-2021.csv',
 '10-17-2022.csv',
 '10-18-2020.csv',
 '10-18-2021.csv',
 '10-18-2022.csv',
 '10-19-2020.csv',
 '10-19-2021.csv',
 '10-19-2022.csv',
 '10-20-2020.csv',
 '10-20-2021.csv',
 '10-20-2022.csv',
 '10-21-2020.csv',
 '10-21-2021.csv',
 '10-21-2022.csv',
 '10-22-2020.csv',
 '10-22-2021.csv',
 '10-22-2022.csv',
 '10-23-2020.csv',
 '10-23-2021.csv',
 '10-23-2022.csv',
 '10-24-2020.csv',
 '10-24-2021.csv',
 '10-24-2022.csv',
 '10-25-2020.csv',
 '10-25-2021.csv',
 '10-25-2022.csv',
 '10-26-2020.csv',
 '10-26-2021.csv',
 '10-26-2022.csv',
 '10-27-2020.csv',
 '10-27-2021.csv',
 '10-27-2022.csv',
 '10-28-2020.csv',
 '10-28-2021.csv',
 '10-28-2022.csv',
 '10-29-2020.csv',
 '10-29-2021.csv',
 '10-29-2022.csv',
 '10-30-2020.csv',
 '10-30-2021.csv',
 '10-30-2022.csv',
 '10-31-2020.csv',
 '10-31-2021.csv',
 '10-31-2022.csv',
 '11-01-2020.csv',
 '11-01-2021.csv',
 '11-01-2022.csv',
 '11-02-2020.csv',
 '11-02-2021.csv',
 '11-02-2022.csv',
 '11-03-2020.csv',
 '11-03-2021.csv',
 '11-03-2022.csv',
 '11-04-2020.csv',
 '11-04-2021.csv',
 '11-04-2022.csv',
 '11-05-2020.csv',
 '11-05-2021.csv',
 '11-05-2022.csv',
 '11-06-2020.csv',
 '11-06-2021.csv',
 '11-06-2022.csv',
 '11-07-2020.csv',
 '11-07-2021.csv',
 '11-07-2022.csv',
 '11-08-2020.csv',
 '11-08-2021.csv',
 '11-08-2022.csv',
 '11-09-2020.csv',
 '11-09-2021.csv',
 '11-09-2022.csv',
 '11-10-2020.csv',
 '11-10-2021.csv',
 '11-10-2022.csv',
 '11-11-2020.csv',
 '11-11-2021.csv',
 '11-11-2022.csv',
 '11-12-2020.csv',
 '11-12-2021.csv',
 '11-12-2022.csv',
 '11-13-2020.csv',
 '11-13-2021.csv',
 '11-13-2022.csv',
 ...]

In [60]:
file_list, csv_list = os.listdir(PATH), list()
# csv_list = list()  -- 구조분해할당으로 이걸 안 쓰고 위로 씀

file_list

['.gitignore',
 '01-01-2021.csv',
 '01-01-2022.csv',
 '01-01-2023.csv',
 '01-02-2021.csv',
 '01-02-2022.csv',
 '01-02-2023.csv',
 '01-03-2021.csv',
 '01-03-2022.csv',
 '01-03-2023.csv',
 '01-04-2021.csv',
 '01-04-2022.csv',
 '01-04-2023.csv',
 '01-05-2021.csv',
 '01-05-2022.csv',
 '01-05-2023.csv',
 '01-06-2021.csv',
 '01-06-2022.csv',
 '01-06-2023.csv',
 '01-07-2021.csv',
 '01-07-2022.csv',
 '01-07-2023.csv',
 '01-08-2021.csv',
 '01-08-2022.csv',
 '01-08-2023.csv',
 '01-09-2021.csv',
 '01-09-2022.csv',
 '01-09-2023.csv',
 '01-10-2021.csv',
 '01-10-2022.csv',
 '01-10-2023.csv',
 '01-11-2021.csv',
 '01-11-2022.csv',
 '01-11-2023.csv',
 '01-12-2021.csv',
 '01-12-2022.csv',
 '01-12-2023.csv',
 '01-13-2021.csv',
 '01-13-2022.csv',
 '01-13-2023.csv',
 '01-14-2021.csv',
 '01-14-2022.csv',
 '01-14-2023.csv',
 '01-15-2021.csv',
 '01-15-2022.csv',
 '01-15-2023.csv',
 '01-16-2021.csv',
 '01-16-2022.csv',
 '01-16-2023.csv',
 '01-17-2021.csv',
 '01-17-2022.csv',
 '01-17-2023.csv',
 '01-18-2021.csv',
 '01-18-2022.csv',
 '01-18-2023.csv',
 '01-19-2021.csv',
 '01-19-2022.csv',
 '01-19-2023.csv',
 '01-20-2021.csv',
 '01-20-2022.csv',
 '01-20-2023.csv',
 '01-21-2021.csv',
 '01-21-2022.csv',
 '01-21-2023.csv',
 '01-22-2020.csv',
 '01-22-2021.csv',
 '01-22-2022.csv',
 '01-22-2023.csv',
 '01-23-2020.csv',
 '01-23-2021.csv',
 '01-23-2022.csv',
 '01-23-2023.csv',
 '01-24-2020.csv',
 '01-24-2021.csv',
 '01-24-2022.csv',
 '01-24-2023.csv',
 '01-25-2020.csv',
 '01-25-2021.csv',
 '01-25-2022.csv',
 '01-25-2023.csv',
 '01-26-2020.csv',
 '01-26-2021.csv',
 '01-26-2022.csv',
 '01-26-2023.csv',
 '01-27-2020.csv',
 '01-27-2021.csv',
 '01-27-2022.csv',
 '01-27-2023.csv',
 '01-28-2020.csv',
 '01-28-2021.csv',
 '01-28-2022.csv',
 '01-28-2023.csv',
 '01-29-2020.csv',
 '01-29-2021.csv',
 '01-29-2022.csv',
 '01-29-2023.csv',
 '01-30-2020.csv',
 '01-30-2021.csv',
 '01-30-2022.csv',
 '01-30-2023.csv',
 '01-31-2020.csv',
 '01-31-2021.csv',
 '01-31-2022.csv',
 '01-31-2023.csv',
 '02-01-2020.csv',
 '02-01-2021.csv',
 '02-01-2022.csv',
 '02-01-2023.csv',
 '02-02-2020.csv',
 '02-02-2021.csv',
 '02-02-2022.csv',
 '02-02-2023.csv',
 '02-03-2020.csv',
 '02-03-2021.csv',
 '02-03-2022.csv',
 '02-03-2023.csv',
 '02-04-2020.csv',
 '02-04-2021.csv',
 '02-04-2022.csv',
 '02-04-2023.csv',
 '02-05-2020.csv',
 '02-05-2021.csv',
 '02-05-2022.csv',
 '02-05-2023.csv',
 '02-06-2020.csv',
 '02-06-2021.csv',
 '02-06-2022.csv',
 '02-06-2023.csv',
 '02-07-2020.csv',
 '02-07-2021.csv',
 '02-07-2022.csv',
 '02-07-2023.csv',
 '02-08-2020.csv',
 '02-08-2021.csv',
 '02-08-2022.csv',
 '02-08-2023.csv',
 '02-09-2020.csv',
 '02-09-2021.csv',
 '02-09-2022.csv',
 '02-09-2023.csv',
 '02-10-2020.csv',
 '02-10-2021.csv',
 '02-10-2022.csv',
 '02-10-2023.csv',
 '02-11-2020.csv',
 '02-11-2021.csv',
 '02-11-2022.csv',
 '02-11-2023.csv',
 '02-12-2020.csv',
 '02-12-2021.csv',
 '02-12-2022.csv',
 '02-12-2023.csv',
 '02-13-2020.csv',
 '02-13-2021.csv',
 '02-13-2022.csv',
 '02-13-2023.csv',
 '02-14-2020.csv',
 '02-14-2021.csv',
 '02-14-2022.csv',
 '02-14-2023.csv',
 '02-15-2020.csv',
 '02-15-2021.csv',
 '02-15-2022.csv',
 '02-15-2023.csv',
 '02-16-2020.csv',
 '02-16-2021.csv',
 '02-16-2022.csv',
 '02-16-2023.csv',
 '02-17-2020.csv',
 '02-17-2021.csv',
 '02-17-2022.csv',
 '02-17-2023.csv',
 '02-18-2020.csv',
 '02-18-2021.csv',
 '02-18-2022.csv',
 '02-18-2023.csv',
 '02-19-2020.csv',
 '02-19-2021.csv',
 '02-19-2022.csv',
 '02-19-2023.csv',
 '02-20-2020.csv',
 '02-20-2021.csv',
 '02-20-2022.csv',
 '02-20-2023.csv',
 '02-21-2020.csv',
 '02-21-2021.csv',
 '02-21-2022.csv',
 '02-21-2023.csv',
 '02-22-2020.csv',
 '02-22-2021.csv',
 '02-22-2022.csv',
 '02-22-2023.csv',
 '02-23-2020.csv',
 '02-23-2021.csv',
 '02-23-2022.csv',
 '02-23-2023.csv',
 '02-24-2020.csv',
 '02-24-2021.csv',
 '02-24-2022.csv',
 '02-24-2023.csv',
 '02-25-2020.csv',
 '02-25-2021.csv',
 '02-25-2022.csv',
 '02-25-2023.csv',
 '02-26-2020.csv',
 '02-26-2021.csv',
 '02-26-2022.csv',
 '02-26-2023.csv',
 '02-27-2020.csv',
 '02-27-2021.csv',
 '02-27-2022.csv',
 '02-27-2023.csv',
 '02-28-2020.csv',
 '02-28-2021.csv',
 '02-28-2022.csv',
 '02-28-2023.csv',
 '02-29-2020.csv',
 '03-01-2020.csv',
 '03-01-2021.csv',
 '03-01-2022.csv',
 '03-01-2023.csv',
 '03-02-2020.csv',
 '03-02-2021.csv',
 '03-02-2022.csv',
 '03-02-2023.csv',
 '03-03-2020.csv',
 '03-03-2021.csv',
 '03-03-2022.csv',
 '03-03-2023.csv',
 '03-04-2020.csv',
 '03-04-2021.csv',
 '03-04-2022.csv',
 '03-04-2023.csv',
 '03-05-2020.csv',
 '03-05-2021.csv',
 '03-05-2022.csv',
 '03-05-2023.csv',
 '03-06-2020.csv',
 '03-06-2021.csv',
 '03-06-2022.csv',
 '03-06-2023.csv',
 '03-07-2020.csv',
 '03-07-2021.csv',
 '03-07-2022.csv',
 '03-07-2023.csv',
 '03-08-2020.csv',
 '03-08-2021.csv',
 '03-08-2022.csv',
 '03-08-2023.csv',
 '03-09-2020.csv',
 '03-09-2021.csv',
 '03-09-2022.csv',
 '03-09-2023.csv',
 '03-10-2020.csv',
 '03-10-2021.csv',
 '03-10-2022.csv',
 '03-11-2020.csv',
 '03-11-2021.csv',
 '03-11-2022.csv',
 '03-12-2020.csv',
 '03-12-2021.csv',
 '03-12-2022.csv',
 '03-13-2020.csv',
 '03-13-2021.csv',
 '03-13-2022.csv',
 '03-14-2020.csv',
 '03-14-2021.csv',
 '03-14-2022.csv',
 '03-15-2020.csv',
 '03-15-2021.csv',
 '03-15-2022.csv',
 '03-16-2020.csv',
 '03-16-2021.csv',
 '03-16-2022.csv',
 '03-17-2020.csv',
 '03-17-2021.csv',
 '03-17-2022.csv',
 '03-18-2020.csv',
 '03-18-2021.csv',
 '03-18-2022.csv',
 '03-19-2020.csv',
 '03-19-2021.csv',
 '03-19-2022.csv',
 '03-20-2020.csv',
 '03-20-2021.csv',
 '03-20-2022.csv',
 '03-21-2020.csv',
 '03-21-2021.csv',
 '03-21-2022.csv',
 '03-22-2020.csv',
 '03-22-2021.csv',
 '03-22-2022.csv',
 '03-23-2020.csv',
 '03-23-2021.csv',
 '03-23-2022.csv',
 '03-24-2020.csv',
 '03-24-2021.csv',
 '03-24-2022.csv',
 '03-25-2020.csv',
 '03-25-2021.csv',
 '03-25-2022.csv',
 '03-26-2020.csv',
 '03-26-2021.csv',
 '03-26-2022.csv',
 '03-27-2020.csv',
 '03-27-2021.csv',
 '03-27-2022.csv',
 '03-28-2020.csv',
 '03-28-2021.csv',
 '03-28-2022.csv',
 '03-29-2020.csv',
 '03-29-2021.csv',
 '03-29-2022.csv',
 '03-30-2020.csv',
 '03-30-2021.csv',
 '03-30-2022.csv',
 '03-31-2020.csv',
 '03-31-2021.csv',
 '03-31-2022.csv',
 '04-01-2020.csv',
 '04-01-2021.csv',
 '04-01-2022.csv',
 '04-02-2020.csv',
 '04-02-2021.csv',
 '04-02-2022.csv',
 '04-03-2020.csv',
 '04-03-2021.csv',
 '04-03-2022.csv',
 '04-04-2020.csv',
 '04-04-2021.csv',
 '04-04-2022.csv',
 '04-05-2020.csv',
 '04-05-2021.csv',
 '04-05-2022.csv',
 '04-06-2020.csv',
 '04-06-2021.csv',
 '04-06-2022.csv',
 '04-07-2020.csv',
 '04-07-2021.csv',
 '04-07-2022.csv',
 '04-08-2020.csv',
 '04-08-2021.csv',
 '04-08-2022.csv',
 '04-09-2020.csv',
 '04-09-2021.csv',
 '04-09-2022.csv',
 '04-10-2020.csv',
 '04-10-2021.csv',
 '04-10-2022.csv',
 '04-11-2020.csv',
 '04-11-2021.csv',
 '04-11-2022.csv',
 '04-12-2020.csv',
 '04-12-2021.csv',
 '04-12-2022.csv',
 '04-13-2020.csv',
 '04-13-2021.csv',
 '04-13-2022.csv',
 '04-14-2020.csv',
 '04-14-2021.csv',
 '04-14-2022.csv',
 '04-15-2020.csv',
 '04-15-2021.csv',
 '04-15-2022.csv',
 '04-16-2020.csv',
 '04-16-2021.csv',
 '04-16-2022.csv',
 '04-17-2020.csv',
 '04-17-2021.csv',
 '04-17-2022.csv',
 '04-18-2020.csv',
 '04-18-2021.csv',
 '04-18-2022.csv',
 '04-19-2020.csv',
 '04-19-2021.csv',
 '04-19-2022.csv',
 '04-20-2020.csv',
 '04-20-2021.csv',
 '04-20-2022.csv',
 '04-21-2020.csv',
 '04-21-2021.csv',
 '04-21-2022.csv',
 '04-22-2020.csv',
 '04-22-2021.csv',
 '04-22-2022.csv',
 '04-23-2020.csv',
 '04-23-2021.csv',
 '04-23-2022.csv',
 '04-24-2020.csv',
 '04-24-2021.csv',
 '04-24-2022.csv',
 '04-25-2020.csv',
 '04-25-2021.csv',
 '04-25-2022.csv',
 '04-26-2020.csv',
 '04-26-2021.csv',
 '04-26-2022.csv',
 '04-27-2020.csv',
 '04-27-2021.csv',
 '04-27-2022.csv',
 '04-28-2020.csv',
 '04-28-2021.csv',
 '04-28-2022.csv',
 '04-29-2020.csv',
 '04-29-2021.csv',
 '04-29-2022.csv',
 '04-30-2020.csv',
 '04-30-2021.csv',
 '04-30-2022.csv',
 '05-01-2020.csv',
 '05-01-2021.csv',
 '05-01-2022.csv',
 '05-02-2020.csv',
 '05-02-2021.csv',
 '05-02-2022.csv',
 '05-03-2020.csv',
 '05-03-2021.csv',
 '05-03-2022.csv',
 '05-04-2020.csv',
 '05-04-2021.csv',
 '05-04-2022.csv',
 '05-05-2020.csv',
 '05-05-2021.csv',
 '05-05-2022.csv',
 '05-06-2020.csv',
 '05-06-2021.csv',
 '05-06-2022.csv',
 '05-07-2020.csv',
 '05-07-2021.csv',
 '05-07-2022.csv',
 '05-08-2020.csv',
 '05-08-2021.csv',
 '05-08-2022.csv',
 '05-09-2020.csv',
 '05-09-2021.csv',
 '05-09-2022.csv',
 '05-10-2020.csv',
 '05-10-2021.csv',
 '05-10-2022.csv',
 '05-11-2020.csv',
 '05-11-2021.csv',
 '05-11-2022.csv',
 '05-12-2020.csv',
 '05-12-2021.csv',
 '05-12-2022.csv',
 '05-13-2020.csv',
 '05-13-2021.csv',
 '05-13-2022.csv',
 '05-14-2020.csv',
 '05-14-2021.csv',
 '05-14-2022.csv',
 '05-15-2020.csv',
 '05-15-2021.csv',
 '05-15-2022.csv',
 '05-16-2020.csv',
 '05-16-2021.csv',
 '05-16-2022.csv',
 '05-17-2020.csv',
 '05-17-2021.csv',
 '05-17-2022.csv',
 '05-18-2020.csv',
 '05-18-2021.csv',
 '05-18-2022.csv',
 '05-19-2020.csv',
 '05-19-2021.csv',
 '05-19-2022.csv',
 '05-20-2020.csv',
 '05-20-2021.csv',
 '05-20-2022.csv',
 '05-21-2020.csv',
 '05-21-2021.csv',
 '05-21-2022.csv',
 '05-22-2020.csv',
 '05-22-2021.csv',
 '05-22-2022.csv',
 '05-23-2020.csv',
 '05-23-2021.csv',
 '05-23-2022.csv',
 '05-24-2020.csv',
 '05-24-2021.csv',
 '05-24-2022.csv',
 '05-25-2020.csv',
 '05-25-2021.csv',
 '05-25-2022.csv',
 '05-26-2020.csv',
 '05-26-2021.csv',
 '05-26-2022.csv',
 '05-27-2020.csv',
 '05-27-2021.csv',
 '05-27-2022.csv',
 '05-28-2020.csv',
 '05-28-2021.csv',
 '05-28-2022.csv',
 '05-29-2020.csv',
 '05-29-2021.csv',
 '05-29-2022.csv',
 '05-30-2020.csv',
 '05-30-2021.csv',
 '05-30-2022.csv',
 '05-31-2020.csv',
 '05-31-2021.csv',
 '05-31-2022.csv',
 '06-01-2020.csv',
 '06-01-2021.csv',
 '06-01-2022.csv',
 '06-02-2020.csv',
 '06-02-2021.csv',
 '06-02-2022.csv',
 '06-03-2020.csv',
 '06-03-2021.csv',
 '06-03-2022.csv',
 '06-04-2020.csv',
 '06-04-2021.csv',
 '06-04-2022.csv',
 '06-05-2020.csv',
 '06-05-2021.csv',
 '06-05-2022.csv',
 '06-06-2020.csv',
 '06-06-2021.csv',
 '06-06-2022.csv',
 '06-07-2020.csv',
 '06-07-2021.csv',
 '06-07-2022.csv',
 '06-08-2020.csv',
 '06-08-2021.csv',
 '06-08-2022.csv',
 '06-09-2020.csv',
 '06-09-2021.csv',
 '06-09-2022.csv',
 '06-10-2020.csv',
 '06-10-2021.csv',
 '06-10-2022.csv',
 '06-11-2020.csv',
 '06-11-2021.csv',
 '06-11-2022.csv',
 '06-12-2020.csv',
 '06-12-2021.csv',
 '06-12-2022.csv',
 '06-13-2020.csv',
 '06-13-2021.csv',
 '06-13-2022.csv',
 '06-14-2020.csv',
 '06-14-2021.csv',
 '06-14-2022.csv',
 '06-15-2020.csv',
 '06-15-2021.csv',
 '06-15-2022.csv',
 '06-16-2020.csv',
 '06-16-2021.csv',
 '06-16-2022.csv',
 '06-17-2020.csv',
 '06-17-2021.csv',
 '06-17-2022.csv',
 '06-18-2020.csv',
 '06-18-2021.csv',
 '06-18-2022.csv',
 '06-19-2020.csv',
 '06-19-2021.csv',
 '06-19-2022.csv',
 '06-20-2020.csv',
 '06-20-2021.csv',
 '06-20-2022.csv',
 '06-21-2020.csv',
 '06-21-2021.csv',
 '06-21-2022.csv',
 '06-22-2020.csv',
 '06-22-2021.csv',
 '06-22-2022.csv',
 '06-23-2020.csv',
 '06-23-2021.csv',
 '06-23-2022.csv',
 '06-24-2020.csv',
 '06-24-2021.csv',
 '06-24-2022.csv',
 '06-25-2020.csv',
 '06-25-2021.csv',
 '06-25-2022.csv',
 '06-26-2020.csv',
 '06-26-2021.csv',
 '06-26-2022.csv',
 '06-27-2020.csv',
 '06-27-2021.csv',
 '06-27-2022.csv',
 '06-28-2020.csv',
 '06-28-2021.csv',
 '06-28-2022.csv',
 '06-29-2020.csv',
 '06-29-2021.csv',
 '06-29-2022.csv',
 '06-30-2020.csv',
 '06-30-2021.csv',
 '06-30-2022.csv',
 '07-01-2020.csv',
 '07-01-2021.csv',
 '07-01-2022.csv',
 '07-02-2020.csv',
 '07-02-2021.csv',
 '07-02-2022.csv',
 '07-03-2020.csv',
 '07-03-2021.csv',
 '07-03-2022.csv',
 '07-04-2020.csv',
 '07-04-2021.csv',
 '07-04-2022.csv',
 '07-05-2020.csv',
 '07-05-2021.csv',
 '07-05-2022.csv',
 '07-06-2020.csv',
 '07-06-2021.csv',
 '07-06-2022.csv',
 '07-07-2020.csv',
 '07-07-2021.csv',
 '07-07-2022.csv',
 '07-08-2020.csv',
 '07-08-2021.csv',
 '07-08-2022.csv',
 '07-09-2020.csv',
 '07-09-2021.csv',
 '07-09-2022.csv',
 '07-10-2020.csv',
 '07-10-2021.csv',
 '07-10-2022.csv',
 '07-11-2020.csv',
 '07-11-2021.csv',
 '07-11-2022.csv',
 '07-12-2020.csv',
 '07-12-2021.csv',
 '07-12-2022.csv',
 '07-13-2020.csv',
 '07-13-2021.csv',
 '07-13-2022.csv',
 '07-14-2020.csv',
 '07-14-2021.csv',
 '07-14-2022.csv',
 '07-15-2020.csv',
 '07-15-2021.csv',
 '07-15-2022.csv',
 '07-16-2020.csv',
 '07-16-2021.csv',
 '07-16-2022.csv',
 '07-17-2020.csv',
 '07-17-2021.csv',
 '07-17-2022.csv',
 '07-18-2020.csv',
 '07-18-2021.csv',
 '07-18-2022.csv',
 '07-19-2020.csv',
 '07-19-2021.csv',
 '07-19-2022.csv',
 '07-20-2020.csv',
 '07-20-2021.csv',
 '07-20-2022.csv',
 '07-21-2020.csv',
 '07-21-2021.csv',
 '07-21-2022.csv',
 '07-22-2020.csv',
 '07-22-2021.csv',
 '07-22-2022.csv',
 '07-23-2020.csv',
 '07-23-2021.csv',
 '07-23-2022.csv',
 '07-24-2020.csv',
 '07-24-2021.csv',
 '07-24-2022.csv',
 '07-25-2020.csv',
 '07-25-2021.csv',
 '07-25-2022.csv',
 '07-26-2020.csv',
 '07-26-2021.csv',
 '07-26-2022.csv',
 '07-27-2020.csv',
 '07-27-2021.csv',
 '07-27-2022.csv',
 '07-28-2020.csv',
 '07-28-2021.csv',
 '07-28-2022.csv',
 '07-29-2020.csv',
 '07-29-2021.csv',
 '07-29-2022.csv',
 '07-30-2020.csv',
 '07-30-2021.csv',
 '07-30-2022.csv',
 '07-31-2020.csv',
 '07-31-2021.csv',
 '07-31-2022.csv',
 '08-01-2020.csv',
 '08-01-2021.csv',
 '08-01-2022.csv',
 '08-02-2020.csv',
 '08-02-2021.csv',
 '08-02-2022.csv',
 '08-03-2020.csv',
 '08-03-2021.csv',
 '08-03-2022.csv',
 '08-04-2020.csv',
 '08-04-2021.csv',
 '08-04-2022.csv',
 '08-05-2020.csv',
 '08-05-2021.csv',
 '08-05-2022.csv',
 '08-06-2020.csv',
 '08-06-2021.csv',
 '08-06-2022.csv',
 '08-07-2020.csv',
 '08-07-2021.csv',
 '08-07-2022.csv',
 '08-08-2020.csv',
 '08-08-2021.csv',
 '08-08-2022.csv',
 '08-09-2020.csv',
 '08-09-2021.csv',
 '08-09-2022.csv',
 '08-10-2020.csv',
 '08-10-2021.csv',
 '08-10-2022.csv',
 '08-11-2020.csv',
 '08-11-2021.csv',
 '08-11-2022.csv',
 '08-12-2020.csv',
 '08-12-2021.csv',
 '08-12-2022.csv',
 '08-13-2020.csv',
 '08-13-2021.csv',
 '08-13-2022.csv',
 '08-14-2020.csv',
 '08-14-2021.csv',
 '08-14-2022.csv',
 '08-15-2020.csv',
 '08-15-2021.csv',
 '08-15-2022.csv',
 '08-16-2020.csv',
 '08-16-2021.csv',
 '08-16-2022.csv',
 '08-17-2020.csv',
 '08-17-2021.csv',
 '08-17-2022.csv',
 '08-18-2020.csv',
 '08-18-2021.csv',
 '08-18-2022.csv',
 '08-19-2020.csv',
 '08-19-2021.csv',
 '08-19-2022.csv',
 '08-20-2020.csv',
 '08-20-2021.csv',
 '08-20-2022.csv',
 '08-21-2020.csv',
 '08-21-2021.csv',
 '08-21-2022.csv',
 '08-22-2020.csv',
 '08-22-2021.csv',
 '08-22-2022.csv',
 '08-23-2020.csv',
 '08-23-2021.csv',
 '08-23-2022.csv',
 '08-24-2020.csv',
 '08-24-2021.csv',
 '08-24-2022.csv',
 '08-25-2020.csv',
 '08-25-2021.csv',
 '08-25-2022.csv',
 '08-26-2020.csv',
 '08-26-2021.csv',
 '08-26-2022.csv',
 '08-27-2020.csv',
 '08-27-2021.csv',
 '08-27-2022.csv',
 '08-28-2020.csv',
 '08-28-2021.csv',
 '08-28-2022.csv',
 '08-29-2020.csv',
 '08-29-2021.csv',
 '08-29-2022.csv',
 '08-30-2020.csv',
 '08-30-2021.csv',
 '08-30-2022.csv',
 '08-31-2020.csv',
 '08-31-2021.csv',
 '08-31-2022.csv',
 '09-01-2020.csv',
 '09-01-2021.csv',
 '09-01-2022.csv',
 '09-02-2020.csv',
 '09-02-2021.csv',
 '09-02-2022.csv',
 '09-03-2020.csv',
 '09-03-2021.csv',
 '09-03-2022.csv',
 '09-04-2020.csv',
 '09-04-2021.csv',
 '09-04-2022.csv',
 '09-05-2020.csv',
 '09-05-2021.csv',
 '09-05-2022.csv',
 '09-06-2020.csv',
 '09-06-2021.csv',
 '09-06-2022.csv',
 '09-07-2020.csv',
 '09-07-2021.csv',
 '09-07-2022.csv',
 '09-08-2020.csv',
 '09-08-2021.csv',
 '09-08-2022.csv',
 '09-09-2020.csv',
 '09-09-2021.csv',
 '09-09-2022.csv',
 '09-10-2020.csv',
 '09-10-2021.csv',
 '09-10-2022.csv',
 '09-11-2020.csv',
 '09-11-2021.csv',
 '09-11-2022.csv',
 '09-12-2020.csv',
 '09-12-2021.csv',
 '09-12-2022.csv',
 '09-13-2020.csv',
 '09-13-2021.csv',
 '09-13-2022.csv',
 '09-14-2020.csv',
 '09-14-2021.csv',
 '09-14-2022.csv',
 '09-15-2020.csv',
 '09-15-2021.csv',
 '09-15-2022.csv',
 '09-16-2020.csv',
 '09-16-2021.csv',
 '09-16-2022.csv',
 '09-17-2020.csv',
 '09-17-2021.csv',
 '09-17-2022.csv',
 '09-18-2020.csv',
 '09-18-2021.csv',
 '09-18-2022.csv',
 '09-19-2020.csv',
 '09-19-2021.csv',
 '09-19-2022.csv',
 '09-20-2020.csv',
 '09-20-2021.csv',
 '09-20-2022.csv',
 '09-21-2020.csv',
 '09-21-2021.csv',
 '09-21-2022.csv',
 '09-22-2020.csv',
 '09-22-2021.csv',
 '09-22-2022.csv',
 '09-23-2020.csv',
 '09-23-2021.csv',
 '09-23-2022.csv',
 '09-24-2020.csv',
 '09-24-2021.csv',
 '09-24-2022.csv',
 '09-25-2020.csv',
 '09-25-2021.csv',
 '09-25-2022.csv',
 '09-26-2020.csv',
 '09-26-2021.csv',
 '09-26-2022.csv',
 '09-27-2020.csv',
 '09-27-2021.csv',
 '09-27-2022.csv',
 '09-28-2020.csv',
 '09-28-2021.csv',
 '09-28-2022.csv',
 '09-29-2020.csv',
 '09-29-2021.csv',
 '09-29-2022.csv',
 '09-30-2020.csv',
 '09-30-2021.csv',
 '09-30-2022.csv',
 '10-01-2020.csv',
 '10-01-2021.csv',
 '10-01-2022.csv',
 '10-02-2020.csv',
 '10-02-2021.csv',
 '10-02-2022.csv',
 '10-03-2020.csv',
 '10-03-2021.csv',
 '10-03-2022.csv',
 '10-04-2020.csv',
 '10-04-2021.csv',
 '10-04-2022.csv',
 '10-05-2020.csv',
 '10-05-2021.csv',
 '10-05-2022.csv',
 '10-06-2020.csv',
 '10-06-2021.csv',
 '10-06-2022.csv',
 '10-07-2020.csv',
 '10-07-2021.csv',
 '10-07-2022.csv',
 '10-08-2020.csv',
 '10-08-2021.csv',
 '10-08-2022.csv',
 '10-09-2020.csv',
 '10-09-2021.csv',
 '10-09-2022.csv',
 '10-10-2020.csv',
 '10-10-2021.csv',
 '10-10-2022.csv',
 '10-11-2020.csv',
 '10-11-2021.csv',
 '10-11-2022.csv',
 '10-12-2020.csv',
 '10-12-2021.csv',
 '10-12-2022.csv',
 '10-13-2020.csv',
 '10-13-2021.csv',
 '10-13-2022.csv',
 '10-14-2020.csv',
 '10-14-2021.csv',
 '10-14-2022.csv',
 '10-15-2020.csv',
 '10-15-2021.csv',
 '10-15-2022.csv',
 '10-16-2020.csv',
 '10-16-2021.csv',
 '10-16-2022.csv',
 '10-17-2020.csv',
 '10-17-2021.csv',
 '10-17-2022.csv',
 '10-18-2020.csv',
 '10-18-2021.csv',
 '10-18-2022.csv',
 '10-19-2020.csv',
 '10-19-2021.csv',
 '10-19-2022.csv',
 '10-20-2020.csv',
 '10-20-2021.csv',
 '10-20-2022.csv',
 '10-21-2020.csv',
 '10-21-2021.csv',
 '10-21-2022.csv',
 '10-22-2020.csv',
 '10-22-2021.csv',
 '10-22-2022.csv',
 '10-23-2020.csv',
 '10-23-2021.csv',
 '10-23-2022.csv',
 '10-24-2020.csv',
 '10-24-2021.csv',
 '10-24-2022.csv',
 '10-25-2020.csv',
 '10-25-2021.csv',
 '10-25-2022.csv',
 '10-26-2020.csv',
 '10-26-2021.csv',
 '10-26-2022.csv',
 '10-27-2020.csv',
 '10-27-2021.csv',
 '10-27-2022.csv',
 '10-28-2020.csv',
 '10-28-2021.csv',
 '10-28-2022.csv',
 '10-29-2020.csv',
 '10-29-2021.csv',
 '10-29-2022.csv',
 '10-30-2020.csv',
 '10-30-2021.csv',
 '10-30-2022.csv',
 '10-31-2020.csv',
 '10-31-2021.csv',
 '10-31-2022.csv',
 '11-01-2020.csv',
 '11-01-2021.csv',
 '11-01-2022.csv',
 '11-02-2020.csv',
 '11-02-2021.csv',
 '11-02-2022.csv',
 '11-03-2020.csv',
 '11-03-2021.csv',
 '11-03-2022.csv',
 '11-04-2020.csv',
 '11-04-2021.csv',
 '11-04-2022.csv',
 '11-05-2020.csv',
 '11-05-2021.csv',
 '11-05-2022.csv',
 '11-06-2020.csv',
 '11-06-2021.csv',
 '11-06-2022.csv',
 '11-07-2020.csv',
 '11-07-2021.csv',
 '11-07-2022.csv',
 '11-08-2020.csv',
 '11-08-2021.csv',
 '11-08-2022.csv',
 '11-09-2020.csv',
 '11-09-2021.csv',
 '11-09-2022.csv',
 '11-10-2020.csv',
 '11-10-2021.csv',
 '11-10-2022.csv',
 '11-11-2020.csv',
 '11-11-2021.csv',
 '11-11-2022.csv',
 '11-12-2020.csv',
 '11-12-2021.csv',
 '11-12-2022.csv',
 '11-13-2020.csv',
 '11-13-2021.csv',
 '11-13-2022.csv',
 ...]

In [62]:
file_list, csv_list = os.listdir(PATH), list()

for file in file_list :
    if file.split(".")[-1] == "csv" :
        csv_list.append(file)

print(csv_list)

['01-01-2021.csv', '01-01-2022.csv', '01-01-2023.csv', '01-02-2021.csv', '01-02-2022.csv', '01-02-2023.csv', '01-03-2021.csv', '01-03-2022.csv', '01-03-2023.csv', '01-04-2021.csv', '01-04-2022.csv', '01-04-2023.csv', '01-05-2021.csv', '01-05-2022.csv', '01-05-2023.csv', '01-06-2021.csv', '01-06-2022.csv', '01-06-2023.csv', '01-07-2021.csv', '01-07-2022.csv', '01-07-2023.csv', '01-08-2021.csv', '01-08-2022.csv', '01-08-2023.csv', '01-09-2021.csv', '01-09-2022.csv', '01-09-2023.csv', '01-10-2021.csv', '01-10-2022.csv', '01-10-2023.csv', '01-11-2021.csv', '01-11-2022.csv', '01-11-2023.csv', '01-12-2021.csv', '01-12-2022.csv', '01-12-2023.csv', '01-13-2021.csv', '01-13-2022.csv', '01-13-2023.csv', '01-14-2021.csv', '01-14-2022.csv', '01-14-2023.csv', '01-15-2021.csv', '01-15-2022.csv', '01-15-2023.csv', '01-16-2021.csv', '01-16-2022.csv', '01-16-2023.csv', '01-17-2021.csv', '01-17-2022.csv', '01-17-2023.csv', '01-18-2021.csv', '01-18-2022.csv', '01-18-2023.csv', '01-19-2021.csv', '01-19-2022.csv', '01-19-2023.csv', '01-20-2021.csv', '01-20-2022.csv', '01-20-2023.csv', '01-21-2021.csv', '01-21-2022.csv', '01-21-2023.csv', '01-22-2020.csv', '01-22-2021.csv', '01-22-2022.csv', '01-22-2023.csv', '01-23-2020.csv', '01-23-2021.csv', '01-23-2022.csv', '01-23-2023.csv', '01-24-2020.csv', '01-24-2021.csv', '01-24-2022.csv', '01-24-2023.csv', '01-25-2020.csv', '01-25-2021.csv', '01-25-2022.csv', '01-25-2023.csv', '01-26-2020.csv', '01-26-2021.csv', '01-26-2022.csv', '01-26-2023.csv', '01-27-2020.csv', '01-27-2021.csv', '01-27-2022.csv', '01-27-2023.csv', '01-28-2020.csv', '01-28-2021.csv', '01-28-2022.csv', '01-28-2023.csv', '01-29-2020.csv', '01-29-2021.csv', '01-29-2022.csv', '01-29-2023.csv', '01-30-2020.csv', '01-30-2021.csv', '01-30-2022.csv', '01-30-2023.csv', '01-31-2020.csv', '01-31-2021.csv', '01-31-2022.csv', '01-31-2023.csv', '02-01-2020.csv', '02-01-2021.csv', '02-01-2022.csv', '02-01-2023.csv', '02-02-2020.csv', '02-02-2021.csv', '02-02-2022.csv', '02-02-2023.csv', '02-03-2020.csv', '02-03-2021.csv', '02-03-2022.csv', '02-03-2023.csv', '02-04-2020.csv', '02-04-2021.csv', '02-04-2022.csv', '02-04-2023.csv', '02-05-2020.csv', '02-05-2021.csv', '02-05-2022.csv', '02-05-2023.csv', '02-06-2020.csv', '02-06-2021.csv', '02-06-2022.csv', '02-06-2023.csv', '02-07-2020.csv', '02-07-2021.csv', '02-07-2022.csv', '02-07-2023.csv', '02-08-2020.csv', '02-08-2021.csv', '02-08-2022.csv', '02-08-2023.csv', '02-09-2020.csv', '02-09-2021.csv', '02-09-2022.csv', '02-09-2023.csv', '02-10-2020.csv', '02-10-2021.csv', '02-10-2022.csv', '02-10-2023.csv', '02-11-2020.csv', '02-11-2021.csv', '02-11-2022.csv', '02-11-2023.csv', '02-12-2020.csv', '02-12-2021.csv', '02-12-2022.csv', '02-12-2023.csv', '02-13-2020.csv', '02-13-2021.csv', '02-13-2022.csv', '02-13-2023.csv', '02-14-2020.csv', '02-14-2021.csv', '02-14-2022.csv', '02-14-2023.csv', '02-15-2020.csv', '02-15-2021.csv', '02-15-2022.csv', '02-15-2023.csv', '02-16-2020.csv', '02-16-2021.csv', '02-16-2022.csv', '02-16-2023.csv', '02-17-2020.csv', '02-17-2021.csv', '02-17-2022.csv', '02-17-2023.csv', '02-18-2020.csv', '02-18-2021.csv', '02-18-2022.csv', '02-18-2023.csv', '02-19-2020.csv', '02-19-2021.csv', '02-19-2022.csv', '02-19-2023.csv', '02-20-2020.csv', '02-20-2021.csv', '02-20-2022.csv', '02-20-2023.csv', '02-21-2020.csv', '02-21-2021.csv', '02-21-2022.csv', '02-21-2023.csv', '02-22-2020.csv', '02-22-2021.csv', '02-22-2022.csv', '02-22-2023.csv', '02-23-2020.csv', '02-23-2021.csv', '02-23-2022.csv', '02-23-2023.csv', '02-24-2020.csv', '02-24-2021.csv', '02-24-2022.csv', '02-24-2023.csv', '02-25-2020.csv', '02-25-2021.csv', '02-25-2022.csv', '02-25-2023.csv', '02-26-2020.csv', '02-26-2021.csv', '02-26-2022.csv', '02-26-2023.csv', '02-27-2020.csv', '02-27-2021.csv', '02-27-2022.csv', '02-27-2023.csv', '02-28-2020.csv', '02-28-2021.csv', '02-28-2022.csv', '02-28-2023.csv', '02-29-2020.csv', '03-01-2020.csv', '03-01-2021.csv', '03-01-2022.csv', '03-01-2023.csv', '03-02-2020.csv', '03-02-2021.csv', '03-02-2022.csv', '03-02-2023.csv', '03-03-2020.csv', '03-03-2021.csv', '03-03-2022.csv', '03-03-2023.csv', '03-04-2020.csv', '03-04-2021.csv', '03-04-2022.csv', '03-04-2023.csv', '03-05-2020.csv', '03-05-2021.csv', '03-05-2022.csv', '03-05-2023.csv', '03-06-2020.csv', '03-06-2021.csv', '03-06-2022.csv', '03-06-2023.csv', '03-07-2020.csv', '03-07-2021.csv', '03-07-2022.csv', '03-07-2023.csv', '03-08-2020.csv', '03-08-2021.csv', '03-08-2022.csv', '03-08-2023.csv', '03-09-2020.csv', '03-09-2021.csv', '03-09-2022.csv', '03-09-2023.csv', '03-10-2020.csv', '03-10-2021.csv', '03-10-2022.csv', '03-11-2020.csv', '03-11-2021.csv', '03-11-2022.csv', '03-12-2020.csv', '03-12-2021.csv', '03-12-2022.csv', '03-13-2020.csv', '03-13-2021.csv', '03-13-2022.csv', '03-14-2020.csv', '03-14-2021.csv', '03-14-2022.csv', '03-15-2020.csv', '03-15-2021.csv', '03-15-2022.csv', '03-16-2020.csv', '03-16-2021.csv', '03-16-2022.csv', '03-17-2020.csv', '03-17-2021.csv', '03-17-2022.csv', '03-18-2020.csv', '03-18-2021.csv', '03-18-2022.csv', '03-19-2020.csv', '03-19-2021.csv', '03-19-2022.csv', '03-20-2020.csv', '03-20-2021.csv', '03-20-2022.csv', '03-21-2020.csv', '03-21-2021.csv', '03-21-2022.csv', '03-22-2020.csv', '03-22-2021.csv', '03-22-2022.csv', '03-23-2020.csv', '03-23-2021.csv', '03-23-2022.csv', '03-24-2020.csv', '03-24-2021.csv', '03-24-2022.csv', '03-25-2020.csv', '03-25-2021.csv', '03-25-2022.csv', '03-26-2020.csv', '03-26-2021.csv', '03-26-2022.csv', '03-27-2020.csv', '03-27-2021.csv', '03-27-2022.csv', '03-28-2020.csv', '03-28-2021.csv', '03-28-2022.csv', '03-29-2020.csv', '03-29-2021.csv', '03-29-2022.csv', '03-30-2020.csv', '03-30-2021.csv', '03-30-2022.csv', '03-31-2020.csv', '03-31-2021.csv', '03-31-2022.csv', '04-01-2020.csv', '04-01-2021.csv', '04-01-2022.csv', '04-02-2020.csv', '04-02-2021.csv', '04-02-2022.csv', '04-03-2020.csv', '04-03-2021.csv', '04-03-2022.csv', '04-04-2020.csv', '04-04-2021.csv', '04-04-2022.csv', '04-05-2020.csv', '04-05-2021.csv', '04-05-2022.csv', '04-06-2020.csv', '04-06-2021.csv', '04-06-2022.csv', '04-07-2020.csv', '04-07-2021.csv', '04-07-2022.csv', '04-08-2020.csv', '04-08-2021.csv', '04-08-2022.csv', '04-09-2020.csv', '04-09-2021.csv', '04-09-2022.csv', '04-10-2020.csv', '04-10-2021.csv', '04-10-2022.csv', '04-11-2020.csv', '04-11-2021.csv', '04-11-2022.csv', '04-12-2020.csv', '04-12-2021.csv', '04-12-2022.csv', '04-13-2020.csv', '04-13-2021.csv', '04-13-2022.csv', '04-14-2020.csv', '04-14-2021.csv', '04-14-2022.csv', '04-15-2020.csv', '04-15-2021.csv', '04-15-2022.csv', '04-16-2020.csv', '04-16-2021.csv', '04-16-2022.csv', '04-17-2020.csv', '04-17-2021.csv', '04-17-2022.csv', '04-18-2020.csv', '04-18-2021.csv', '04-18-2022.csv', '04-19-2020.csv', '04-19-2021.csv', '04-19-2022.csv', '04-20-2020.csv', '04-20-2021.csv', '04-20-2022.csv', '04-21-2020.csv', '04-21-2021.csv', '04-21-2022.csv', '04-22-2020.csv', '04-22-2021.csv', '04-22-2022.csv', '04-23-2020.csv', '04-23-2021.csv', '04-23-2022.csv', '04-24-2020.csv', '04-24-2021.csv', '04-24-2022.csv', '04-25-2020.csv', '04-25-2021.csv', '04-25-2022.csv', '04-26-2020.csv', '04-26-2021.csv', '04-26-2022.csv', '04-27-2020.csv', '04-27-2021.csv', '04-27-2022.csv', '04-28-2020.csv', '04-28-2021.csv', '04-28-2022.csv', '04-29-2020.csv', '04-29-2021.csv', '04-29-2022.csv', '04-30-2020.csv', '04-30-2021.csv', '04-30-2022.csv', '05-01-2020.csv', '05-01-2021.csv', '05-01-2022.csv', '05-02-2020.csv', '05-02-2021.csv', '05-02-2022.csv', '05-03-2020.csv', '05-03-2021.csv', '05-03-2022.csv', '05-04-2020.csv', '05-04-2021.csv', '05-04-2022.csv', '05-05-2020.csv', '05-05-2021.csv', '05-05-2022.csv', '05-06-2020.csv', '05-06-2021.csv', '05-06-2022.csv', '05-07-2020.csv', '05-07-2021.csv', '05-07-2022.csv', '05-08-2020.csv', '05-08-2021.csv', '05-08-2022.csv', '05-09-2020.csv', '05-09-2021.csv', '05-09-2022.csv', '05-10-2020.csv', '05-10-2021.csv', '05-10-2022.csv', '05-11-2020.csv', '05-11-2021.csv', '05-11-2022.csv', '05-12-2020.csv', '05-12-2021.csv', '05-12-2022.csv', '05-13-2020.csv', '05-13-2021.csv', '05-13-2022.csv', '05-14-2020.csv', '05-14-2021.csv', '05-14-2022.csv', '05-15-2020.csv', '05-15-2021.csv', '05-15-2022.csv', '05-16-2020.csv', '05-16-2021.csv', '05-16-2022.csv', '05-17-2020.csv', '05-17-2021.csv', '05-17-2022.csv', '05-18-2020.csv', '05-18-2021.csv', '05-18-2022.csv', '05-19-2020.csv', '05-19-2021.csv', '05-19-2022.csv', '05-20-2020.csv', '05-20-2021.csv', '05-20-2022.csv', '05-21-2020.csv', '05-21-2021.csv', '05-21-2022.csv', '05-22-2020.csv', '05-22-2021.csv', '05-22-2022.csv', '05-23-2020.csv', '05-23-2021.csv', '05-23-2022.csv', '05-24-2020.csv', '05-24-2021.csv', '05-24-2022.csv', '05-25-2020.csv', '05-25-2021.csv', '05-25-2022.csv', '05-26-2020.csv', '05-26-2021.csv', '05-26-2022.csv', '05-27-2020.csv', '05-27-2021.csv', '05-27-2022.csv', '05-28-2020.csv', '05-28-2021.csv', '05-28-2022.csv', '05-29-2020.csv', '05-29-2021.csv', '05-29-2022.csv', '05-30-2020.csv', '05-30-2021.csv', '05-30-2022.csv', '05-31-2020.csv', '05-31-2021.csv', '05-31-2022.csv', '06-01-2020.csv', '06-01-2021.csv', '06-01-2022.csv', '06-02-2020.csv', '06-02-2021.csv', '06-02-2022.csv', '06-03-2020.csv', '06-03-2021.csv', '06-03-2022.csv', '06-04-2020.csv', '06-04-2021.csv', '06-04-2022.csv', '06-05-2020.csv', '06-05-2021.csv', '06-05-2022.csv', '06-06-2020.csv', '06-06-2021.csv', '06-06-2022.csv', '06-07-2020.csv', '06-07-2021.csv', '06-07-2022.csv', '06-08-2020.csv', '06-08-2021.csv', '06-08-2022.csv', '06-09-2020.csv', '06-09-2021.csv', '06-09-2022.csv', '06-10-2020.csv', '06-10-2021.csv', '06-10-2022.csv', '06-11-2020.csv', '06-11-2021.csv', '06-11-2022.csv', '06-12-2020.csv', '06-12-2021.csv', '06-12-2022.csv', '06-13-2020.csv', '06-13-2021.csv', '06-13-2022.csv', '06-14-2020.csv', '06-14-2021.csv', '06-14-2022.csv', '06-15-2020.csv', '06-15-2021.csv', '06-15-2022.csv', '06-16-2020.csv', '06-16-2021.csv', '06-16-2022.csv', '06-17-2020.csv', '06-17-2021.csv', '06-17-2022.csv', '06-18-2020.csv', '06-18-2021.csv', '06-18-2022.csv', '06-19-2020.csv', '06-19-2021.csv', '06-19-2022.csv', '06-20-2020.csv', '06-20-2021.csv', '06-20-2022.csv', '06-21-2020.csv', '06-21-2021.csv', '06-21-2022.csv', '06-22-2020.csv', '06-22-2021.csv', '06-22-2022.csv', '06-23-2020.csv', '06-23-2021.csv', '06-23-2022.csv', '06-24-2020.csv', '06-24-2021.csv', '06-24-2022.csv', '06-25-2020.csv', '06-25-2021.csv', '06-25-2022.csv', '06-26-2020.csv', '06-26-2021.csv', '06-26-2022.csv', '06-27-2020.csv', '06-27-2021.csv', '06-27-2022.csv', '06-28-2020.csv', '06-28-2021.csv', '06-28-2022.csv', '06-29-2020.csv', '06-29-2021.csv', '06-29-2022.csv', '06-30-2020.csv', '06-30-2021.csv', '06-30-2022.csv', '07-01-2020.csv', '07-01-2021.csv', '07-01-2022.csv', '07-02-2020.csv', '07-02-2021.csv', '07-02-2022.csv', '07-03-2020.csv', '07-03-2021.csv', '07-03-2022.csv', '07-04-2020.csv', '07-04-2021.csv', '07-04-2022.csv', '07-05-2020.csv', '07-05-2021.csv', '07-05-2022.csv', '07-06-2020.csv', '07-06-2021.csv', '07-06-2022.csv', '07-07-2020.csv', '07-07-2021.csv', '07-07-2022.csv', '07-08-2020.csv', '07-08-2021.csv', '07-08-2022.csv', '07-09-2020.csv', '07-09-2021.csv', '07-09-2022.csv', '07-10-2020.csv', '07-10-2021.csv', '07-10-2022.csv', '07-11-2020.csv', '07-11-2021.csv', '07-11-2022.csv', '07-12-2020.csv', '07-12-2021.csv', '07-12-2022.csv', '07-13-2020.csv', '07-13-2021.csv', '07-13-2022.csv', '07-14-2020.csv', '07-14-2021.csv', '07-14-2022.csv', '07-15-2020.csv', '07-15-2021.csv', '07-15-2022.csv', '07-16-2020.csv', '07-16-2021.csv', '07-16-2022.csv', '07-17-2020.csv', '07-17-2021.csv', '07-17-2022.csv', '07-18-2020.csv', '07-18-2021.csv', '07-18-2022.csv', '07-19-2020.csv', '07-19-2021.csv', '07-19-2022.csv', '07-20-2020.csv', '07-20-2021.csv', '07-20-2022.csv', '07-21-2020.csv', '07-21-2021.csv', '07-21-2022.csv', '07-22-2020.csv', '07-22-2021.csv', '07-22-2022.csv', '07-23-2020.csv', '07-23-2021.csv', '07-23-2022.csv', '07-24-2020.csv', '07-24-2021.csv', '07-24-2022.csv', '07-25-2020.csv', '07-25-2021.csv', '07-25-2022.csv', '07-26-2020.csv', '07-26-2021.csv', '07-26-2022.csv', '07-27-2020.csv', '07-27-2021.csv', '07-27-2022.csv', '07-28-2020.csv', '07-28-2021.csv', '07-28-2022.csv', '07-29-2020.csv', '07-29-2021.csv', '07-29-2022.csv', '07-30-2020.csv', '07-30-2021.csv', '07-30-2022.csv', '07-31-2020.csv', '07-31-2021.csv', '07-31-2022.csv', '08-01-2020.csv', '08-01-2021.csv', '08-01-2022.csv', '08-02-2020.csv', '08-02-2021.csv', '08-02-2022.csv', '08-03-2020.csv', '08-03-2021.csv', '08-03-2022.csv', '08-04-2020.csv', '08-04-2021.csv', '08-04-2022.csv', '08-05-2020.csv', '08-05-2021.csv', '08-05-2022.csv', '08-06-2020.csv', '08-06-2021.csv', '08-06-2022.csv', '08-07-2020.csv', '08-07-2021.csv', '08-07-2022.csv', '08-08-2020.csv', '08-08-2021.csv', '08-08-2022.csv', '08-09-2020.csv', '08-09-2021.csv', '08-09-2022.csv', '08-10-2020.csv', '08-10-2021.csv', '08-10-2022.csv', '08-11-2020.csv', '08-11-2021.csv', '08-11-2022.csv', '08-12-2020.csv', '08-12-2021.csv', '08-12-2022.csv', '08-13-2020.csv', '08-13-2021.csv', '08-13-2022.csv', '08-14-2020.csv', '08-14-2021.csv', '08-14-2022.csv', '08-15-2020.csv', '08-15-2021.csv', '08-15-2022.csv', '08-16-2020.csv', '08-16-2021.csv', '08-16-2022.csv', '08-17-2020.csv', '08-17-2021.csv', '08-17-2022.csv', '08-18-2020.csv', '08-18-2021.csv', '08-18-2022.csv', '08-19-2020.csv', '08-19-2021.csv', '08-19-2022.csv', '08-20-2020.csv', '08-20-2021.csv', '08-20-2022.csv', '08-21-2020.csv', '08-21-2021.csv', '08-21-2022.csv', '08-22-2020.csv', '08-22-2021.csv', '08-22-2022.csv', '08-23-2020.csv', '08-23-2021.csv', '08-23-2022.csv', '08-24-2020.csv', '08-24-2021.csv', '08-24-2022.csv', '08-25-2020.csv', '08-25-2021.csv', '08-25-2022.csv', '08-26-2020.csv', '08-26-2021.csv', '08-26-2022.csv', '08-27-2020.csv', '08-27-2021.csv', '08-27-2022.csv', '08-28-2020.csv', '08-28-2021.csv', '08-28-2022.csv', '08-29-2020.csv', '08-29-2021.csv', '08-29-2022.csv', '08-30-2020.csv', '08-30-2021.csv', '08-30-2022.csv', '08-31-2020.csv', '08-31-2021.csv', '08-31-2022.csv', '09-01-2020.csv', '09-01-2021.csv', '09-01-2022.csv', '09-02-2020.csv', '09-02-2021.csv', '09-02-2022.csv', '09-03-2020.csv', '09-03-2021.csv', '09-03-2022.csv', '09-04-2020.csv', '09-04-2021.csv', '09-04-2022.csv', '09-05-2020.csv', '09-05-2021.csv', '09-05-2022.csv', '09-06-2020.csv', '09-06-2021.csv', '09-06-2022.csv', '09-07-2020.csv', '09-07-2021.csv', '09-07-2022.csv', '09-08-2020.csv', '09-08-2021.csv', '09-08-2022.csv', '09-09-2020.csv', '09-09-2021.csv', '09-09-2022.csv', '09-10-2020.csv', '09-10-2021.csv', '09-10-2022.csv', '09-11-2020.csv', '09-11-2021.csv', '09-11-2022.csv', '09-12-2020.csv', '09-12-2021.csv', '09-12-2022.csv', '09-13-2020.csv', '09-13-2021.csv', '09-13-2022.csv', '09-14-2020.csv', '09-14-2021.csv', '09-14-2022.csv', '09-15-2020.csv', '09-15-2021.csv', '09-15-2022.csv', '09-16-2020.csv', '09-16-2021.csv', '09-16-2022.csv', '09-17-2020.csv', '09-17-2021.csv', '09-17-2022.csv', '09-18-2020.csv', '09-18-2021.csv', '09-18-2022.csv', '09-19-2020.csv', '09-19-2021.csv', '09-19-2022.csv', '09-20-2020.csv', '09-20-2021.csv', '09-20-2022.csv', '09-21-2020.csv', '09-21-2021.csv', '09-21-2022.csv', '09-22-2020.csv', '09-22-2021.csv', '09-22-2022.csv', '09-23-2020.csv', '09-23-2021.csv', '09-23-2022.csv', '09-24-2020.csv', '09-24-2021.csv', '09-24-2022.csv', '09-25-2020.csv', '09-25-2021.csv', '09-25-2022.csv', '09-26-2020.csv', '09-26-2021.csv', '09-26-2022.csv', '09-27-2020.csv', '09-27-2021.csv', '09-27-2022.csv', '09-28-2020.csv', '09-28-2021.csv', '09-28-2022.csv', '09-29-2020.csv', '09-29-2021.csv', '09-29-2022.csv', '09-30-2020.csv', '09-30-2021.csv', '09-30-2022.csv', '10-01-2020.csv', '10-01-2021.csv', '10-01-2022.csv', '10-02-2020.csv', '10-02-2021.csv', '10-02-2022.csv', '10-03-2020.csv', '10-03-2021.csv', '10-03-2022.csv', '10-04-2020.csv', '10-04-2021.csv', '10-04-2022.csv', '10-05-2020.csv', '10-05-2021.csv', '10-05-2022.csv', '10-06-2020.csv', '10-06-2021.csv', '10-06-2022.csv', '10-07-2020.csv', '10-07-2021.csv', '10-07-2022.csv', '10-08-2020.csv', '10-08-2021.csv', '10-08-2022.csv', '10-09-2020.csv', '10-09-2021.csv', '10-09-2022.csv', '10-10-2020.csv', '10-10-2021.csv', '10-10-2022.csv', '10-11-2020.csv', '10-11-2021.csv', '10-11-2022.csv', '10-12-2020.csv', '10-12-2021.csv', '10-12-2022.csv', '10-13-2020.csv', '10-13-2021.csv', '10-13-2022.csv', '10-14-2020.csv', '10-14-2021.csv', '10-14-2022.csv', '10-15-2020.csv', '10-15-2021.csv', '10-15-2022.csv', '10-16-2020.csv', '10-16-2021.csv', '10-16-2022.csv', '10-17-2020.csv', '10-17-2021.csv', '10-17-2022.csv', '10-18-2020.csv', '10-18-2021.csv', '10-18-2022.csv', '10-19-2020.csv', '10-19-2021.csv', '10-19-2022.csv', '10-20-2020.csv', '10-20-2021.csv', '10-20-2022.csv', '10-21-2020.csv', '10-21-2021.csv', '10-21-2022.csv', '10-22-2020.csv', '10-22-2021.csv', '10-22-2022.csv', '10-23-2020.csv', '10-23-2021.csv', '10-23-2022.csv', '10-24-2020.csv', '10-24-2021.csv', '10-24-2022.csv', '10-25-2020.csv', '10-25-2021.csv', '10-25-2022.csv', '10-26-2020.csv', '10-26-2021.csv', '10-26-2022.csv', '10-27-2020.csv', '10-27-2021.csv', '10-27-2022.csv', '10-28-2020.csv', '10-28-2021.csv', '10-28-2022.csv', '10-29-2020.csv', '10-29-2021.csv', '10-29-2022.csv', '10-30-2020.csv', '10-30-2021.csv', '10-30-2022.csv', '10-31-2020.csv', '10-31-2021.csv', '10-31-2022.csv', '11-01-2020.csv', '11-01-2021.csv', '11-01-2022.csv', '11-02-2020.csv', '11-02-2021.csv', '11-02-2022.csv', '11-03-2020.csv', '11-03-2021.csv', '11-03-2022.csv', '11-04-2020.csv', '11-04-2021.csv', '11-04-2022.csv', '11-05-2020.csv', '11-05-2021.csv', '11-05-2022.csv', '11-06-2020.csv', '11-06-2021.csv', '11-06-2022.csv', '11-07-2020.csv', '11-07-2021.csv', '11-07-2022.csv', '11-08-2020.csv', '11-08-2021.csv', '11-08-2022.csv', '11-09-2020.csv', '11-09-2021.csv', '11-09-2022.csv', '11-10-2020.csv', '11-10-2021.csv', '11-10-2022.csv', '11-11-2020.csv', '11-11-2021.csv', '11-11-2022.csv', '11-12-2020.csv', '11-12-2021.csv', '11-12-2022.csv', '11-13-2020.csv', '11-13-2021.csv', '11-13-2022.csv', '11-14-2020.csv', '11-14-2021.csv', '11-14-2022.csv', '11-15-2020.csv', '11-15-2021.csv', '11-15-2022.csv', '11-16-2020.csv', '11-16-2021.csv', '11-16-2022.csv', '11-17-2020.csv', '11-17-2021.csv', '11-17-2022.csv', '11-18-2020.csv', '11-18-2021.csv', '11-18-2022.csv', '11-19-2020.csv', '11-19-2021.csv', '11-19-2022.csv', '11-20-2020.csv', '11-20-2021.csv', '11-20-2022.csv', '11-21-2020.csv', '11-21-2021.csv', '11-21-2022.csv', '11-22-2020.csv', '11-22-2021.csv', '11-22-2022.csv', '11-23-2020.csv', '11-23-2021.csv', '11-23-2022.csv', '11-24-2020.csv', '11-24-2021.csv', '11-24-2022.csv', '11-25-2020.csv', '11-25-2021.csv', '11-25-2022.csv', '11-26-2020.csv', '11-26-2021.csv', '11-26-2022.csv', '11-27-2020.csv', '11-27-2021.csv', '11-27-2022.csv', '11-28-2020.csv', '11-28-2021.csv', '11-28-2022.csv', '11-29-2020.csv', '11-29-2021.csv', '11-29-2022.csv', '11-30-2020.csv', '11-30-2021.csv', '11-30-2022.csv', '12-01-2020.csv', '12-01-2021.csv', '12-01-2022.csv', '12-02-2020.csv', '12-02-2021.csv', '12-02-2022.csv', '12-03-2020.csv', '12-03-2021.csv', '12-03-2022.csv', '12-04-2020.csv', '12-04-2021.csv', '12-04-2022.csv', '12-05-2020.csv', '12-05-2021.csv', '12-05-2022.csv', '12-06-2020.csv', '12-06-2021.csv', '12-06-2022.csv', '12-07-2020.csv', '12-07-2021.csv', '12-07-2022.csv', '12-08-2020.csv', '12-08-2021.csv', '12-08-2022.csv', '12-09-2020.csv', '12-09-2021.csv', '12-09-2022.csv', '12-10-2020.csv', '12-10-2021.csv', '12-10-2022.csv', '12-11-2020.csv', '12-11-2021.csv', '12-11-2022.csv', '12-12-2020.csv', '12-12-2021.csv', '12-12-2022.csv', '12-13-2020.csv', '12-13-2021.csv', '12-13-2022.csv', '12-14-2020.csv', '12-14-2021.csv', '12-14-2022.csv', '12-15-2020.csv', '12-15-2021.csv', '12-15-2022.csv', '12-16-2020.csv', '12-16-2021.csv', '12-16-2022.csv', '12-17-2020.csv', '12-17-2021.csv', '12-17-2022.csv', '12-18-2020.csv', '12-18-2021.csv', '12-18-2022.csv', '12-19-2020.csv', '12-19-2021.csv', '12-19-2022.csv', '12-20-2020.csv', '12-20-2021.csv', '12-20-2022.csv', '12-21-2020.csv', '

In [63]:
from datetime import datetime

# 날짜처럼 생긴 문자 -> 해당 문자를 진짜 날짜로 바꿔줘야 함 -> 가장 오래된 날짜부터 가장 최신 날짜로 인식하여 정렬해줘야 함
# 람다 식 = 메서드 안에 어떤 기능을 구현할 수 있는 함수를 또 사용해야 하는 경우
# 자바스크립트(Javascript)라는 프로그래밍 언어에서는 함수를 1급 시민이라고 함.
    # 함수 안에 함수를 사용하는 걸 콜백이라고 함
    # 함수 안에 return문 안에 함수를 사용할 수 있음
    # 함수의 매개변수 = 인자값으로 함수를 쓸 수 있음
# 하지만 파이썬은 안 됨. 함수의 기능을 구현할 수 있는 메서드 안에 또 다른 기능 구현을 위한 함수를 사용하고 싶으면 lambda식을 써야 함
    # 함수의 구문이 식으로 바뀐다는 것은 결국, 함수의 이름을 포기하겠다는 것이며, 한줄짜리 식으로 사용하겠다는 것임
# 람다식 = 익명함수 라고도 부름

csv_list.sort(key = lambda x : datetime.strptime(x, "%m-%d-%Y.csv")) ## strptime 문자로 생긴 매개변수를 어떠한 포맷타입으로 바꿀건지 지정

In [64]:
csv_list

['01-22-2020.csv',
 '01-23-2020.csv',
 '01-24-2020.csv',
 '01-25-2020.csv',
 '01-26-2020.csv',
 '01-27-2020.csv',
 '01-28-2020.csv',
 '01-29-2020.csv',
 '01-30-2020.csv',
 '01-31-2020.csv',
 '02-01-2020.csv',
 '02-02-2020.csv',
 '02-03-2020.csv',
 '02-04-2020.csv',
 '02-05-2020.csv',
 '02-06-2020.csv',
 '02-07-2020.csv',
 '02-08-2020.csv',
 '02-09-2020.csv',
 '02-10-2020.csv',
 '02-11-2020.csv',
 '02-12-2020.csv',
 '02-13-2020.csv',
 '02-14-2020.csv',
 '02-15-2020.csv',
 '02-16-2020.csv',
 '02-17-2020.csv',
 '02-18-2020.csv',
 '02-19-2020.csv',
 '02-20-2020.csv',
 '02-21-2020.csv',
 '02-22-2020.csv',
 '02-23-2020.csv',
 '02-24-2020.csv',
 '02-25-2020.csv',
 '02-26-2020.csv',
 '02-27-2020.csv',
 '02-28-2020.csv',
 '02-29-2020.csv',
 '03-01-2020.csv',
 '03-02-2020.csv',
 '03-03-2020.csv',
 '03-04-2020.csv',
 '03-05-2020.csv',
 '03-06-2020.csv',
 '03-07-2020.csv',
 '03-08-2020.csv',
 '03-09-2020.csv',
 '03-10-2020.csv',
 '03-11-2020.csv',
 '03-12-2020.csv',
 '03-13-2020.csv',
 '03-14-2020.csv',
 '03-15-2020.csv',
 '03-16-2020.csv',
 '03-17-2020.csv',
 '03-18-2020.csv',
 '03-19-2020.csv',
 '03-20-2020.csv',
 '03-21-2020.csv',
 '03-22-2020.csv',
 '03-23-2020.csv',
 '03-24-2020.csv',
 '03-25-2020.csv',
 '03-26-2020.csv',
 '03-27-2020.csv',
 '03-28-2020.csv',
 '03-29-2020.csv',
 '03-30-2020.csv',
 '03-31-2020.csv',
 '04-01-2020.csv',
 '04-02-2020.csv',
 '04-03-2020.csv',
 '04-04-2020.csv',
 '04-05-2020.csv',
 '04-06-2020.csv',
 '04-07-2020.csv',
 '04-08-2020.csv',
 '04-09-2020.csv',
 '04-10-2020.csv',
 '04-11-2020.csv',
 '04-12-2020.csv',
 '04-13-2020.csv',
 '04-14-2020.csv',
 '04-15-2020.csv',
 '04-16-2020.csv',
 '04-17-2020.csv',
 '04-18-2020.csv',
 '04-19-2020.csv',
 '04-20-2020.csv',
 '04-21-2020.csv',
 '04-22-2020.csv',
 '04-23-2020.csv',
 '04-24-2020.csv',
 '04-25-2020.csv',
 '04-26-2020.csv',
 '04-27-2020.csv',
 '04-28-2020.csv',
 '04-29-2020.csv',
 '04-30-2020.csv',
 '05-01-2020.csv',
 '05-02-2020.csv',
 '05-03-2020.csv',
 '05-04-2020.csv',
 '05-05-2020.csv',
 '05-06-2020.csv',
 '05-07-2020.csv',
 '05-08-2020.csv',
 '05-09-2020.csv',
 '05-10-2020.csv',
 '05-11-2020.csv',
 '05-12-2020.csv',
 '05-13-2020.csv',
 '05-14-2020.csv',
 '05-15-2020.csv',
 '05-16-2020.csv',
 '05-17-2020.csv',
 '05-18-2020.csv',
 '05-19-2020.csv',
 '05-20-2020.csv',
 '05-21-2020.csv',
 '05-22-2020.csv',
 '05-23-2020.csv',
 '05-24-2020.csv',
 '05-25-2020.csv',
 '05-26-2020.csv',
 '05-27-2020.csv',
 '05-28-2020.csv',
 '05-29-2020.csv',
 '05-30-2020.csv',
 '05-31-2020.csv',
 '06-01-2020.csv',
 '06-02-2020.csv',
 '06-03-2020.csv',
 '06-04-2020.csv',
 '06-05-2020.csv',
 '06-06-2020.csv',
 '06-07-2020.csv',
 '06-08-2020.csv',
 '06-09-2020.csv',
 '06-10-2020.csv',
 '06-11-2020.csv',
 '06-12-2020.csv',
 '06-13-2020.csv',
 '06-14-2020.csv',
 '06-15-2020.csv',
 '06-16-2020.csv',
 '06-17-2020.csv',
 '06-18-2020.csv',
 '06-19-2020.csv',
 '06-20-2020.csv',
 '06-21-2020.csv',
 '06-22-2020.csv',
 '06-23-2020.csv',
 '06-24-2020.csv',
 '06-25-2020.csv',
 '06-26-2020.csv',
 '06-27-2020.csv',
 '06-28-2020.csv',
 '06-29-2020.csv',
 '06-30-2020.csv',
 '07-01-2020.csv',
 '07-02-2020.csv',
 '07-03-2020.csv',
 '07-04-2020.csv',
 '07-05-2020.csv',
 '07-06-2020.csv',
 '07-07-2020.csv',
 '07-08-2020.csv',
 '07-09-2020.csv',
 '07-10-2020.csv',
 '07-11-2020.csv',
 '07-12-2020.csv',
 '07-13-2020.csv',
 '07-14-2020.csv',
 '07-15-2020.csv',
 '07-16-2020.csv',
 '07-17-2020.csv',
 '07-18-2020.csv',
 '07-19-2020.csv',
 '07-20-2020.csv',
 '07-21-2020.csv',
 '07-22-2020.csv',
 '07-23-2020.csv',
 '07-24-2020.csv',
 '07-25-2020.csv',
 '07-26-2020.csv',
 '07-27-2020.csv',
 '07-28-2020.csv',
 '07-29-2020.csv',
 '07-30-2020.csv',
 '07-31-2020.csv',
 '08-01-2020.csv',
 '08-02-2020.csv',
 '08-03-2020.csv',
 '08-04-2020.csv',
 '08-05-2020.csv',
 '08-06-2020.csv',
 '08-07-2020.csv',
 '08-08-2020.csv',
 '08-09-2020.csv',
 '08-10-2020.csv',
 '08-11-2020.csv',
 '08-12-2020.csv',
 '08-13-2020.csv',
 '08-14-2020.csv',
 '08-15-2020.csv',
 '08-16-2020.csv',
 '08-17-2020.csv',
 '08-18-2020.csv',
 '08-19-2020.csv',
 '08-20-2020.csv',
 '08-21-2020.csv',
 '08-22-2020.csv',
 '08-23-2020.csv',
 '08-24-2020.csv',
 '08-25-2020.csv',
 '08-26-2020.csv',
 '08-27-2020.csv',
 '08-28-2020.csv',
 '08-29-2020.csv',
 '08-30-2020.csv',
 '08-31-2020.csv',
 '09-01-2020.csv',
 '09-02-2020.csv',
 '09-03-2020.csv',
 '09-04-2020.csv',
 '09-05-2020.csv',
 '09-06-2020.csv',
 '09-07-2020.csv',
 '09-08-2020.csv',
 '09-09-2020.csv',
 '09-10-2020.csv',
 '09-11-2020.csv',
 '09-12-2020.csv',
 '09-13-2020.csv',
 '09-14-2020.csv',
 '09-15-2020.csv',
 '09-16-2020.csv',
 '09-17-2020.csv',
 '09-18-2020.csv',
 '09-19-2020.csv',
 '09-20-2020.csv',
 '09-21-2020.csv',
 '09-22-2020.csv',
 '09-23-2020.csv',
 '09-24-2020.csv',
 '09-25-2020.csv',
 '09-26-2020.csv',
 '09-27-2020.csv',
 '09-28-2020.csv',
 '09-29-2020.csv',
 '09-30-2020.csv',
 '10-01-2020.csv',
 '10-02-2020.csv',
 '10-03-2020.csv',
 '10-04-2020.csv',
 '10-05-2020.csv',
 '10-06-2020.csv',
 '10-07-2020.csv',
 '10-08-2020.csv',
 '10-09-2020.csv',
 '10-10-2020.csv',
 '10-11-2020.csv',
 '10-12-2020.csv',
 '10-13-2020.csv',
 '10-14-2020.csv',
 '10-15-2020.csv',
 '10-16-2020.csv',
 '10-17-2020.csv',
 '10-18-2020.csv',
 '10-19-2020.csv',
 '10-20-2020.csv',
 '10-21-2020.csv',
 '10-22-2020.csv',
 '10-23-2020.csv',
 '10-24-2020.csv',
 '10-25-2020.csv',
 '10-26-2020.csv',
 '10-27-2020.csv',
 '10-28-2020.csv',
 '10-29-2020.csv',
 '10-30-2020.csv',
 '10-31-2020.csv',
 '11-01-2020.csv',
 '11-02-2020.csv',
 '11-03-2020.csv',
 '11-04-2020.csv',
 '11-05-2020.csv',
 '11-06-2020.csv',
 '11-07-2020.csv',
 '11-08-2020.csv',
 '11-09-2020.csv',
 '11-10-2020.csv',
 '11-11-2020.csv',
 '11-12-2020.csv',
 '11-13-2020.csv',
 '11-14-2020.csv',
 '11-15-2020.csv',
 '11-16-2020.csv',
 '11-17-2020.csv',
 '11-18-2020.csv',
 '11-19-2020.csv',
 '11-20-2020.csv',
 '11-21-2020.csv',
 '11-22-2020.csv',
 '11-23-2020.csv',
 '11-24-2020.csv',
 '11-25-2020.csv',
 '11-26-2020.csv',
 '11-27-2020.csv',
 '11-28-2020.csv',
 '11-29-2020.csv',
 '11-30-2020.csv',
 '12-01-2020.csv',
 '12-02-2020.csv',
 '12-03-2020.csv',
 '12-04-2020.csv',
 '12-05-2020.csv',
 '12-06-2020.csv',
 '12-07-2020.csv',
 '12-08-2020.csv',
 '12-09-2020.csv',
 '12-10-2020.csv',
 '12-11-2020.csv',
 '12-12-2020.csv',
 '12-13-2020.csv',
 '12-14-2020.csv',
 '12-15-2020.csv',
 '12-16-2020.csv',
 '12-17-2020.csv',
 '12-18-2020.csv',
 '12-19-2020.csv',
 '12-20-2020.csv',
 '12-21-2020.csv',
 '12-22-2020.csv',
 '12-23-2020.csv',
 '12-24-2020.csv',
 '12-25-2020.csv',
 '12-26-2020.csv',
 '12-27-2020.csv',
 '12-28-2020.csv',
 '12-29-2020.csv',
 '12-30-2020.csv',
 '12-31-2020.csv',
 '01-01-2021.csv',
 '01-02-2021.csv',
 '01-03-2021.csv',
 '01-04-2021.csv',
 '01-05-2021.csv',
 '01-06-2021.csv',
 '01-07-2021.csv',
 '01-08-2021.csv',
 '01-09-2021.csv',
 '01-10-2021.csv',
 '01-11-2021.csv',
 '01-12-2021.csv',
 '01-13-2021.csv',
 '01-14-2021.csv',
 '01-15-2021.csv',
 '01-16-2021.csv',
 '01-17-2021.csv',
 '01-18-2021.csv',
 '01-19-2021.csv',
 '01-20-2021.csv',
 '01-21-2021.csv',
 '01-22-2021.csv',
 '01-23-2021.csv',
 '01-24-2021.csv',
 '01-25-2021.csv',
 '01-26-2021.csv',
 '01-27-2021.csv',
 '01-28-2021.csv',
 '01-29-2021.csv',
 '01-30-2021.csv',
 '01-31-2021.csv',
 '02-01-2021.csv',
 '02-02-2021.csv',
 '02-03-2021.csv',
 '02-04-2021.csv',
 '02-05-2021.csv',
 '02-06-2021.csv',
 '02-07-2021.csv',
 '02-08-2021.csv',
 '02-09-2021.csv',
 '02-10-2021.csv',
 '02-11-2021.csv',
 '02-12-2021.csv',
 '02-13-2021.csv',
 '02-14-2021.csv',
 '02-15-2021.csv',
 '02-16-2021.csv',
 '02-17-2021.csv',
 '02-18-2021.csv',
 '02-19-2021.csv',
 '02-20-2021.csv',
 '02-21-2021.csv',
 '02-22-2021.csv',
 '02-23-2021.csv',
 '02-24-2021.csv',
 '02-25-2021.csv',
 '02-26-2021.csv',
 '02-27-2021.csv',
 '02-28-2021.csv',
 '03-01-2021.csv',
 '03-02-2021.csv',
 '03-03-2021.csv',
 '03-04-2021.csv',
 '03-05-2021.csv',
 '03-06-2021.csv',
 '03-07-2021.csv',
 '03-08-2021.csv',
 '03-09-2021.csv',
 '03-10-2021.csv',
 '03-11-2021.csv',
 '03-12-2021.csv',
 '03-13-2021.csv',
 '03-14-2021.csv',
 '03-15-2021.csv',
 '03-16-2021.csv',
 '03-17-2021.csv',
 '03-18-2021.csv',
 '03-19-2021.csv',
 '03-20-2021.csv',
 '03-21-2021.csv',
 '03-22-2021.csv',
 '03-23-2021.csv',
 '03-24-2021.csv',
 '03-25-2021.csv',
 '03-26-2021.csv',
 '03-27-2021.csv',
 '03-28-2021.csv',
 '03-29-2021.csv',
 '03-30-2021.csv',
 '03-31-2021.csv',
 '04-01-2021.csv',
 '04-02-2021.csv',
 '04-03-2021.csv',
 '04-04-2021.csv',
 '04-05-2021.csv',
 '04-06-2021.csv',
 '04-07-2021.csv',
 '04-08-2021.csv',
 '04-09-2021.csv',
 '04-10-2021.csv',
 '04-11-2021.csv',
 '04-12-2021.csv',
 '04-13-2021.csv',
 '04-14-2021.csv',
 '04-15-2021.csv',
 '04-16-2021.csv',
 '04-17-2021.csv',
 '04-18-2021.csv',
 '04-19-2021.csv',
 '04-20-2021.csv',
 '04-21-2021.csv',
 '04-22-2021.csv',
 '04-23-2021.csv',
 '04-24-2021.csv',
 '04-25-2021.csv',
 '04-26-2021.csv',
 '04-27-2021.csv',
 '04-28-2021.csv',
 '04-29-2021.csv',
 '04-30-2021.csv',
 '05-01-2021.csv',
 '05-02-2021.csv',
 '05-03-2021.csv',
 '05-04-2021.csv',
 '05-05-2021.csv',
 '05-06-2021.csv',
 '05-07-2021.csv',
 '05-08-2021.csv',
 '05-09-2021.csv',
 '05-10-2021.csv',
 '05-11-2021.csv',
 '05-12-2021.csv',
 '05-13-2021.csv',
 '05-14-2021.csv',
 '05-15-2021.csv',
 '05-16-2021.csv',
 '05-17-2021.csv',
 '05-18-2021.csv',
 '05-19-2021.csv',
 '05-20-2021.csv',
 '05-21-2021.csv',
 '05-22-2021.csv',
 '05-23-2021.csv',
 '05-24-2021.csv',
 '05-25-2021.csv',
 '05-26-2021.csv',
 '05-27-2021.csv',
 '05-28-2021.csv',
 '05-29-2021.csv',
 '05-30-2021.csv',
 '05-31-2021.csv',
 '06-01-2021.csv',
 '06-02-2021.csv',
 '06-03-2021.csv',
 '06-04-2021.csv',
 '06-05-2021.csv',
 '06-06-2021.csv',
 '06-07-2021.csv',
 '06-08-2021.csv',
 '06-09-2021.csv',
 '06-10-2021.csv',
 '06-11-2021.csv',
 '06-12-2021.csv',
 '06-13-2021.csv',
 '06-14-2021.csv',
 '06-15-2021.csv',
 '06-16-2021.csv',
 '06-17-2021.csv',
 '06-18-2021.csv',
 '06-19-2021.csv',
 '06-20-2021.csv',
 '06-21-2021.csv',
 '06-22-2021.csv',
 '06-23-2021.csv',
 '06-24-2021.csv',
 '06-25-2021.csv',
 '06-26-2021.csv',
 '06-27-2021.csv',
 '06-28-2021.csv',
 '06-29-2021.csv',
 '06-30-2021.csv',
 '07-01-2021.csv',
 '07-02-2021.csv',
 '07-03-2021.csv',
 '07-04-2021.csv',
 '07-05-2021.csv',
 '07-06-2021.csv',
 '07-07-2021.csv',
 '07-08-2021.csv',
 '07-09-2021.csv',
 '07-10-2021.csv',
 '07-11-2021.csv',
 '07-12-2021.csv',
 '07-13-2021.csv',
 '07-14-2021.csv',
 '07-15-2021.csv',
 '07-16-2021.csv',
 '07-17-2021.csv',
 '07-18-2021.csv',
 '07-19-2021.csv',
 '07-20-2021.csv',
 '07-21-2021.csv',
 '07-22-2021.csv',
 '07-23-2021.csv',
 '07-24-2021.csv',
 '07-25-2021.csv',
 '07-26-2021.csv',
 '07-27-2021.csv',
 '07-28-2021.csv',
 '07-29-2021.csv',
 '07-30-2021.csv',
 '07-31-2021.csv',
 '08-01-2021.csv',
 '08-02-2021.csv',
 '08-03-2021.csv',
 '08-04-2021.csv',
 '08-05-2021.csv',
 '08-06-2021.csv',
 '08-07-2021.csv',
 '08-08-2021.csv',
 '08-09-2021.csv',
 '08-10-2021.csv',
 '08-11-2021.csv',
 '08-12-2021.csv',
 '08-13-2021.csv',
 '08-14-2021.csv',
 '08-15-2021.csv',
 '08-16-2021.csv',
 '08-17-2021.csv',
 '08-18-2021.csv',
 '08-19-2021.csv',
 '08-20-2021.csv',
 '08-21-2021.csv',
 '08-22-2021.csv',
 '08-23-2021.csv',
 '08-24-2021.csv',
 '08-25-2021.csv',
 '08-26-2021.csv',
 '08-27-2021.csv',
 '08-28-2021.csv',
 '08-29-2021.csv',
 '08-30-2021.csv',
 '08-31-2021.csv',
 '09-01-2021.csv',
 '09-02-2021.csv',
 '09-03-2021.csv',
 '09-04-2021.csv',
 '09-05-2021.csv',
 '09-06-2021.csv',
 '09-07-2021.csv',
 '09-08-2021.csv',
 '09-09-2021.csv',
 '09-10-2021.csv',
 '09-11-2021.csv',
 '09-12-2021.csv',
 '09-13-2021.csv',
 '09-14-2021.csv',
 '09-15-2021.csv',
 '09-16-2021.csv',
 '09-17-2021.csv',
 '09-18-2021.csv',
 '09-19-2021.csv',
 '09-20-2021.csv',
 '09-21-2021.csv',
 '09-22-2021.csv',
 '09-23-2021.csv',
 '09-24-2021.csv',
 '09-25-2021.csv',
 '09-26-2021.csv',
 '09-27-2021.csv',
 '09-28-2021.csv',
 '09-29-2021.csv',
 '09-30-2021.csv',
 '10-01-2021.csv',
 '10-02-2021.csv',
 '10-03-2021.csv',
 '10-04-2021.csv',
 '10-05-2021.csv',
 '10-06-2021.csv',
 '10-07-2021.csv',
 '10-08-2021.csv',
 '10-09-2021.csv',
 '10-10-2021.csv',
 '10-11-2021.csv',
 '10-12-2021.csv',
 '10-13-2021.csv',
 '10-14-2021.csv',
 '10-15-2021.csv',
 '10-16-2021.csv',
 '10-17-2021.csv',
 '10-18-2021.csv',
 '10-19-2021.csv',
 '10-20-2021.csv',
 '10-21-2021.csv',
 '10-22-2021.csv',
 '10-23-2021.csv',
 '10-24-2021.csv',
 '10-25-2021.csv',
 '10-26-2021.csv',
 '10-27-2021.csv',
 '10-28-2021.csv',
 '10-29-2021.csv',
 '10-30-2021.csv',
 '10-31-2021.csv',
 '11-01-2021.csv',
 '11-02-2021.csv',
 '11-03-2021.csv',
 '11-04-2021.csv',
 '11-05-2021.csv',
 '11-06-2021.csv',
 '11-07-2021.csv',
 '11-08-2021.csv',
 '11-09-2021.csv',
 '11-10-2021.csv',
 '11-11-2021.csv',
 '11-12-2021.csv',
 '11-13-2021.csv',
 '11-14-2021.csv',
 '11-15-2021.csv',
 '11-16-2021.csv',
 '11-17-2021.csv',
 '11-18-2021.csv',
 '11-19-2021.csv',
 '11-20-2021.csv',
 '11-21-2021.csv',
 '11-22-2021.csv',
 '11-23-2021.csv',
 '11-24-2021.csv',
 '11-25-2021.csv',
 '11-26-2021.csv',
 '11-27-2021.csv',
 '11-28-2021.csv',
 '11-29-2021.csv',
 '11-30-2021.csv',
 '12-01-2021.csv',
 '12-02-2021.csv',
 '12-03-2021.csv',
 '12-04-2021.csv',
 '12-05-2021.csv',
 '12-06-2021.csv',
 '12-07-2021.csv',
 '12-08-2021.csv',
 '12-09-2021.csv',
 '12-10-2021.csv',
 '12-11-2021.csv',
 '12-12-2021.csv',
 '12-13-2021.csv',
 '12-14-2021.csv',
 '12-15-2021.csv',
 '12-16-2021.csv',
 '12-17-2021.csv',
 '12-18-2021.csv',
 '12-19-2021.csv',
 '12-20-2021.csv',
 '12-21-2021.csv',
 '12-22-2021.csv',
 '12-23-2021.csv',
 '12-24-2021.csv',
 '12-25-2021.csv',
 '12-26-2021.csv',
 '12-27-2021.csv',
 '12-28-2021.csv',
 '12-29-2021.csv',
 '12-30-2021.csv',
 '12-31-2021.csv',
 '01-01-2022.csv',
 '01-02-2022.csv',
 '01-03-2022.csv',
 '01-04-2022.csv',
 '01-05-2022.csv',
 '01-06-2022.csv',
 '01-07-2022.csv',
 '01-08-2022.csv',
 '01-09-2022.csv',
 '01-10-2022.csv',
 '01-11-2022.csv',
 '01-12-2022.csv',
 '01-13-2022.csv',
 '01-14-2022.csv',
 '01-15-2022.csv',
 '01-16-2022.csv',
 '01-17-2022.csv',
 '01-18-2022.csv',
 '01-19-2022.csv',
 '01-20-2022.csv',
 '01-21-2022.csv',
 '01-22-2022.csv',
 '01-23-2022.csv',
 '01-24-2022.csv',
 '01-25-2022.csv',
 '01-26-2022.csv',
 '01-27-2022.csv',
 '01-28-2022.csv',
 '01-29-2022.csv',
 '01-30-2022.csv',
 '01-31-2022.csv',
 '02-01-2022.csv',
 '02-02-2022.csv',
 '02-03-2022.csv',
 '02-04-2022.csv',
 '02-05-2022.csv',
 '02-06-2022.csv',
 '02-07-2022.csv',
 '02-08-2022.csv',
 '02-09-2022.csv',
 '02-10-2022.csv',
 '02-11-2022.csv',
 '02-12-2022.csv',
 '02-13-2022.csv',
 '02-14-2022.csv',
 '02-15-2022.csv',
 '02-16-2022.csv',
 '02-17-2022.csv',
 '02-18-2022.csv',
 '02-19-2022.csv',
 '02-20-2022.csv',
 '02-21-2022.csv',
 '02-22-2022.csv',
 '02-23-2022.csv',
 '02-24-2022.csv',
 '02-25-2022.csv',
 '02-26-2022.csv',
 '02-27-2022.csv',
 '02-28-2022.csv',
 '03-01-2022.csv',
 '03-02-2022.csv',
 '03-03-2022.csv',
 '03-04-2022.csv',
 '03-05-2022.csv',
 '03-06-2022.csv',
 '03-07-2022.csv',
 '03-08-2022.csv',
 '03-09-2022.csv',
 '03-10-2022.csv',
 '03-11-2022.csv',
 '03-12-2022.csv',
 '03-13-2022.csv',
 '03-14-2022.csv',
 '03-15-2022.csv',
 '03-16-2022.csv',
 '03-17-2022.csv',
 '03-18-2022.csv',
 '03-19-2022.csv',
 '03-20-2022.csv',
 '03-21-2022.csv',
 '03-22-2022.csv',
 '03-23-2022.csv',
 '03-24-2022.csv',
 '03-25-2022.csv',
 '03-26-2022.csv',
 '03-27-2022.csv',
 '03-28-2022.csv',
 '03-29-2022.csv',
 '03-30-2022.csv',
 '03-31-2022.csv',
 '04-01-2022.csv',
 '04-02-2022.csv',
 '04-03-2022.csv',
 '04-04-2022.csv',
 '04-05-2022.csv',
 '04-06-2022.csv',
 '04-07-2022.csv',
 '04-08-2022.csv',
 '04-09-2022.csv',
 '04-10-2022.csv',
 '04-11-2022.csv',
 '04-12-2022.csv',
 '04-13-2022.csv',
 '04-14-2022.csv',
 '04-15-2022.csv',
 '04-16-2022.csv',
 '04-17-2022.csv',
 '04-18-2022.csv',
 '04-19-2022.csv',
 '04-20-2022.csv',
 '04-21-2022.csv',
 '04-22-2022.csv',
 '04-23-2022.csv',
 '04-24-2022.csv',
 '04-25-2022.csv',
 '04-26-2022.csv',
 '04-27-2022.csv',
 '04-28-2022.csv',
 '04-29-2022.csv',
 '04-30-2022.csv',
 '05-01-2022.csv',
 '05-02-2022.csv',
 '05-03-2022.csv',
 '05-04-2022.csv',
 '05-05-2022.csv',
 '05-06-2022.csv',
 '05-07-2022.csv',
 '05-08-2022.csv',
 '05-09-2022.csv',
 '05-10-2022.csv',
 '05-11-2022.csv',
 '05-12-2022.csv',
 '05-13-2022.csv',
 '05-14-2022.csv',
 '05-15-2022.csv',
 '05-16-2022.csv',
 '05-17-2022.csv',
 '05-18-2022.csv',
 '05-19-2022.csv',
 '05-20-2022.csv',
 '05-21-2022.csv',
 '05-22-2022.csv',
 '05-23-2022.csv',
 '05-24-2022.csv',
 '05-25-2022.csv',
 '05-26-2022.csv',
 '05-27-2022.csv',
 '05-28-2022.csv',
 '05-29-2022.csv',
 '05-30-2022.csv',
 '05-31-2022.csv',
 '06-01-2022.csv',
 '06-02-2022.csv',
 '06-03-2022.csv',
 '06-04-2022.csv',
 '06-05-2022.csv',
 '06-06-2022.csv',
 '06-07-2022.csv',
 '06-08-2022.csv',
 '06-09-2022.csv',
 '06-10-2022.csv',
 '06-11-2022.csv',
 '06-12-2022.csv',
 '06-13-2022.csv',
 '06-14-2022.csv',
 '06-15-2022.csv',
 '06-16-2022.csv',
 '06-17-2022.csv',
 '06-18-2022.csv',
 '06-19-2022.csv',
 '06-20-2022.csv',
 '06-21-2022.csv',
 '06-22-2022.csv',
 '06-23-2022.csv',
 '06-24-2022.csv',
 '06-25-2022.csv',
 '06-26-2022.csv',
 '06-27-2022.csv',
 '06-28-2022.csv',
 '06-29-2022.csv',
 '06-30-2022.csv',
 '07-01-2022.csv',
 '07-02-2022.csv',
 '07-03-2022.csv',
 '07-04-2022.csv',
 '07-05-2022.csv',
 '07-06-2022.csv',
 '07-07-2022.csv',
 '07-08-2022.csv',
 '07-09-2022.csv',
 '07-10-2022.csv',
 '07-11-2022.csv',
 '07-12-2022.csv',
 '07-13-2022.csv',
 '07-14-2022.csv',
 '07-15-2022.csv',
 '07-16-2022.csv',
 '07-17-2022.csv',
 '07-18-2022.csv',
 '07-19-2022.csv',
 '07-20-2022.csv',
 '07-21-2022.csv',
 '07-22-2022.csv',
 '07-23-2022.csv',
 '07-24-2022.csv',
 '07-25-2022.csv',
 '07-26-2022.csv',
 '07-27-2022.csv',
 '07-28-2022.csv',
 '07-29-2022.csv',
 '07-30-2022.csv',
 '07-31-2022.csv',
 '08-01-2022.csv',
 '08-02-2022.csv',
 '08-03-2022.csv',
 '08-04-2022.csv',
 '08-05-2022.csv',
 '08-06-2022.csv',
 '08-07-2022.csv',
 '08-08-2022.csv',
 '08-09-2022.csv',
 '08-10-2022.csv',
 '08-11-2022.csv',
 '08-12-2022.csv',
 '08-13-2022.csv',
 '08-14-2022.csv',
 '08-15-2022.csv',
 '08-16-2022.csv',
 '08-17-2022.csv',
 '08-18-2022.csv',
 '08-19-2022.csv',
 '08-20-2022.csv',
 '08-21-2022.csv',
 '08-22-2022.csv',
 '08-23-2022.csv',
 '08-24-2022.csv',
 '08-25-2022.csv',
 '08-26-2022.csv',
 '08-27-2022.csv',
 '08-28-2022.csv',
 '08-29-2022.csv',
 '08-30-2022.csv',
 '08-31-2022.csv',
 '09-01-2022.csv',
 '09-02-2022.csv',
 '09-03-2022.csv',
 '09-04-2022.csv',
 '09-05-2022.csv',
 '09-06-2022.csv',
 '09-07-2022.csv',
 '09-08-2022.csv',
 '09-09-2022.csv',
 '09-10-2022.csv',
 '09-11-2022.csv',
 '09-12-2022.csv',
 '09-13-2022.csv',
 '09-14-2022.csv',
 '09-15-2022.csv',
 '09-16-2022.csv',
 '09-17-2022.csv',
 '09-18-2022.csv',
 '09-19-2022.csv',
 '09-20-2022.csv',
 '09-21-2022.csv',
 '09-22-2022.csv',
 '09-23-2022.csv',
 '09-24-2022.csv',
 '09-25-2022.csv',
 '09-26-2022.csv',
 '09-27-2022.csv',
 '09-28-2022.csv',
 '09-29-2022.csv',
 '09-30-2022.csv',
 '10-01-2022.csv',
 '10-02-2022.csv',
 '10-03-2022.csv',
 '10-04-2022.csv',
 '10-05-2022.csv',
 '10-06-2022.csv',
 '10-07-2022.csv',
 '10-08-2022.csv',
 '10-09-2022.csv',
 '10-10-2022.csv',
 '10-11-2022.csv',
 '10-12-2022.csv',
 '10-13-2022.csv',
 '10-14-2022.csv',
 '10-15-2022.csv',
 '10-16-2022.csv',
 '10-17-2022.csv',
 ...]

In [65]:
csv_list.sort(reverse = True)

In [66]:
csv_list

['12-31-2022.csv',
 '12-31-2021.csv',
 '12-31-2020.csv',
 '12-30-2022.csv',
 '12-30-2021.csv',
 '12-30-2020.csv',
 '12-29-2022.csv',
 '12-29-2021.csv',
 '12-29-2020.csv',
 '12-28-2022.csv',
 '12-28-2021.csv',
 '12-28-2020.csv',
 '12-27-2022.csv',
 '12-27-2021.csv',
 '12-27-2020.csv',
 '12-26-2022.csv',
 '12-26-2021.csv',
 '12-26-2020.csv',
 '12-25-2022.csv',
 '12-25-2021.csv',
 '12-25-2020.csv',
 '12-24-2022.csv',
 '12-24-2021.csv',
 '12-24-2020.csv',
 '12-23-2022.csv',
 '12-23-2021.csv',
 '12-23-2020.csv',
 '12-22-2022.csv',
 '12-22-2021.csv',
 '12-22-2020.csv',
 '12-21-2022.csv',
 '12-21-2021.csv',
 '12-21-2020.csv',
 '12-20-2022.csv',
 '12-20-2021.csv',
 '12-20-2020.csv',
 '12-19-2022.csv',
 '12-19-2021.csv',
 '12-19-2020.csv',
 '12-18-2022.csv',
 '12-18-2021.csv',
 '12-18-2020.csv',
 '12-17-2022.csv',
 '12-17-2021.csv',
 '12-17-2020.csv',
 '12-16-2022.csv',
 '12-16-2021.csv',
 '12-16-2020.csv',
 '12-15-2022.csv',
 '12-15-2021.csv',
 '12-15-2020.csv',
 '12-14-2022.csv',
 '12-14-2021.csv',
 '12-14-2020.csv',
 '12-13-2022.csv',
 '12-13-2021.csv',
 '12-13-2020.csv',
 '12-12-2022.csv',
 '12-12-2021.csv',
 '12-12-2020.csv',
 '12-11-2022.csv',
 '12-11-2021.csv',
 '12-11-2020.csv',
 '12-10-2022.csv',
 '12-10-2021.csv',
 '12-10-2020.csv',
 '12-09-2022.csv',
 '12-09-2021.csv',
 '12-09-2020.csv',
 '12-08-2022.csv',
 '12-08-2021.csv',
 '12-08-2020.csv',
 '12-07-2022.csv',
 '12-07-2021.csv',
 '12-07-2020.csv',
 '12-06-2022.csv',
 '12-06-2021.csv',
 '12-06-2020.csv',
 '12-05-2022.csv',
 '12-05-2021.csv',
 '12-05-2020.csv',
 '12-04-2022.csv',
 '12-04-2021.csv',
 '12-04-2020.csv',
 '12-03-2022.csv',
 '12-03-2021.csv',
 '12-03-2020.csv',
 '12-02-2022.csv',
 '12-02-2021.csv',
 '12-02-2020.csv',
 '12-01-2022.csv',
 '12-01-2021.csv',
 '12-01-2020.csv',
 '11-30-2022.csv',
 '11-30-2021.csv',
 '11-30-2020.csv',
 '11-29-2022.csv',
 '11-29-2021.csv',
 '11-29-2020.csv',
 '11-28-2022.csv',
 '11-28-2021.csv',
 '11-28-2020.csv',
 '11-27-2022.csv',
 '11-27-2021.csv',
 '11-27-2020.csv',
 '11-26-2022.csv',
 '11-26-2021.csv',
 '11-26-2020.csv',
 '11-25-2022.csv',
 '11-25-2021.csv',
 '11-25-2020.csv',
 '11-24-2022.csv',
 '11-24-2021.csv',
 '11-24-2020.csv',
 '11-23-2022.csv',
 '11-23-2021.csv',
 '11-23-2020.csv',
 '11-22-2022.csv',
 '11-22-2021.csv',
 '11-22-2020.csv',
 '11-21-2022.csv',
 '11-21-2021.csv',
 '11-21-2020.csv',
 '11-20-2022.csv',
 '11-20-2021.csv',
 '11-20-2020.csv',
 '11-19-2022.csv',
 '11-19-2021.csv',
 '11-19-2020.csv',
 '11-18-2022.csv',
 '11-18-2021.csv',
 '11-18-2020.csv',
 '11-17-2022.csv',
 '11-17-2021.csv',
 '11-17-2020.csv',
 '11-16-2022.csv',
 '11-16-2021.csv',
 '11-16-2020.csv',
 '11-15-2022.csv',
 '11-15-2021.csv',
 '11-15-2020.csv',
 '11-14-2022.csv',
 '11-14-2021.csv',
 '11-14-2020.csv',
 '11-13-2022.csv',
 '11-13-2021.csv',
 '11-13-2020.csv',
 '11-12-2022.csv',
 '11-12-2021.csv',
 '11-12-2020.csv',
 '11-11-2022.csv',
 '11-11-2021.csv',
 '11-11-2020.csv',
 '11-10-2022.csv',
 '11-10-2021.csv',
 '11-10-2020.csv',
 '11-09-2022.csv',
 '11-09-2021.csv',
 '11-09-2020.csv',
 '11-08-2022.csv',
 '11-08-2021.csv',
 '11-08-2020.csv',
 '11-07-2022.csv',
 '11-07-2021.csv',
 '11-07-2020.csv',
 '11-06-2022.csv',
 '11-06-2021.csv',
 '11-06-2020.csv',
 '11-05-2022.csv',
 '11-05-2021.csv',
 '11-05-2020.csv',
 '11-04-2022.csv',
 '11-04-2021.csv',
 '11-04-2020.csv',
 '11-03-2022.csv',
 '11-03-2021.csv',
 '11-03-2020.csv',
 '11-02-2022.csv',
 '11-02-2021.csv',
 '11-02-2020.csv',
 '11-01-2022.csv',
 '11-01-2021.csv',
 '11-01-2020.csv',
 '10-31-2022.csv',
 '10-31-2021.csv',
 '10-31-2020.csv',
 '10-30-2022.csv',
 '10-30-2021.csv',
 '10-30-2020.csv',
 '10-29-2022.csv',
 '10-29-2021.csv',
 '10-29-2020.csv',
 '10-28-2022.csv',
 '10-28-2021.csv',
 '10-28-2020.csv',
 '10-27-2022.csv',
 '10-27-2021.csv',
 '10-27-2020.csv',
 '10-26-2022.csv',
 '10-26-2021.csv',
 '10-26-2020.csv',
 '10-25-2022.csv',
 '10-25-2021.csv',
 '10-25-2020.csv',
 '10-24-2022.csv',
 '10-24-2021.csv',
 '10-24-2020.csv',
 '10-23-2022.csv',
 '10-23-2021.csv',
 '10-23-2020.csv',
 '10-22-2022.csv',
 '10-22-2021.csv',
 '10-22-2020.csv',
 '10-21-2022.csv',
 '10-21-2021.csv',
 '10-21-2020.csv',
 '10-20-2022.csv',
 '10-20-2021.csv',
 '10-20-2020.csv',
 '10-19-2022.csv',
 '10-19-2021.csv',
 '10-19-2020.csv',
 '10-18-2022.csv',
 '10-18-2021.csv',
 '10-18-2020.csv',
 '10-17-2022.csv',
 '10-17-2021.csv',
 '10-17-2020.csv',
 '10-16-2022.csv',
 '10-16-2021.csv',
 '10-16-2020.csv',
 '10-15-2022.csv',
 '10-15-2021.csv',
 '10-15-2020.csv',
 '10-14-2022.csv',
 '10-14-2021.csv',
 '10-14-2020.csv',
 '10-13-2022.csv',
 '10-13-2021.csv',
 '10-13-2020.csv',
 '10-12-2022.csv',
 '10-12-2021.csv',
 '10-12-2020.csv',
 '10-11-2022.csv',
 '10-11-2021.csv',
 '10-11-2020.csv',
 '10-10-2022.csv',
 '10-10-2021.csv',
 '10-10-2020.csv',
 '10-09-2022.csv',
 '10-09-2021.csv',
 '10-09-2020.csv',
 '10-08-2022.csv',
 '10-08-2021.csv',
 '10-08-2020.csv',
 '10-07-2022.csv',
 '10-07-2021.csv',
 '10-07-2020.csv',
 '10-06-2022.csv',
 '10-06-2021.csv',
 '10-06-2020.csv',
 '10-05-2022.csv',
 '10-05-2021.csv',
 '10-05-2020.csv',
 '10-04-2022.csv',
 '10-04-2021.csv',
 '10-04-2020.csv',
 '10-03-2022.csv',
 '10-03-2021.csv',
 '10-03-2020.csv',
 '10-02-2022.csv',
 '10-02-2021.csv',
 '10-02-2020.csv',
 '10-01-2022.csv',
 '10-01-2021.csv',
 '10-01-2020.csv',
 '09-30-2022.csv',
 '09-30-2021.csv',
 '09-30-2020.csv',
 '09-29-2022.csv',
 '09-29-2021.csv',
 '09-29-2020.csv',
 '09-28-2022.csv',
 '09-28-2021.csv',
 '09-28-2020.csv',
 '09-27-2022.csv',
 '09-27-2021.csv',
 '09-27-2020.csv',
 '09-26-2022.csv',
 '09-26-2021.csv',
 '09-26-2020.csv',
 '09-25-2022.csv',
 '09-25-2021.csv',
 '09-25-2020.csv',
 '09-24-2022.csv',
 '09-24-2021.csv',
 '09-24-2020.csv',
 '09-23-2022.csv',
 '09-23-2021.csv',
 '09-23-2020.csv',
 '09-22-2022.csv',
 '09-22-2021.csv',
 '09-22-2020.csv',
 '09-21-2022.csv',
 '09-21-2021.csv',
 '09-21-2020.csv',
 '09-20-2022.csv',
 '09-20-2021.csv',
 '09-20-2020.csv',
 '09-19-2022.csv',
 '09-19-2021.csv',
 '09-19-2020.csv',
 '09-18-2022.csv',
 '09-18-2021.csv',
 '09-18-2020.csv',
 '09-17-2022.csv',
 '09-17-2021.csv',
 '09-17-2020.csv',
 '09-16-2022.csv',
 '09-16-2021.csv',
 '09-16-2020.csv',
 '09-15-2022.csv',
 '09-15-2021.csv',
 '09-15-2020.csv',
 '09-14-2022.csv',
 '09-14-2021.csv',
 '09-14-2020.csv',
 '09-13-2022.csv',
 '09-13-2021.csv',
 '09-13-2020.csv',
 '09-12-2022.csv',
 '09-12-2021.csv',
 '09-12-2020.csv',
 '09-11-2022.csv',
 '09-11-2021.csv',
 '09-11-2020.csv',
 '09-10-2022.csv',
 '09-10-2021.csv',
 '09-10-2020.csv',
 '09-09-2022.csv',
 '09-09-2021.csv',
 '09-09-2020.csv',
 '09-08-2022.csv',
 '09-08-2021.csv',
 '09-08-2020.csv',
 '09-07-2022.csv',
 '09-07-2021.csv',
 '09-07-2020.csv',
 '09-06-2022.csv',
 '09-06-2021.csv',
 '09-06-2020.csv',
 '09-05-2022.csv',
 '09-05-2021.csv',
 '09-05-2020.csv',
 '09-04-2022.csv',
 '09-04-2021.csv',
 '09-04-2020.csv',
 '09-03-2022.csv',
 '09-03-2021.csv',
 '09-03-2020.csv',
 '09-02-2022.csv',
 '09-02-2021.csv',
 '09-02-2020.csv',
 '09-01-2022.csv',
 '09-01-2021.csv',
 '09-01-2020.csv',
 '08-31-2022.csv',
 '08-31-2021.csv',
 '08-31-2020.csv',
 '08-30-2022.csv',
 '08-30-2021.csv',
 '08-30-2020.csv',
 '08-29-2022.csv',
 '08-29-2021.csv',
 '08-29-2020.csv',
 '08-28-2022.csv',
 '08-28-2021.csv',
 '08-28-2020.csv',
 '08-27-2022.csv',
 '08-27-2021.csv',
 '08-27-2020.csv',
 '08-26-2022.csv',
 '08-26-2021.csv',
 '08-26-2020.csv',
 '08-25-2022.csv',
 '08-25-2021.csv',
 '08-25-2020.csv',
 '08-24-2022.csv',
 '08-24-2021.csv',
 '08-24-2020.csv',
 '08-23-2022.csv',
 '08-23-2021.csv',
 '08-23-2020.csv',
 '08-22-2022.csv',
 '08-22-2021.csv',
 '08-22-2020.csv',
 '08-21-2022.csv',
 '08-21-2021.csv',
 '08-21-2020.csv',
 '08-20-2022.csv',
 '08-20-2021.csv',
 '08-20-2020.csv',
 '08-19-2022.csv',
 '08-19-2021.csv',
 '08-19-2020.csv',
 '08-18-2022.csv',
 '08-18-2021.csv',
 '08-18-2020.csv',
 '08-17-2022.csv',
 '08-17-2021.csv',
 '08-17-2020.csv',
 '08-16-2022.csv',
 '08-16-2021.csv',
 '08-16-2020.csv',
 '08-15-2022.csv',
 '08-15-2021.csv',
 '08-15-2020.csv',
 '08-14-2022.csv',
 '08-14-2021.csv',
 '08-14-2020.csv',
 '08-13-2022.csv',
 '08-13-2021.csv',
 '08-13-2020.csv',
 '08-12-2022.csv',
 '08-12-2021.csv',
 '08-12-2020.csv',
 '08-11-2022.csv',
 '08-11-2021.csv',
 '08-11-2020.csv',
 '08-10-2022.csv',
 '08-10-2021.csv',
 '08-10-2020.csv',
 '08-09-2022.csv',
 '08-09-2021.csv',
 '08-09-2020.csv',
 '08-08-2022.csv',
 '08-08-2021.csv',
 '08-08-2020.csv',
 '08-07-2022.csv',
 '08-07-2021.csv',
 '08-07-2020.csv',
 '08-06-2022.csv',
 '08-06-2021.csv',
 '08-06-2020.csv',
 '08-05-2022.csv',
 '08-05-2021.csv',
 '08-05-2020.csv',
 '08-04-2022.csv',
 '08-04-2021.csv',
 '08-04-2020.csv',
 '08-03-2022.csv',
 '08-03-2021.csv',
 '08-03-2020.csv',
 '08-02-2022.csv',
 '08-02-2021.csv',
 '08-02-2020.csv',
 '08-01-2022.csv',
 '08-01-2021.csv',
 '08-01-2020.csv',
 '07-31-2022.csv',
 '07-31-2021.csv',
 '07-31-2020.csv',
 '07-30-2022.csv',
 '07-30-2021.csv',
 '07-30-2020.csv',
 '07-29-2022.csv',
 '07-29-2021.csv',
 '07-29-2020.csv',
 '07-28-2022.csv',
 '07-28-2021.csv',
 '07-28-2020.csv',
 '07-27-2022.csv',
 '07-27-2021.csv',
 '07-27-2020.csv',
 '07-26-2022.csv',
 '07-26-2021.csv',
 '07-26-2020.csv',
 '07-25-2022.csv',
 '07-25-2021.csv',
 '07-25-2020.csv',
 '07-24-2022.csv',
 '07-24-2021.csv',
 '07-24-2020.csv',
 '07-23-2022.csv',
 '07-23-2021.csv',
 '07-23-2020.csv',
 '07-22-2022.csv',
 '07-22-2021.csv',
 '07-22-2020.csv',
 '07-21-2022.csv',
 '07-21-2021.csv',
 '07-21-2020.csv',
 '07-20-2022.csv',
 '07-20-2021.csv',
 '07-20-2020.csv',
 '07-19-2022.csv',
 '07-19-2021.csv',
 '07-19-2020.csv',
 '07-18-2022.csv',
 '07-18-2021.csv',
 '07-18-2020.csv',
 '07-17-2022.csv',
 '07-17-2021.csv',
 '07-17-2020.csv',
 '07-16-2022.csv',
 '07-16-2021.csv',
 '07-16-2020.csv',
 '07-15-2022.csv',
 '07-15-2021.csv',
 '07-15-2020.csv',
 '07-14-2022.csv',
 '07-14-2021.csv',
 '07-14-2020.csv',
 '07-13-2022.csv',
 '07-13-2021.csv',
 '07-13-2020.csv',
 '07-12-2022.csv',
 '07-12-2021.csv',
 '07-12-2020.csv',
 '07-11-2022.csv',
 '07-11-2021.csv',
 '07-11-2020.csv',
 '07-10-2022.csv',
 '07-10-2021.csv',
 '07-10-2020.csv',
 '07-09-2022.csv',
 '07-09-2021.csv',
 '07-09-2020.csv',
 '07-08-2022.csv',
 '07-08-2021.csv',
 '07-08-2020.csv',
 '07-07-2022.csv',
 '07-07-2021.csv',
 '07-07-2020.csv',
 '07-06-2022.csv',
 '07-06-2021.csv',
 '07-06-2020.csv',
 '07-05-2022.csv',
 '07-05-2021.csv',
 '07-05-2020.csv',
 '07-04-2022.csv',
 '07-04-2021.csv',
 '07-04-2020.csv',
 '07-03-2022.csv',
 '07-03-2021.csv',
 '07-03-2020.csv',
 '07-02-2022.csv',
 '07-02-2021.csv',
 '07-02-2020.csv',
 '07-01-2022.csv',
 '07-01-2021.csv',
 '07-01-2020.csv',
 '06-30-2022.csv',
 '06-30-2021.csv',
 '06-30-2020.csv',
 '06-29-2022.csv',
 '06-29-2021.csv',
 '06-29-2020.csv',
 '06-28-2022.csv',
 '06-28-2021.csv',
 '06-28-2020.csv',
 '06-27-2022.csv',
 '06-27-2021.csv',
 '06-27-2020.csv',
 '06-26-2022.csv',
 '06-26-2021.csv',
 '06-26-2020.csv',
 '06-25-2022.csv',
 '06-25-2021.csv',
 '06-25-2020.csv',
 '06-24-2022.csv',
 '06-24-2021.csv',
 '06-24-2020.csv',
 '06-23-2022.csv',
 '06-23-2021.csv',
 '06-23-2020.csv',
 '06-22-2022.csv',
 '06-22-2021.csv',
 '06-22-2020.csv',
 '06-21-2022.csv',
 '06-21-2021.csv',
 '06-21-2020.csv',
 '06-20-2022.csv',
 '06-20-2021.csv',
 '06-20-2020.csv',
 '06-19-2022.csv',
 '06-19-2021.csv',
 '06-19-2020.csv',
 '06-18-2022.csv',
 '06-18-2021.csv',
 '06-18-2020.csv',
 '06-17-2022.csv',
 '06-17-2021.csv',
 '06-17-2020.csv',
 '06-16-2022.csv',
 '06-16-2021.csv',
 '06-16-2020.csv',
 '06-15-2022.csv',
 '06-15-2021.csv',
 '06-15-2020.csv',
 '06-14-2022.csv',
 '06-14-2021.csv',
 '06-14-2020.csv',
 '06-13-2022.csv',
 '06-13-2021.csv',
 '06-13-2020.csv',
 '06-12-2022.csv',
 '06-12-2021.csv',
 '06-12-2020.csv',
 '06-11-2022.csv',
 '06-11-2021.csv',
 '06-11-2020.csv',
 '06-10-2022.csv',
 '06-10-2021.csv',
 '06-10-2020.csv',
 '06-09-2022.csv',
 '06-09-2021.csv',
 '06-09-2020.csv',
 '06-08-2022.csv',
 '06-08-2021.csv',
 '06-08-2020.csv',
 '06-07-2022.csv',
 '06-07-2021.csv',
 '06-07-2020.csv',
 '06-06-2022.csv',
 '06-06-2021.csv',
 '06-06-2020.csv',
 '06-05-2022.csv',
 '06-05-2021.csv',
 '06-05-2020.csv',
 '06-04-2022.csv',
 '06-04-2021.csv',
 '06-04-2020.csv',
 '06-03-2022.csv',
 '06-03-2021.csv',
 '06-03-2020.csv',
 '06-02-2022.csv',
 '06-02-2021.csv',
 '06-02-2020.csv',
 '06-01-2022.csv',
 '06-01-2021.csv',
 '06-01-2020.csv',
 '05-31-2022.csv',
 '05-31-2021.csv',
 '05-31-2020.csv',
 '05-30-2022.csv',
 '05-30-2021.csv',
 '05-30-2020.csv',
 '05-29-2022.csv',
 '05-29-2021.csv',
 '05-29-2020.csv',
 '05-28-2022.csv',
 '05-28-2021.csv',
 '05-28-2020.csv',
 '05-27-2022.csv',
 '05-27-2021.csv',
 '05-27-2020.csv',
 '05-26-2022.csv',
 '05-26-2021.csv',
 '05-26-2020.csv',
 '05-25-2022.csv',
 '05-25-2021.csv',
 '05-25-2020.csv',
 '05-24-2022.csv',
 '05-24-2021.csv',
 '05-24-2020.csv',
 '05-23-2022.csv',
 '05-23-2021.csv',
 '05-23-2020.csv',
 '05-22-2022.csv',
 '05-22-2021.csv',
 '05-22-2020.csv',
 '05-21-2022.csv',
 '05-21-2021.csv',
 '05-21-2020.csv',
 '05-20-2022.csv',
 '05-20-2021.csv',
 '05-20-2020.csv',
 '05-19-2022.csv',
 '05-19-2021.csv',
 '05-19-2020.csv',
 '05-18-2022.csv',
 '05-18-2021.csv',
 '05-18-2020.csv',
 '05-17-2022.csv',
 '05-17-2021.csv',
 '05-17-2020.csv',
 '05-16-2022.csv',
 '05-16-2021.csv',
 '05-16-2020.csv',
 '05-15-2022.csv',
 '05-15-2021.csv',
 '05-15-2020.csv',
 '05-14-2022.csv',
 '05-14-2021.csv',
 '05-14-2020.csv',
 '05-13-2022.csv',
 '05-13-2021.csv',
 '05-13-2020.csv',
 '05-12-2022.csv',
 '05-12-2021.csv',
 '05-12-2020.csv',
 '05-11-2022.csv',
 '05-11-2021.csv',
 '05-11-2020.csv',
 '05-10-2022.csv',
 '05-10-2021.csv',
 '05-10-2020.csv',
 '05-09-2022.csv',
 '05-09-2021.csv',
 '05-09-2020.csv',
 '05-08-2022.csv',
 '05-08-2021.csv',
 '05-08-2020.csv',
 '05-07-2022.csv',
 '05-07-2021.csv',
 '05-07-2020.csv',
 '05-06-2022.csv',
 '05-06-2021.csv',
 '05-06-2020.csv',
 '05-05-2022.csv',
 '05-05-2021.csv',
 '05-05-2020.csv',
 '05-04-2022.csv',
 '05-04-2021.csv',
 '05-04-2020.csv',
 '05-03-2022.csv',
 '05-03-2021.csv',
 '05-03-2020.csv',
 '05-02-2022.csv',
 '05-02-2021.csv',
 '05-02-2020.csv',
 '05-01-2022.csv',
 '05-01-2021.csv',
 '05-01-2020.csv',
 '04-30-2022.csv',
 '04-30-2021.csv',
 '04-30-2020.csv',
 '04-29-2022.csv',
 '04-29-2021.csv',
 '04-29-2020.csv',
 '04-28-2022.csv',
 '04-28-2021.csv',
 '04-28-2020.csv',
 '04-27-2022.csv',
 '04-27-2021.csv',
 '04-27-2020.csv',
 '04-26-2022.csv',
 '04-26-2021.csv',
 '04-26-2020.csv',
 '04-25-2022.csv',
 '04-25-2021.csv',
 '04-25-2020.csv',
 '04-24-2022.csv',
 '04-24-2021.csv',
 '04-24-2020.csv',
 '04-23-2022.csv',
 '04-23-2021.csv',
 '04-23-2020.csv',
 '04-22-2022.csv',
 '04-22-2021.csv',
 '04-22-2020.csv',
 '04-21-2022.csv',
 '04-21-2021.csv',
 '04-21-2020.csv',
 '04-20-2022.csv',
 '04-20-2021.csv',
 '04-20-2020.csv',
 '04-19-2022.csv',
 '04-19-2021.csv',
 '04-19-2020.csv',
 '04-18-2022.csv',
 '04-18-2021.csv',
 '04-18-2020.csv',
 '04-17-2022.csv',
 '04-17-2021.csv',
 '04-17-2020.csv',
 '04-16-2022.csv',
 '04-16-2021.csv',
 '04-16-2020.csv',
 '04-15-2022.csv',
 '04-15-2021.csv',
 '04-15-2020.csv',
 '04-14-2022.csv',
 '04-14-2021.csv',
 '04-14-2020.csv',
 '04-13-2022.csv',
 '04-13-2021.csv',
 '04-13-2020.csv',
 '04-12-2022.csv',
 '04-12-2021.csv',
 '04-12-2020.csv',
 '04-11-2022.csv',
 '04-11-2021.csv',
 '04-11-2020.csv',
 '04-10-2022.csv',
 '04-10-2021.csv',
 '04-10-2020.csv',
 '04-09-2022.csv',
 '04-09-2021.csv',
 '04-09-2020.csv',
 '04-08-2022.csv',
 '04-08-2021.csv',
 '04-08-2020.csv',
 '04-07-2022.csv',
 '04-07-2021.csv',
 '04-07-2020.csv',
 '04-06-2022.csv',
 '04-06-2021.csv',
 '04-06-2020.csv',
 '04-05-2022.csv',
 '04-05-2021.csv',
 '04-05-2020.csv',
 '04-04-2022.csv',
 '04-04-2021.csv',
 '04-04-2020.csv',
 '04-03-2022.csv',
 '04-03-2021.csv',
 '04-03-2020.csv',
 '04-02-2022.csv',
 '04-02-2021.csv',
 '04-02-2020.csv',
 '04-01-2022.csv',
 '04-01-2021.csv',
 '04-01-2020.csv',
 '03-31-2022.csv',
 '03-31-2021.csv',
 '03-31-2020.csv',
 '03-30-2022.csv',
 '03-30-2021.csv',
 '03-30-2020.csv',
 '03-29-2022.csv',
 '03-29-2021.csv',
 '03-29-2020.csv',
 '03-28-2022.csv',
 '03-28-2021.csv',
 '03-28-2020.csv',
 '03-27-2022.csv',
 '03-27-2021.csv',
 '03-27-2020.csv',
 '03-26-2022.csv',
 '03-26-2021.csv',
 '03-26-2020.csv',
 '03-25-2022.csv',
 '03-25-2021.csv',
 '03-25-2020.csv',
 '03-24-2022.csv',
 '03-24-2021.csv',
 '03-24-2020.csv',
 '03-23-2022.csv',
 '03-23-2021.csv',
 '03-23-2020.csv',
 '03-22-2022.csv',
 '03-22-2021.csv',
 '03-22-2020.csv',
 '03-21-2022.csv',
 '03-21-2021.csv',
 '03-21-2020.csv',
 '03-20-2022.csv',
 '03-20-2021.csv',
 '03-20-2020.csv',
 '03-19-2022.csv',
 '03-19-2021.csv',
 '03-19-2020.csv',
 '03-18-2022.csv',
 '03-18-2021.csv',
 '03-18-2020.csv',
 '03-17-2022.csv',
 '03-17-2021.csv',
 '03-17-2020.csv',
 '03-16-2022.csv',
 '03-16-2021.csv',
 '03-16-2020.csv',
 '03-15-2022.csv',
 '03-15-2021.csv',
 '03-15-2020.csv',
 '03-14-2022.csv',
 '03-14-2021.csv',
 '03-14-2020.csv',
 '03-13-2022.csv',
 '03-13-2021.csv',
 '03-13-2020.csv',
 '03-12-2022.csv',
 '03-12-2021.csv',
 '03-12-2020.csv',
 '03-11-2022.csv',
 '03-11-2021.csv',
 '03-11-2020.csv',
 '03-10-2022.csv',
 '03-10-2021.csv',
 '03-10-2020.csv',
 '03-09-2023.csv',
 '03-09-2022.csv',
 '03-09-2021.csv',
 '03-09-2020.csv',
 '03-08-2023.csv',
 '03-08-2022.csv',
 '03-08-2021.csv',
 '03-08-2020.csv',
 '03-07-2023.csv',
 '03-07-2022.csv',
 '03-07-2021.csv',
 '03-07-2020.csv',
 '03-06-2023.csv',
 '03-06-2022.csv',
 '03-06-2021.csv',
 '03-06-2020.csv',
 '03-05-2023.csv',
 '03-05-2022.csv',
 '03-05-2021.csv',
 '03-05-2020.csv',
 '03-04-2023.csv',
 '03-04-2022.csv',
 '03-04-2021.csv',
 '03-04-2020.csv',
 '03-03-2023.csv',
 '03-03-2022.csv',
 '03-03-2021.csv',
 '03-03-2020.csv',
 '03-02-2023.csv',
 '03-02-2022.csv',
 '03-02-2021.csv',
 '03-02-2020.csv',
 '03-01-2023.csv',
 '03-01-2022.csv',
 '03-01-2021.csv',
 '03-01-2020.csv',
 '02-29-2020.csv',
 '02-28-2023.csv',
 '02-28-2022.csv',
 '02-28-2021.csv',
 '02-28-2020.csv',
 '02-27-2023.csv',
 '02-27-2022.csv',
 '02-27-2021.csv',
 '02-27-2020.csv',
 '02-26-2023.csv',
 '02-26-2022.csv',
 '02-26-2021.csv',
 '02-26-2020.csv',
 '02-25-2023.csv',
 '02-25-2022.csv',
 '02-25-2021.csv',
 '02-25-2020.csv',
 '02-24-2023.csv',
 '02-24-2022.csv',
 '02-24-2021.csv',
 '02-24-2020.csv',
 '02-23-2023.csv',
 '02-23-2022.csv',
 '02-23-2021.csv',
 '02-23-2020.csv',
 '02-22-2023.csv',
 '02-22-2022.csv',
 '02-22-2021.csv',
 '02-22-2020.csv',
 '02-21-2023.csv',
 '02-21-2022.csv',
 '02-21-2021.csv',
 '02-21-2020.csv',
 '02-20-2023.csv',
 '02-20-2022.csv',
 '02-20-2021.csv',
 '02-20-2020.csv',
 '02-19-2023.csv',
 '02-19-2022.csv',
 '02-19-2021.csv',
 '02-19-2020.csv',
 '02-18-2023.csv',
 '02-18-2022.csv',
 '02-18-2021.csv',
 '02-18-2020.csv',
 '02-17-2023.csv',
 '02-17-2022.csv',
 '02-17-2021.csv',
 '02-17-2020.csv',
 '02-16-2023.csv',
 '02-16-2022.csv',
 '02-16-2021.csv',
 '02-16-2020.csv',
 '02-15-2023.csv',
 '02-15-2022.csv',
 '02-15-2021.csv',
 '02-15-2020.csv',
 '02-14-2023.csv',
 '02-14-2022.csv',
 '02-14-2021.csv',
 '02-14-2020.csv',
 '02-13-2023.csv',
 '02-13-2022.csv',
 '02-13-2021.csv',
 '02-13-2020.csv',
 '02-12-2023.csv',
 '02-12-2022.csv',
 '02-12-2021.csv',
 '02-12-2020.csv',
 '02-11-2023.csv',
 '02-11-2022.csv',
 '02-11-2021.csv',
 '02-11-2020.csv',
 ...]

%Y = 연도 4자리 = 2026
%y = 연도 2자리 = 26
%m = 월 2자리 = 09
%d = 일 2자리 = 09
%H = 24시간 = 14 
%I = 12시간 = 02
%M = 분2자리 = 30
%S = 초2자리 = 08
%P = AM/PM

In [ ]:
import pandas as pd
import json

PATH = "csse_covid_19_data/csse_covid_19_daily_reports/"

with open("./csse_covid_19_data/country_convert.json", "r", encoding = "utf-8-sig") as json_file :
    json_data = json.load(json_file)

def country_name_convert(row) :
    if row["Country_Region"] in json_data :
        row["Country_Region"] = json_data[row["Country_Region"]]
    return row["Country_Region"]

def create_dateframe(filename) :
    doc = pd.read_csv(f"{PATH}{filename}", encoding = "utf-8-sig")

    try : 
        doc = doc[["Country_Region","Confirmed"]]
    except : 
        doc = doc[["Country/Region","Confirmed"]]
        doc.columns = ["Country_Region","Confirmed"]

    
    doc = doc.dropna(subset = ["Confirmed"])
    doc["Country_Region"] = doc.apply(country_name_convert, axis = 1)
    doc = doc.astype({"Confirmed" : "int64"})
    doc = doc.groupby("Country_Region").sum()

    date_column = filename.split(".")[0].lstrip("0").replace("-", "/")
    doc.columns = [date_column]

    return doc

In [ ]:
import os

def generate_dateframe_by_path(PTTH) :
    file_list, csv_list = os.listdir(PATH), list()
    
    for file in file_list :
        if file.split(".")[-1] == "csv" :
            csv_list.append(file)
    
    print(csv_list)