**** 아나콘다 라는 프로그램을 사용하는 이유!!

1. 학습 목적 및 목표 : 파이썬 프로그래밍 언어를 활용한 데이터 수집·분석
2. 파이썬이라는 프로그래밍 언어 : 다른 프로그래밍 언어보다 학습 속도·효과가 빠르기 때문에 (난이도 쉬움)
3. 파이썬이라는 언어를 다룰 수 있는 환경 2가지
   - 클라우드 기반 서비스 : 코랩 (네트워크 = 통신 영향)
   - 로컬 기반 서비스 : 내 컴퓨터에 프로그램을 안정적으로 설치해서 파일 관리
        > Web Editor : vscode(MS) -> FrontEnd 개발 (서버, 백엔드, 디비x) 시각적인 요소 개발 > 내가 작성한 코드가 실시간 웹 구현
        > Atom, Bracket 등
        > DB, Backend 관련 코드 작성 > extension 필수 // 가상환경 => python (3.초반 ~ 3.중반 버전) venv(가상환경을 만들어줘야 함)
    - IDE : 통합개발환경 = Integrated Devlopment Environment
        > 웹 에디터처럼 굳이 프로그래밍 언어의 버전에 따라서 혹은 운영체제 등의 환경에 따라서 별도의 확장 플러그인 및 가상환경을 설치 및 세팅하지 않아도 통합개발 환경 만으로도 모든 것을 구현할 수 있도록 만들어진 프로그램
            > 이클립스 = 자바, C
            > 파이참 = 파이썬 (유료)
            > 파이썬 전용 통합 개발환경 프로그램 : 무료, 버전관리, 불필요한 가상환경, 로컬 부담 X => 아나콘다

*** Pandas 실무에서 사용목적
1. 테이블형 데이터를 다루는 데 있어서 압도적인 기능
2. 원본 데이터(raw data)의 전처리(preprocessing) 및 정제(cleansing) 작업 시, 비교적 간단한 코드만으로 가능
3. 데이터 분석 기법을 활용할 때에 굉장히 많이 등장
    - EDA : 탐색적 데이터 분석 = Exploratory Data Analysis
      > 본격적인 데이터 분석 전, 데이터 사이즈, 결측치, 이상치, 평균·중앙값, 사분위 데이터 등을 통해서 데이터의 패턴을 파악하기 위한 목적
    - LDA : 잠재적 주제 도출 분석 과정 = Latent Dirichlet Allocation = 잠재 디리클레 할당
      > EDA 과정을 걸쳐서 충분히 분석할만한 가치가 있다고 판단은 하였으나, 파편화되어있는 데이터들이 어떤 주제로 구성되어 있는지를 분류·파악하기 위한 목적
    - ETL : 데이터 추출 처리 분석 = Extract Transform Load
      > 원본 데이터 = 원시데이터는 정보가(데이터의 패턴 조회, 가설 설정) 아닙니다. -> 원시 데이터를 유용한 정보성 요소로 변환시키도록 하기 위한 분석 과정
      > 데이터의 패턴을 조회하고 여기에 대한 가설을 설정하면 정보가 됨

In [ ]:
# Pandas : 시리즈, 데이터프레임
# 시리즈(series) : 1차원 데이터 -> 단일 데이터 -> 한 줄로 되어있음
# 데이터프레임(dataframe) : 복수의 시리즈가 모여서 만들어진 2차원 데이터 -> 행·열 테이블
# CRUD => SQL => DDL DML DTL

In [3]:
import pandas as pd

## 데이터를 표기할 때에는 반드시 대괄호로 묶어서 표기하기
# seriesdata = pd.Series([70, 60, 90])
# seriesdata = pd.Series([True, False, True])
seriesdata = pd.Series(["A", "B", "C"])
seriesdata

0    A
1    B
2    C
dtype: object

In [12]:
## 전체 열을 표기할 때에는 중괄호
df = pd.DataFrame({
    "미국" : [2.1, 2.2, 2.3],
    "한국" : [0.4, 0.5, 0.45],
    "중국" : [10, 13, 15]
}, index = [2000, 2010, 2020])

df

       미국    한국  중국
2000  2.1  0.40  10
2010  2.2  0.50  13
2020  2.3  0.45  15

In [8]:
df.index # 데이터프레임 - 인덱스, 컬럼, 로우
df.index = [2001, 2002, 2003]

In [13]:
df.columns

Index(['미국', '한국', '중국'], dtype='object')

In [14]:
df.columns = ["일본","필리핀","러시아"]

In [15]:
df.values

array([[ 2.1 ,  0.4 , 10.  ],
       [ 2.2 ,  0.5 , 13.  ],
       [ 2.3 ,  0.45, 15.  ]])

In [22]:
df = pd.DataFrame({
    "년도" : [2000, 2010, 2020],
    "미국" : [2.1, 2.2, 2.3],
    "한국" : [0.4, 0.5, 0.45],
    "중국" : [10, 13, 15]
})

df

     년도   미국    한국  중국
0  2000  2.1  0.40  10
1  2010  2.2  0.50  13
2  2020  2.3  0.45  15

In [18]:
df.set_index("년도")

       미국    한국  중국
년도
2000  2.1  0.40  10
2010  2.2  0.50  13
2020  2.3  0.45  15

In [19]:
df

     년도   미국    한국  중국
0  2000  2.1  0.40  10
1  2010  2.2  0.50  13
2  2020  2.3  0.45  15

In [32]:
df = df.set_index("년도")
df

       미국    한국  중국
년도
2000  2.1  0.40  10
2010  2.2  0.50  13
2020  2.3  0.45  15

In [28]:
df.index.name = "연도"
df

      년도   미국    한국  중국
연도
0   2000  2.1  0.40  10
1   2010  2.2  0.50  13
2   2020  2.3  0.45  15

In [23]:
## 다시 df 초기화
df

     년도   미국    한국  중국
0  2000  2.1  0.40  10
1  2010  2.2  0.50  13
2  2020  2.3  0.45  15

In [29]:
# 컬럼즈, 인덱스
df.iloc[2]

년도    2020.00
미국       2.30
한국       0.45
중국      15.00
Name: 2, dtype: float64

In [ ]:
df = df.set_index("년도")

In [33]:
df.loc[2020]

미국     2.30
한국     0.45
중국    15.00
Name: 2020, dtype: float64

In [35]:
type(df.loc[2000])

pandas.core.series.Series

In [37]:
type(df["미국"])

pandas.core.series.Series

In [38]:
df["미국"][2000]

np.float64(2.1)

In [41]:
df.loc[2000]["미국"]

np.float64(2.1)

In [43]:
df["일본"] = [1, 2, 3]

In [44]:
df

       미국    한국  중국  일본
년도
2000  2.1  0.40  10   1
2010  2.2  0.50  13   2
2020  2.3  0.45  15   3

In [45]:
del df["일본"]

In [46]:
df

       미국    한국  중국
년도
2000  2.1  0.40  10
2010  2.2  0.50  13
2020  2.3  0.45  15

In [48]:
df.loc[2030] = [1, 2, 3]

In [49]:
df

       미국    한국  중국
년도
2000  2.1  0.40  10
2010  2.2  0.50  13
2020  2.3  0.45  15
2030  1.0  2.00   3

In [50]:
df.drop([2020])

       미국   한국  중국
년도
2000  2.1  0.4  10
2010  2.2  0.5  13
2030  1.0  2.0   3

In [51]:
df

       미국    한국  중국
년도
2000  2.1  0.40  10
2010  2.2  0.50  13
2020  2.3  0.45  15
2030  1.0  2.00   3

In [53]:
# 복제

# 데이터 프레임 재할당 = 별도의 백업 X
# 데이터 프레임 복제 = 기존 데이터 프레임을 둔 상태로, 신규로 데아터 프레임을 생성하는 경우

## 가지고 오려는 요소에서 [] 한 번 쓰이고, 참인 요소 가져오기 위해 []가 또 쓰임
df2 = df[["한국", "중국"]].copy()
df2

        한국  중국
년도
2000  0.40  10
2010  0.50  13
2020  0.45  15
2030  2.00   3